insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR1J',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org_v',0,'N',1,'N','Y',null,0,'pk_org_v','pu.po_pricesettle.pk_org_v',null,'N',0,null,'1002Z81000000001BR1F','@@@@',0,'采购组织版本',null,null,'N',0,4,'po_pricesettle','po_pricesettle',0,'2012-06-28 09:21:47','N',null,null,null,0,1,'N',1,null,1,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR1K',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbillcode',0,'N',1,'Y','Y',null,0,'vbillcode','pu.po_pricesettle.vbillcode',null,'N',0,null,'1002Z81000000001BR1F','@@@@',0,null,null,null,'N',1,5,'po_pricesettle','价格结算单',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,1,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR1L',1,-1,null,null,0,0,null,-1,'N',null,-1,'dbilldate',0,'N',1,'N','Y',null,0,'dbilldate','pu.po_pricesettle.dbilldate',null,'N',1,null,'1002Z81000000001BR1F','@@@@',0,null,null,null,'N',1,6,'po_pricesettle',null,0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,1,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR1N',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_storeorg_v',0,'N',1,'N','Y',null,0,'pk_storeorg_v','pu.po_pricesettle.pk_storeorg_v','pk_storeorg=pk_stockorg','N',0,null,'1002Z81000000001BR1F','@@@@',0,'库存组织版本',null,null,'N',1,8,'po_pricesettle','po_pricesettle',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,1,8)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR1O',1,-1,null,null,0,1,null,-1,'Y',null,-1,'pk_supplier',0,'N',1,'Y','Y',null,0,'pk_supplier','pu.po_pricesettle.pk_supplier',null,'N',1,null,'1002Z81000000001BR1F','@@@@',0,'供应商档案',null,null,'N',1,9,'po_pricesettle','价格结算单',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,1,9)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR1P',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_employee',0,'N',1,'N','Y',null,0,'pk_employee','pu.po_pricesettle.pk_employee',null,'N',0,null,'1002Z81000000001BR1F','@@@@',0,'人员',null,null,'N',1,10,'po_pricesettle','价格结算单',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,1,10)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR1R',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_dept_v',0,'N',1,'N','Y',null,0,'pk_dept_v','pu.po_pricesettle.pk_dept_v','pk_dept=pk_dept','N',0,null,'1002Z81000000001BR1F','@@@@',0,'部门版本',null,null,'N',1,12,'po_pricesettle','po_pricesettle',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,1,12)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR1T',1,-1,null,null,0,0,null,-1,'N',null,-1,'ccurrencyid',0,'N',1,'N','N',null,0,'ccurrencyid','pu.po_pricesettle.ccurrencyid',null,'N',0,null,'1002Z81000000001BR1F','@@@@',0,'币种档案',null,null,'N',0,14,'po_pricesettle','价格结算单',0,'2012-06-28 09:21:47','N',null,null,null,0,0,'N',0,null,1,14)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR2F',1,-1,null,null,0,0,null,-1,'N',null,-1,'fbillstatus',0,'N',1,'N','Y',null,0,'fbillstatus','pu.po_pricesettle.fbillstatus',null,'N',0,null,'1002Z81000000001BR1F','@@@@',0,null,null,null,'N',1,36,'po_pricesettle','po_pricesettle',0,'2012-06-28 09:21:47','N',null,null,null,0,1,'N',1,null,1,36)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR2N',1,-1,null,null,0,0,null,-1,'N',null,-1,'crowno',0,'N',1,'N','Y',null,0,'crowno','pu.po_pricesettle_b.crowno',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,null,null,'N',1,4,'body_material','物料相关信息',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR2O',1,-1,null,null,0,0,null,-1,'N',null,-1,'vcheckvalue',0,'N',1,'N','Y',null,0,'vcheckvalue','pu.po_pricesettle_bb.vcheckvalue',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,null,null,'N',1,5,'body_hqhp','body_hqhp',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR2P',1,-1,'物料编码',null,0,0,null,-1,'Y',null,-1,'pk_material',0,'N',1,'Y','Y',null,0,'pk_material','pu.po_pricesettle_b.pk_material',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,'物料（多版本）,code=N','UC000-0002911',null,'N',1,5,'body_material','物料相关信息',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR2Q',1,-1,null,null,0,0,null,-1,'N',null,-1,'nstandcalvalue',0,'N',1,'N','Y',null,0,'nstandcalvalue','pu.po_pricesettle_bb.nstandcalvalue',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,null,null,'N',1,6,'body_hqhp','body_hqhp',1,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR2R',1,-1,null,null,0,0,null,-1,'N','pk_material',-1,'pk_material.name',0,'N',1,'N','Y',null,0,'name','uap.material.name',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,null,null,'N',1,6,'body_material','body_material',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR2T',1,-1,null,null,0,0,null,-1,'N','pk_material',-1,'pk_material.materialtype',0,'N',1,'N','Y',null,0,'materialtype','uap.material.materialtype',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,null,null,'N',1,7,'body_material','body_material',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,7)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR2V',1,-1,null,null,0,0,null,-1,'N','pk_material',-1,'pk_material.materialspec',0,'N',1,'N','Y',null,0,'materialspec','uap.material.materialspec',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,null,null,'N',1,8,'body_material','body_material',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,8)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR2W',1,-1,'优质优价项目编码',null,0,0,null,-1,'N','cqpbasestandid',-1,'cqpbasestandid.pk_checkitem.vcheckitemcode',0,'N',1,'N','Y',null,0,'pk_checkitem.vcheckitemcode','qc.qc_checkitem.vcheckitemcode',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,'14004180003',null,'N',1,9,'body_hqhp','body_hqhp',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,9)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR2Y',1,-1,'优质优价项目名称',null,0,0,null,-1,'N','cqpbasestandid',-1,'cqpbasestandid.pk_checkitem.vcheckitemname',0,'N',1,'N','Y',null,0,'pk_checkitem.vcheckitemname','qc.qc_checkitem.vcheckitemname',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,'14004180005',null,'N',1,10,'body_hqhp','body_hqhp',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,10)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR30',1,-1,'质量单位',null,0,0,null,-1,'N','cqpbasestandid',-1,'cqpbasestandid.pk_checkitem.pk_measdoc',0,'N',1,'N','Y',null,0,'pk_checkitem.pk_measdoc','qc.qc_checkitem.pk_measdoc',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,'计量单位,code=N','14004180007',null,'N',1,11,'body_hqhp','body_hqhp',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,11)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR33',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbaselowlmt',0,'N',1,'N','Y',null,0,'vbaselowlmt','pu.po_pricesettle_bb.vbaselowlmt',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,null,null,'N',1,12,'body_hqhp','body_hqhp',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,12)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR35',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbaseuplmt',0,'N',1,'N','Y',null,0,'vbaseuplmt','pu.po_pricesettle_bb.vbaseuplmt',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,null,null,'N',1,13,'body_hqhp','body_hqhp',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,13)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR37',1,-1,null,null,0,0,null,-1,'N',null,-1,'faccumtype',0,'N',1,'N','Y',null,0,'faccumtype','pu.po_pricesettle_bb.faccumtype',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,null,null,'N',1,14,'body_hqhp','body_hqhp',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,14)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR39',1,-1,null,null,0,0,null,-1,'N',null,-1,'ipriority',0,'N',1,'N','Y',null,0,'ipriority','pu.po_pricesettle_bb.ipriority',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,null,null,'N',1,15,'body_hqhp','body_hqhp',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,15)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR3D',1,-1,null,null,0,0,null,-1,'N',null,-1,'vprecondname',0,'N',1,'N','Y',null,0,'vprecondname','pu.po_pricesettle_bb.vprecondname',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,null,null,'N',1,17,'body_hqhp','body_hqhp',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,17)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR3G',1,0,'标准类型',null,0,0,null,-1,'N',null,20,'fstandtypename',0,'N',1,'N','Y','fstandardtype->getcolvalue(purp_qpstandard ,fstandardtype , pk_qpstandard,cqpstandbid );fstandtypename->iif(fstandardtype==0 ,"扣吨" ,"调价" );',0,null,null,null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,'14004180004',null,'N',1,19,'body_hqhp','优质优价相关信息',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,19)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR3I',1,-1,null,null,0,0,null,-1,'N',null,-1,'fvaluetype',0,'N',1,'N','Y',null,0,'fvaluetype','pu.po_pricesettle_bb.fvaluetype',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,null,null,'N',1,20,'body_hqhp','body_hqhp',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,20)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR3L',1,-1,null,null,0,0,null,-1,'N',null,-1,'fadjusttype',0,'N',1,'N','Y',null,0,'fadjusttype','pu.po_pricesettle_bb.fadjusttype',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,null,null,'N',1,21,'body_hqhp','body_hqhp',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,21)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR3M',1,-1,null,null,0,0,null,-1,'N',null,-1,'bincludelower',0,'N',1,'N','Y',null,0,'bincludelower','pu.po_pricesettle_bb.bincludelower',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,null,null,'N',1,22,'body_hqhp','body_hqhp',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,22)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR3O',1,-1,null,null,0,0,null,-1,'N',null,-1,'castunitid',0,'N',1,'N','Y',null,0,'castunitid','pu.po_pricesettle_b.castunitid',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,'计量单位,code=N',null,null,'N',1,23,'body_material','物料相关信息',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,23)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR3P',1,-1,null,null,0,0,null,-1,'N',null,-1,'vlower',0,'N',1,'N','Y',null,0,'vlower','pu.po_pricesettle_bb.vlower',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,null,null,'N',1,23,'body_hqhp','body_hqhp',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,23)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR3R',1,-1,null,null,0,0,null,-1,'N',null,-1,'vupper',0,'N',1,'N','Y',null,0,'vupper','pu.po_pricesettle_bb.vupper',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,null,null,'N',1,24,'body_hqhp','body_hqhp',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,24)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR3S',1,-1,null,null,0,0,null,-1,'N',null,-1,'bincludeupper',0,'N',1,'N','Y',null,0,'bincludeupper','pu.po_pricesettle_bb.bincludeupper',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,null,null,'N',1,25,'body_hqhp','body_hqhp',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,25)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR3T',1,-1,null,null,0,0,null,-1,'N',null,-1,'cunitid',0,'N',1,'N','N',null,0,'cunitid','pu.po_pricesettle_b.cunitid',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,'计量单位,code=N',null,null,'N',0,25,'body_material','物料相关信息',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,25)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR3U',1,0,'调整基数',null,0,0,null,-1,'N',null,20,'dbasevalue',0,'N',1,'N','Y','dbasevalue->getcolvalue(purp_qpstandard_b ,dbasevalue , pk_qpstandard_b,cqpstandbid )',0,null,null,null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,'14004180001',null,'N',1,26,'body_hqhp','优质优价相关信息',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,26)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR3V',1,-1,null,null,0,0,null,-1,'N',null,-1,'nastarrvnum',0,'N',1,'N','Y',null,0,'nastarrvnum','pu.po_pricesettle_b.nastarrvnum',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,null,null,'N',1,26,'body_material','物料相关信息',1,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,26)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR3W',1,0,'调整幅度',null,0,0,null,-1,'N',null,20,'dadjustvalue',0,'N',1,'N','Y','dadjustvalue->getcolvalue(purp_qpstandard_b ,dadjustvalue ,pk_qpstandard_b , cqpstandbid)',0,null,null,null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,'14004180002',null,'N',1,27,'body_hqhp','优质优价相关信息',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,27)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR3Y',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfrmlcode',0,'N',1,'N','Y',null,0,'vfrmlcode','pu.po_pricesettle_bb.vfrmlcode',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,null,null,'N',1,28,'body_hqhp','body_hqhp',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,28)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR3Z',1,-1,null,null,0,0,null,-1,'N',null,-1,'nastshouldinnum',0,'N',1,'N','Y',null,0,'nastshouldinnum','pu.po_pricesettle_b.nastshouldinnum',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,null,null,'N',1,28,'body_material','物料相关信息',1,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,28)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR40',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfrmlname',0,'N',1,'N','Y',null,0,'vfrmlname','pu.po_pricesettle_bb.vfrmlname',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,null,null,'N',1,29,'body_hqhp','body_hqhp',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,29)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR42',1,-1,null,null,0,0,null,-1,'N',null,-1,'nastinnum',0,'N',1,'N','Y',null,0,'nastinnum','pu.po_pricesettle_b.nastinnum',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,null,null,'N',1,30,'body_material','物料相关信息',1,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,30)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR46',1,-1,null,null,0,0,null,-1,'N',null,-1,'ntaxrate',0,'N',1,'N','Y',null,0,'ntaxrate','pu.po_pricesettle_b.ntaxrate',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,null,null,'N',1,32,'body_material','物料相关信息',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,32)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR47',1,-1,null,null,0,0,null,-1,'N',null,-1,'ftaxtypeflag',0,'N',1,'N','Y',null,0,'ftaxtypeflag','pu.po_pricesettle_b.ftaxtypeflag',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,null,null,'N',1,33,'body_material','物料相关信息',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,33)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR48',1,-1,null,null,0,0,null,-1,'N',null,-1,'ncalqualprice',0,'N',1,'N','Y',null,0,'ncalqualprice','pu.po_pricesettle_b.ncalqualprice',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,null,null,'N',1,34,'body_material','物料相关信息',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,34)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR49',1,-1,'本币含税基价',null,0,0,null,-1,'N',null,-1,'nbasetaxprice',0,'N',1,'N','Y',null,0,'nbasetaxprice','pu.po_pricesettle_b.nbasetaxprice',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,'14004180006',null,'N',1,35,'body_material',null,0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,35)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR4B',1,-1,null,null,0,1,null,-1,'N',null,-1,'ntaxprice',0,'N',1,'N','Y',null,0,'ntaxprice','pu.po_pricesettle_b.ntaxprice',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,null,null,'N',1,37,'body_material','物料相关信息',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,37)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR4C',1,-1,null,null,0,1,null,-1,'N',null,-1,'nprice',0,'N',1,'N','Y',null,0,'nprice','pu.po_pricesettle_b.nprice',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,null,null,'N',1,38,'body_material','物料相关信息',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,38)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR4D',1,-1,null,null,0,0,null,-1,'N',null,-1,'ntaxmny',0,'N',1,'N','Y','ntaxmny->ninnum*ntaxprice',0,'ntaxmny','pu.po_pricesettle_b.ntaxmny',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,null,null,'N',1,39,'body_material','body_material',1,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,39)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR4E',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_stordoc',0,'N',1,'N','Y',null,0,'pk_stordoc','pu.po_pricesettle_b.pk_stordoc',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,'仓库,code=N',null,null,'N',1,40,'body_material','物料相关信息',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,40)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR4F',1,-1,null,null,0,0,null,-1,'N',null,-1,'dbizdate',0,'N',1,'N','Y',null,0,'dbizdate','pu.po_pricesettle_b.dbizdate',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,null,null,'N',1,41,'body_material','物料相关信息',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,41)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR4J',1,-1,'入库单号',null,0,0,null,-1,'Y',null,-1,'vsourcecode',0,'N',1,'Y','Y',null,0,'vsourcecode','pu.po_pricesettle_b.vsourcecode',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,'UC000-0000371',null,'N',1,45,'body_material','物料相关信息',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,45)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR4N',1,-1,null,null,0,0,null,-1,'N',null,-1,'vcontractcode',0,'N',1,'N','Y',null,0,'vcontractcode','pu.po_pricesettle_b.vcontractcode',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,null,null,'N',1,49,'body_material','物料相关信息',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,49)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR4P',1,-1,null,null,0,0,null,-1,'N',null,-1,'cordercode',0,'N',1,'N','Y',null,0,'cordercode','pu.po_pricesettle_b.cordercode',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,null,null,'N',1,51,'body_material','物料相关信息',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,51)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR4R',1,-1,null,null,0,0,null,-1,'N',null,-1,'ccheckbillcode',0,'N',1,'N','Y',null,0,'ccheckbillcode','pu.po_pricesettle_b.ccheckbillcode',null,'N',0,null,'1002Z81000000001BR1F','@@@@',1,null,null,null,'N',1,53,'body_material','物料相关信息',0,'2012-06-28 09:21:47','N',null,null,null,1,1,'N',1,null,100,53)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR5I',1,-1,null,'@SYSOPER',0,0,null,-1,'N',null,-1,'billmaker',0,'N',1,'N','Y',null,0,'billmaker','pu.po_pricesettle.billmaker',null,'N',0,null,'1002Z81000000001BR1F','@@@@',2,'用户',null,null,'N',1,1,'tailinfo',null,0,'2012-06-28 09:21:47','N',null,null,null,0,1,'N',1,null,1,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR5K',1,-1,null,null,0,0,null,-1,'N',null,-1,'dbaseprice',0,'N',1,'N','N',null,0,'dbaseprice','pu.po_pricesettle_b.dbaseprice',null,'N',0,null,'1002Z81000000001BR1F','@@@@',2,null,null,null,'N',1,1,'tail_hqhp','tail_hqhp',0,'2012-06-28 09:21:47','N',null,null,null,0,1,'N',1,null,1,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR5L',1,-1,null,null,0,0,null,-1,'N',null,-1,'dmakedate',0,'N',1,'N','Y',null,0,'dmakedate','pu.po_pricesettle.dmakedate',null,'N',0,null,'1002Z81000000001BR1F','@@@@',2,null,null,null,'N',1,2,'tailinfo','tailinfo',0,'2012-06-28 09:21:47','N',null,null,null,0,1,'N',1,null,1,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR5M',1,-1,null,null,0,0,null,-1,'N',null,-1,'vschemefrmlname',0,'N',1,'N','N',null,0,'vschemefrmlname','pu.po_pricesettle_b.vschemefrmlname',null,'N',0,null,'1002Z81000000001BR1F','@@@@',2,null,null,null,'N',1,2,'tail_hqhp',null,0,'2012-06-28 09:21:48','N',null,null,null,0,1,'N',1,null,1,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR5N',1,-1,null,'@SYSOPER',0,0,null,-1,'N',null,-1,'creator',0,'N',1,'N','Y',null,0,'creator','pu.po_pricesettle.creator',null,'N',0,null,'1002Z81000000001BR1F','@@@@',2,'用户',null,null,'N',1,2,'tail_material',null,0,'2012-06-28 09:21:48','N',null,null,null,0,1,'N',1,null,1,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR5O',1,-1,null,null,0,0,null,-1,'N',null,-1,'creationtime',0,'N',1,'N','Y',null,0,'creationtime','pu.po_pricesettle.creationtime',null,'N',0,null,'1002Z81000000001BR1F','@@@@',2,null,null,null,'N',1,3,'tail_material',null,0,'2012-06-28 09:21:48','N',null,null,null,0,1,'N',1,null,1,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR5P',1,-1,null,null,0,0,null,-1,'N',null,-1,'nschemecalvalue',0,'N',1,'N','N',null,0,'nschemecalvalue','pu.po_pricesettle_b.nschemecalvalue',null,'N',0,null,'1002Z81000000001BR1F','@@@@',2,null,null,null,'N',1,3,'tail_hqhp',null,0,'2012-06-28 09:21:48','N',null,null,null,0,1,'N',1,null,1,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR5Q',1,-1,null,null,0,0,null,-1,'N',null,-1,'approver',0,'N',1,'N','Y',null,0,'approver','pu.po_pricesettle.approver',null,'N',0,null,'1002Z81000000001BR1F','@@@@',2,'用户',null,null,'N',1,3,'tailinfo',null,0,'2012-06-28 09:21:48','N',null,null,null,0,1,'N',1,null,1,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR5R',1,-1,null,null,0,0,null,-1,'N',null,-1,'modifier',0,'N',1,'N','Y',null,0,'modifier','pu.po_pricesettle.modifier',null,'N',0,null,'1002Z81000000001BR1F','@@@@',2,'用户',null,null,'N',1,4,'tail_material',null,0,'2012-06-28 09:21:48','N',null,null,null,0,1,'N',1,null,1,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR5S',1,-1,null,null,0,0,null,-1,'N',null,-1,'taudittime',0,'N',1,'N','Y',null,0,'taudittime','pu.po_pricesettle.taudittime',null,'N',0,null,'1002Z81000000001BR1F','@@@@',2,null,null,null,'N',1,4,'tailinfo',null,0,'2012-06-28 09:21:48','N',null,null,null,0,1,'N',1,null,1,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BR5T',1,-1,null,null,0,0,null,-1,'N',null,-1,'modifiedtime',0,'N',1,'N','Y',null,0,'modifiedtime','pu.po_pricesettle.modifiedtime',null,'N',0,null,'1002Z81000000001BR1F','@@@@',2,null,null,null,'N',1,5,'tail_material',null,0,'2012-06-28 09:21:48','N',null,null,null,0,1,'N',1,null,1,5)
go

