/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.pu.m21.entity;

import nc.vo.pu.pub.enumeration.EnumDiscounttaxtype;
import nc.vo.pub.IVOMeta;
import nc.vo.pub.SuperVO;
import nc.vo.pub.lang.UFBoolean;
import nc.vo.pub.lang.UFDate;
import nc.vo.pub.lang.UFDateTime;
import nc.vo.pub.lang.UFDouble;
import nc.vo.pubapp.pattern.model.meta.entity.vo.VOMetaFactory;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * 
 * @author
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class OrderPriceVO extends SuperVO {
  /**
   * 预警类型
   */
  public static final String ALERTTYPE = "alertType";

  /**
   * 是否有效
   */
  public static final String BVALIDATE = "bvalidate";

  /**
   * 单位
   */
  public static final String CASTUNITID = "castunitid";

  /**
   * 币种
   */
  public static final String CORIGCURRENCYID = "corigcurrencyid";

  /**
   * 报价单位
   */
  public static final String CQTUNITID = "cqtunitid";

  /**
   * 主单位
   */
  public static final String CUNITID = "cunitid";

  /**
   * 每天预警
   */
  public static final String DAILY = "DAILY";

  /**
   * 订单日期
   */
  public static final String DBILLDATE = "dbilldate";

  /**
   * 扣税类别
   */
  public static final String FTAXTYPEFLAG = "ftaxtypeflag";

  /**
   * 最后修改时间
   */
  public static final String MODIFIEDTIME = "modifiedtime";

  /**
   * 每月预警
   */
  public static final String MONTHLY = "MONTHLY";

  /**
   * 主本币无税净价
   */
  public static final String NNETPRICE = "nnetprice";

  /**
   * 主本币无税净最低价
   */
  public static final String NNETPRICEM = "nnetpricem";

  /**
   * 不可抵扣税率
   */
  public static final String NNOSUBTAXRAT = "nnosubtaxrate";

  /**
   * 主无税净价
   */
  public static final String NORIGNETPRICE = "norignetprice";

  /**
   * 主无税净最低价
   */
  public static final String NORIGNETPRICEM = "norignetpricem";

  /**
   * 主无税单价
   */
  public static final String NORIGPRICE = "norigprice";

  /**
   * 主含税净价
   */
  public static final String NORIGTAXNETPRICE = "norigtaxnetprice";

  /**
   * 主含税净最低价
   */
  public static final String NORIGTAXNETPRICEM = "norigtaxnetpricem";

  /**
   * 主含税单价
   */
  public static final String NORIGTAXPRICE = "norigtaxprice";

  /**
   * 主本币无税单价
   */
  public static final String NPRICE = "nprice";

  /**
   * 本币无税净价
   */
  public static final String NQTNETPRICE = "nqtnetprice";

  /**
   * 无税净价
   */
  public static final String NQTORIGNETPRICE = "nqtorignetprice";

  /**
   * 无税单价
   */
  public static final String NQTORIGPRICE = "nqtorigprice";

  /**
   * 含税净价
   */
  public static final String NQTORIGTAXNETPRC = "nqtorigtaxnetprc";

  /**
   * 含税单价
   */
  public static final String NQTORIGTAXPRICE = "nqtorigtaxprice";

  /**
   * 本币无税单价
   */
  public static final String NQTPRICE = "nqtprice";

  /**
   * 本币含税净价
   */
  public static final String NQTTAXNETPRICE = "nqttaxnetprice";

  /**
   * 本币含税单价
   */
  public static final String NQTTAXPRICE = "nqttaxprice";

  /**
   * 主本币含税净价
   */
  public static final String NTAXNETPRICE = "ntaxnetprice";

  /**
   * 主本币含税净最低价
   */
  public static final String NTAXNETPRICEM = "ntaxnetpricem";

  /**
   * 主本币含税单价
   */
  public static final String NTAXPRICE = "ntaxprice";

  /**
   * 税率
   */
  public static final String NTAXRATE = "ntaxrate";

  /**
   * 收货库存组织(OID)
   */
  public static final String PK_ARRVSTOORG = "pk_arrvstoorg";

  /** 采购订单询价表－计算标识主键，此行记录表达了异步任务已经计算完成的订单时间 **/
  public final static String PK_CALC = "CALCZ800POORDERPRICE";

  /**
   * 采购询价
   */
  public static final String PK_ORDER_PRICE = "pk_order_price";

  /**
   * 采购组织版本信息
   */
  public static final String PK_ORG = "pk_org";

  /**
   * 结算财务组织(OID)
   */
  public static final String PK_PSFINANCEORG = "pk_psfinanceorg";

  /**
   * 物料信息
   */
  public static final String PK_SRCMATERIAL = "pk_srcmaterial";

  /**
   * 供应商
   */
  public static final String PK_SUPPLIER = "pk_supplier";

  /**
   * 时间戳
   */
  public static final String TS = "ts";

  /**
   * 按照默认方式创建构造子.
   * 创建日期:
   */
  public OrderPriceVO() {
    super();
  }

  /**
   * 获取是否有效
   * 
   * @return 是否有效
   */
  public UFBoolean getBvalidate() {
    return (UFBoolean) this.getAttributeValue(OrderPriceVO.BVALIDATE);
  }

  /**
   * 获取单位
   * 
   * @return 单位
   */
  public String getCastunitid() {
    return (String) this.getAttributeValue(OrderPriceVO.CASTUNITID);
  }

  /**
   * 获取币种
   * 
   * @return 币种
   */
  public String getCorigcurrencyid() {
    return (String) this.getAttributeValue(OrderPriceVO.CORIGCURRENCYID);
  }

  /**
   * 获取报价单位
   * 
   * @return 报价单位
   */
  public String getCqtunitid() {
    return (String) this.getAttributeValue(OrderPriceVO.CQTUNITID);
  }

  /**
   * 获取主单位
   * 
   * @return 主单位
   */
  public String getCunitid() {
    return (String) this.getAttributeValue(OrderPriceVO.CUNITID);
  }

  /**
   * 获取订单日期
   * 
   * @return 订单日期
   */
  public UFDate getDbilldate() {
    return (UFDate) this.getAttributeValue(OrderPriceVO.DBILLDATE);
  }

  /**
   * 获取扣税类别
   * 
   * @return 扣税类别
   * @see EnumDiscounttaxtype
   */
  public Integer getFtaxtypeflag() {
    return (Integer) this.getAttributeValue(OrderPriceVO.FTAXTYPEFLAG);
  }

  @Override
  public IVOMeta getMetaData() {
    IVOMeta meta = VOMetaFactory.getInstance().getVOMeta("pu.po_order_price");
    return meta;
  }

  /**
   * 获取最后修改时间
   * 
   * @return 最后修改时间
   */
  public UFDateTime getModifiedtime() {
    return (UFDateTime) this.getAttributeValue(OrderPriceVO.MODIFIEDTIME);
  }

  /**
   * 获取主本币无税净价
   * 
   * @return 主本币无税净价
   */
  public UFDouble getNnetprice() {
    return (UFDouble) this.getAttributeValue(OrderPriceVO.NNETPRICE);
  }

  /**
   * 获取主本币无税净最低价
   * 
   * @return 主本币无税净最低价
   */
  public UFDouble getNnetpricem() {
    return (UFDouble) this.getAttributeValue(OrderPriceVO.NNETPRICEM);
  }

  /**
   * 获取主无税净价
   * 
   * @return 主无税净价
   */
  public UFDouble getNorignetprice() {
    return (UFDouble) this.getAttributeValue(OrderPriceVO.NORIGNETPRICE);
  }

  /**
   * 获取主无税净最低价
   * 
   * @return 主无税净最低价
   */
  public UFDouble getNorignetpricem() {
    return (UFDouble) this.getAttributeValue(OrderPriceVO.NORIGNETPRICEM);
  }

  /**
   * 获取主无税单价
   * 
   * @return 主无税单价
   */
  public UFDouble getNorigprice() {
    return (UFDouble) this.getAttributeValue(OrderPriceVO.NORIGPRICE);
  }

  /**
   * 获取主含税净价
   * 
   * @return 主含税净价
   */
  public UFDouble getNorigtaxnetprice() {
    return (UFDouble) this.getAttributeValue(OrderPriceVO.NORIGTAXNETPRICE);
  }

  /**
   * 获取主含税净最低价
   * 
   * @return 主含税净最低价
   */
  public UFDouble getNorigtaxnetpricem() {
    return (UFDouble) this.getAttributeValue(OrderPriceVO.NORIGTAXNETPRICEM);
  }

  /**
   * 获取主含税单价
   * 
   * @return 主含税单价
   */
  public UFDouble getNorigtaxprice() {
    return (UFDouble) this.getAttributeValue(OrderPriceVO.NORIGTAXPRICE);
  }

  /**
   * 获取主本币无税单价
   * 
   * @return 主本币无税单价
   */
  public UFDouble getNprice() {
    return (UFDouble) this.getAttributeValue(OrderPriceVO.NPRICE);
  }

  /**
   * 获取本币无税净价
   * 
   * @return 本币无税净价
   */
  public UFDouble getNqtnetprice() {
    return (UFDouble) this.getAttributeValue(OrderPriceVO.NQTNETPRICE);
  }

  /**
   * 获取无税净价
   * 
   * @return 无税净价
   */
  public UFDouble getNqtorignetprice() {
    return (UFDouble) this.getAttributeValue(OrderPriceVO.NQTORIGNETPRICE);
  }

  /**
   * 获取无税单价
   * 
   * @return 无税单价
   */
  public UFDouble getNqtorigprice() {
    return (UFDouble) this.getAttributeValue(OrderPriceVO.NQTORIGPRICE);
  }

  /**
   * 获取含税净价
   * 
   * @return 含税净价
   */
  public UFDouble getNqtorigtaxnetprc() {
    return (UFDouble) this.getAttributeValue(OrderPriceVO.NQTORIGTAXNETPRC);
  }

  /**
   * 获取含税单价
   * 
   * @return 含税单价
   */
  public UFDouble getNqtorigtaxprice() {
    return (UFDouble) this.getAttributeValue(OrderPriceVO.NQTORIGTAXPRICE);
  }

  /**
   * 获取本币无税单价
   * 
   * @return 本币无税单价
   */
  public UFDouble getNqtprice() {
    return (UFDouble) this.getAttributeValue(OrderPriceVO.NQTPRICE);
  }

  /**
   * 获取本币含税净价
   * 
   * @return 本币含税净价
   */
  public UFDouble getNqttaxnetprice() {
    return (UFDouble) this.getAttributeValue(OrderPriceVO.NQTTAXNETPRICE);
  }

  /**
   * 获取本币含税单价
   * 
   * @return 本币含税单价
   */
  public UFDouble getNqttaxprice() {
    return (UFDouble) this.getAttributeValue(OrderPriceVO.NQTTAXPRICE);
  }

  /**
   * 获取主本币含税净价
   * 
   * @return 主本币含税净价
   */
  public UFDouble getNtaxnetprice() {
    return (UFDouble) this.getAttributeValue(OrderPriceVO.NTAXNETPRICE);
  }

  /**
   * 获取主本币含税净最低价
   * 
   * @return 主本币含税净最低价
   */
  public UFDouble getNtaxnetpricem() {
    return (UFDouble) this.getAttributeValue(OrderPriceVO.NTAXNETPRICEM);
  }

  /**
   * 获取主本币含税单价
   * 
   * @return 主本币含税单价
   */
  public UFDouble getNtaxprice() {
    return (UFDouble) this.getAttributeValue(OrderPriceVO.NTAXPRICE);
  }

  /**
   * 获取税率
   * 
   * @return 税率
   */
  public UFDouble getNtaxrate() {
    return (UFDouble) this.getAttributeValue(OrderPriceVO.NTAXRATE);
  }

  /**
   * <p>
   * 取得父VO主键字段.
   * <p>
   * 创建日期:
   * 
   * @return java.lang.String
   */
  @Override
  public java.lang.String getParentPKFieldName() {
    return null;
  }

  /**
   * 获取收货库存组织(OID)
   * 
   * @return 收货库存组织(OID)
   */
  public String getPk_arrvstoorg() {
    return (String) this.getAttributeValue(OrderPriceVO.PK_ARRVSTOORG);
  }

  /**
   * 获取采购询价
   * 
   * @return 采购询价
   */
  public String getPk_order_price() {
    return (String) this.getAttributeValue(OrderPriceVO.PK_ORDER_PRICE);
  }

  /**
   * 获取采购组织版本信息
   * 
   * @return 采购组织版本信息
   */
  public String getPk_org() {
    return (String) this.getAttributeValue(OrderPriceVO.PK_ORG);
  }

  /**
   * 获取结算财务组织(OID)
   * 
   * @return 结算财务组织(OID)
   */
  public String getPk_psfinanceorg() {
    return (String) this.getAttributeValue(OrderPriceVO.PK_PSFINANCEORG);
  }

  /**
   * 获取物料信息
   * 
   * @return 物料信息
   */
  public String getPk_srcmaterial() {
    return (String) this.getAttributeValue(OrderPriceVO.PK_SRCMATERIAL);
  }

  /**
   * 获取供应商
   * 
   * @return 供应商
   */
  public String getPk_supplier() {
    return (String) this.getAttributeValue(OrderPriceVO.PK_SUPPLIER);
  }

  /**
   * <p>
   * 取得表主键.
   * <p>
   * 创建日期:
   * 
   * @return java.lang.String
   */
  @Override
  public java.lang.String getPKFieldName() {
    return "pk_order_price";
  }

  /**
   * <p>
   * 返回表名称.
   * <p>
   * 创建日期:
   * 
   * @return java.lang.String
   */
  @Override
  public java.lang.String getTableName() {
    return "po_order_price";
  }

  /**
   * 获取时间戳
   * 
   * @return 时间戳
   */
  public UFDateTime getTs() {
    return (UFDateTime) this.getAttributeValue(OrderPriceVO.TS);
  }

  /**
   * 设置是否有效
   * 
   * @param bvalidate 是否有效
   */
  public void setBvalidate(UFBoolean bvalidate) {
    this.setAttributeValue(OrderPriceVO.BVALIDATE, bvalidate);
  }

  /**
   * 设置单位
   * 
   * @param castunitid 单位
   */
  public void setCastunitid(String castunitid) {
    this.setAttributeValue(OrderPriceVO.CASTUNITID, castunitid);
  }

  /**
   * 设置币种
   * 
   * @param corigcurrencyid 币种
   */
  public void setCorigcurrencyid(String corigcurrencyid) {
    this.setAttributeValue(OrderPriceVO.CORIGCURRENCYID, corigcurrencyid);
  }

  /**
   * 设置报价单位
   * 
   * @param cqtunitid 报价单位
   */
  public void setCqtunitid(String cqtunitid) {
    this.setAttributeValue(OrderPriceVO.CQTUNITID, cqtunitid);
  }

  /**
   * 设置主单位
   * 
   * @param cunitid 主单位
   */
  public void setCunitid(String cunitid) {
    this.setAttributeValue(OrderPriceVO.CUNITID, cunitid);
  }

  /**
   * 设置订单日期
   * 
   * @param dbilldate 订单日期
   */
  public void setDbilldate(UFDate dbilldate) {
    this.setAttributeValue(OrderPriceVO.DBILLDATE, dbilldate);
  }

  /**
   * 设置扣税类别
   * 
   * @param ftaxtypeflag 扣税类别
   * @see EnumDiscounttaxtype
   */
  public void setFtaxtypeflag(Integer ftaxtypeflag) {
    this.setAttributeValue(OrderPriceVO.FTAXTYPEFLAG, ftaxtypeflag);
  }

  /**
   * 设置最后修改时间
   * 
   * @param modifiedtime 最后修改时间
   */
  public void setModifiedtime(UFDateTime modifiedtime) {
    this.setAttributeValue(OrderPriceVO.MODIFIEDTIME, modifiedtime);
  }

  /**
   * 设置主本币无税净价
   * 
   * @param nnetprice 主本币无税净价
   */
  public void setNnetprice(UFDouble nnetprice) {
    this.setAttributeValue(OrderPriceVO.NNETPRICE, nnetprice);
  }

  /**
   * 设置主本币无税净最低价
   * 
   * @param nnetpricem 主本币无税净最低价
   */
  public void setNnetpricem(UFDouble nnetpricem) {
    this.setAttributeValue(OrderPriceVO.NNETPRICEM, nnetpricem);
  }

  /**
   * 设置主无税净价
   * 
   * @param norignetprice 主无税净价
   */
  public void setNorignetprice(UFDouble norignetprice) {
    this.setAttributeValue(OrderPriceVO.NORIGNETPRICE, norignetprice);
  }

  /**
   * 设置主无税净最低价
   * 
   * @param norignetpricem 主无税净最低价
   */
  public void setNorignetpricem(UFDouble norignetpricem) {
    this.setAttributeValue(OrderPriceVO.NORIGNETPRICEM, norignetpricem);
  }

  /**
   * 设置主无税单价
   * 
   * @param norigprice 主无税单价
   */
  public void setNorigprice(UFDouble norigprice) {
    this.setAttributeValue(OrderPriceVO.NORIGPRICE, norigprice);
  }

  /**
   * 设置主含税净价
   * 
   * @param norigtaxnetprice 主含税净价
   */
  public void setNorigtaxnetprice(UFDouble norigtaxnetprice) {
    this.setAttributeValue(OrderPriceVO.NORIGTAXNETPRICE, norigtaxnetprice);
  }

  /**
   * 设置主含税净最低价
   * 
   * @param norigtaxnetpricem 主含税净最低价
   */
  public void setNorigtaxnetpricem(UFDouble norigtaxnetpricem) {
    this.setAttributeValue(OrderPriceVO.NORIGTAXNETPRICEM, norigtaxnetpricem);
  }

  /**
   * 设置主含税单价
   * 
   * @param norigtaxprice 主含税单价
   */
  public void setNorigtaxprice(UFDouble norigtaxprice) {
    this.setAttributeValue(OrderPriceVO.NORIGTAXPRICE, norigtaxprice);
  }

  /**
   * 设置主本币无税单价
   * 
   * @param nprice 主本币无税单价
   */
  public void setNprice(UFDouble nprice) {
    this.setAttributeValue(OrderPriceVO.NPRICE, nprice);
  }

  /**
   * 设置本币无税净价
   * 
   * @param nqtnetprice 本币无税净价
   */
  public void setNqtnetprice(UFDouble nqtnetprice) {
    this.setAttributeValue(OrderPriceVO.NQTNETPRICE, nqtnetprice);
  }

  /**
   * 设置无税净价
   * 
   * @param nqtorignetprice 无税净价
   */
  public void setNqtorignetprice(UFDouble nqtorignetprice) {
    this.setAttributeValue(OrderPriceVO.NQTORIGNETPRICE, nqtorignetprice);
  }

  /**
   * 设置无税单价
   * 
   * @param nqtorigprice 无税单价
   */
  public void setNqtorigprice(UFDouble nqtorigprice) {
    this.setAttributeValue(OrderPriceVO.NQTORIGPRICE, nqtorigprice);
  }

  /**
   * 设置含税净价
   * 
   * @param nqtorigtaxnetprc 含税净价
   */
  public void setNqtorigtaxnetprc(UFDouble nqtorigtaxnetprc) {
    this.setAttributeValue(OrderPriceVO.NQTORIGTAXNETPRC, nqtorigtaxnetprc);
  }

  /**
   * 设置含税单价
   * 
   * @param nqtorigtaxprice 含税单价
   */
  public void setNqtorigtaxprice(UFDouble nqtorigtaxprice) {
    this.setAttributeValue(OrderPriceVO.NQTORIGTAXPRICE, nqtorigtaxprice);
  }

  /**
   * 设置本币无税单价
   * 
   * @param nqtprice 本币无税单价
   */
  public void setNqtprice(UFDouble nqtprice) {
    this.setAttributeValue(OrderPriceVO.NQTPRICE, nqtprice);
  }

  /**
   * 设置本币含税净价
   * 
   * @param nqttaxnetprice 本币含税净价
   */
  public void setNqttaxnetprice(UFDouble nqttaxnetprice) {
    this.setAttributeValue(OrderPriceVO.NQTTAXNETPRICE, nqttaxnetprice);
  }

  /**
   * 设置本币含税单价
   * 
   * @param nqttaxprice 本币含税单价
   */
  public void setNqttaxprice(UFDouble nqttaxprice) {
    this.setAttributeValue(OrderPriceVO.NQTTAXPRICE, nqttaxprice);
  }

  /**
   * 设置主本币含税净价
   * 
   * @param ntaxnetprice 主本币含税净价
   */
  public void setNtaxnetprice(UFDouble ntaxnetprice) {
    this.setAttributeValue(OrderPriceVO.NTAXNETPRICE, ntaxnetprice);
  }

  /**
   * 设置主本币含税净最低价
   * 
   * @param ntaxnetpricem 主本币含税净最低价
   */
  public void setNtaxnetpricem(UFDouble ntaxnetpricem) {
    this.setAttributeValue(OrderPriceVO.NTAXNETPRICEM, ntaxnetpricem);
  }

  /**
   * 设置主本币含税单价
   * 
   * @param ntaxprice 主本币含税单价
   */
  public void setNtaxprice(UFDouble ntaxprice) {
    this.setAttributeValue(OrderPriceVO.NTAXPRICE, ntaxprice);
  }

  /**
   * 设置税率
   * 
   * @param ntaxrate 税率
   */
  public void setNtaxrate(UFDouble ntaxrate) {
    this.setAttributeValue(OrderPriceVO.NTAXRATE, ntaxrate);
  }

  /**
   * 设置收货库存组织(OID)
   * 
   * @param pk_arrvstoorg 收货库存组织(OID)
   */
  public void setPk_arrvstoorg(String pk_arrvstoorg) {
    this.setAttributeValue(OrderPriceVO.PK_ARRVSTOORG, pk_arrvstoorg);
  }

  /**
   * 设置采购询价
   * 
   * @param pk_order_price 采购询价
   */
  public void setPk_order_price(String pk_order_price) {
    this.setAttributeValue(OrderPriceVO.PK_ORDER_PRICE, pk_order_price);
  }

  /**
   * 设置采购组织版本信息
   * 
   * @param pk_org 采购组织版本信息
   */
  public void setPk_org(String pk_org) {
    this.setAttributeValue(OrderPriceVO.PK_ORG, pk_org);
  }

  /**
   * 设置结算财务组织(OID)
   * 
   * @param pk_psfinanceorg 结算财务组织(OID)
   */
  public void setPk_psfinanceorg(String pk_psfinanceorg) {
    this.setAttributeValue(OrderPriceVO.PK_PSFINANCEORG, pk_psfinanceorg);
  }

  /**
   * 设置物料信息
   * 
   * @param pk_srcmaterial 物料信息
   */
  public void setPk_srcmaterial(String pk_srcmaterial) {
    this.setAttributeValue(OrderPriceVO.PK_SRCMATERIAL, pk_srcmaterial);
  }

  /**
   * 设置供应商
   * 
   * @param pk_supplier 供应商
   */
  public void setPk_supplier(String pk_supplier) {
    this.setAttributeValue(OrderPriceVO.PK_SUPPLIER, pk_supplier);
  }

  /**
   * 设置时间戳
   * 
   * @param ts 时间戳
   */
  public void setTs(UFDateTime ts) {
    this.setAttributeValue(OrderPriceVO.TS, ts);
  }

}
