insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A001',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_recvstordoc',null,'N',1,'N','Y',null,0,'pk_recvstordoc','pu.po_order_bb1.pk_recvstordoc',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,'仓库,code=N',null,null,'N',1,24,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,24)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A002',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef18',null,'N',1,'N','N',null,0,'vbdef18','pu.po_order_bb1.vbdef18',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,77,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,77)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A003',1,-1,null,null,0,1,null,-1,'N',null,-1,'nnum',null,'N',1,'N','N',null,0,'nnum','pu.po_order_bb1.nnum',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,16,'pk_order_bb1','到货计划子子表',1,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,16)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A004',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree2',null,'N',1,'N','N',null,0,'vfree2','pu.po_order_bb1.vfree2',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,51,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,51)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A005',1,-1,null,null,0,0,null,-1,'N',null,-1,'nbackarrvnum',null,'N',1,'N','N',null,0,'nbackarrvnum','pu.po_order_bb1.nbackarrvnum',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,38,'pk_order_bb1','到货计划子子表',1,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,38)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A006',1,-1,null,null,0,1,null,-1,'N',null,-1,'cdevareaid',null,'N',1,'N','Y',null,0,'cdevareaid','pu.po_order_bb1.cdevareaid',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,'地区分类,code=N',null,null,'N',1,27,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,27)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A007',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef8',null,'N',1,'N','N',null,0,'vbdef8','pu.po_order_bb1.vbdef8',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,67,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,67)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A008',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef1',null,'N',1,'N','N',null,0,'vbdef1','pu.po_order_bb1.vbdef1',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,60,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,60)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A009',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef5',null,'N',1,'N','N',null,0,'vbdef5','pu.po_order_bb1.vbdef5',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,64,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,64)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A010',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',null,'N',1,'N','N',null,0,'ts','pu.po_order_bb1.ts',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,80,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,80)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A011',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef9',null,'N',1,'N','N',null,0,'vbdef9','pu.po_order_bb1.vbdef9',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,68,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,68)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A012',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_order_b',null,'N',1,'N','N',null,0,'pk_order_b','pu.po_order_b.pk_order_b',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,4,'pk_order_bb1','pk_order_bb1',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A013',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef3',null,'N',1,'N','N',null,0,'vbdef3','pu.po_order_bb1.vbdef3',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,62,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,62)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A014',1,-1,null,null,0,1,null,-1,'N',null,-1,'btransclosed',null,'N',1,'N','N',null,0,'btransclosed','pu.po_order_bb1.btransclosed',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,47,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,47)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A015',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbillcode',null,'N',1,'N','Y',null,0,'vbillcode','pu.po_order_bb1.vbillcode',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',1,2,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A016',1,-1,null,null,0,1,null,-1,'N',null,-1,'vmemo',null,'N',1,'N','N',null,0,'vmemo','pu.po_order_bb1.vmemo',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,44,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,44)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A017',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org_v',null,'N',1,'N','N',null,0,'pk_org_v','pu.po_order_bb1.pk_org_v','pk_org=pk_purchaseorg','N',0,null,'1001Z8ARRPL0000HA001',null,1,'采购组织版本,code=N',null,null,'N',1,8,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,0,1,'N',1,null,100,8)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A018',1,-1,null,null,0,0,null,-1,'N',null,-1,'vqtunitrate',null,'N',1,'N','N',null,0,'vqtunitrate','pu.po_order_bb1.vqtunitrate',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,22,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,22)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A019',1,-1,null,null,0,1,null,-1,'N',null,-1,'nqtunitnum',null,'N',1,'N','N',null,0,'nqtunitnum','pu.po_order_bb1.nqtunitnum',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,21,'pk_order_bb1','到货计划子子表',1,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,21)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A020',1,-1,null,null,0,1,null,-1,'N',null,-1,'dplanarrvdate',null,'N',1,'N','Y',null,0,'dplanarrvdate','pu.po_order_bb1.dplanarrvdate',null,'N',1,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',1,23,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,23)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A021',1,-1,'订单行关闭',null,0,0,null,-1,'N',null,-1,'fisactive',null,'N',1,'N','Y',null,0,'fisactive','pu.po_order_bb1.fisactive',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,'1400404160003',null,'N',1,42,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,42)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A022',1,-1,null,null,0,1,null,-1,'N',null,-1,'nastnum',null,'N',1,'N','Y',null,0,'nastnum','pu.po_order_bb1.nastnum',null,'N',1,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',1,18,'pk_order_bb1','到货计划子子表',1,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,18)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A023',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree5',null,'N',1,'N','N',null,0,'vfree5','pu.po_order_bb1.vfree5',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,54,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,54)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A024',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef19',null,'N',1,'N','N',null,0,'vbdef19','pu.po_order_bb1.vbdef19',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,78,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,78)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A025',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree9',null,'N',1,'N','N',null,0,'vfree9','pu.po_order_bb1.vfree9',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,58,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,58)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A026',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef7',null,'N',1,'N','N',null,0,'vbdef7','pu.po_order_bb1.vbdef7',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,66,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,66)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A027',1,-1,null,null,0,1,null,-1,'N',null,-1,'cdevaddrid',null,'N',1,'N','Y',null,0,'cdevaddrid','pu.po_order_bb1.cdevaddrid',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,'地点档案,code=N',null,null,'N',1,28,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,28)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A028',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_batchcode',null,'N',1,'N','N',null,0,'pk_batchcode','pu.po_order_bb1.pk_batchcode',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,14,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,14)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A029',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef15',null,'N',1,'N','N',null,0,'vbdef15','pu.po_order_bb1.vbdef15',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,74,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,74)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A030',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef14',null,'N',1,'N','N',null,0,'vbdef14','pu.po_order_bb1.vbdef14',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,73,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,73)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A031',1,-1,null,null,0,0,null,-1,'N',null,-1,'naccumarrvnum',null,'N',1,'N','N',null,0,'naccumarrvnum','pu.po_order_bb1.naccumarrvnum',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,35,'pk_order_bb1','到货计划子子表',1,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,35)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A032',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef20',null,'N',1,'N','N',null,0,'vbdef20','pu.po_order_bb1.vbdef20',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,79,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,79)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A033',1,-1,'物料编码',null,0,0,null,-1,'Y',null,-1,'pk_material',null,'N',1,'Y','Y',null,0,'pk_material','pu.po_order_bb1.pk_material','cunitid=pk_measdoc,castunitid=pk_measdoc,cqtunitid=pk_measdoc,pk_srcmaterial=pk_source','N',1,null,'1001Z8ARRPL0000HA001',null,1,'物料（多版本）','UC000-0002911',null,'N',1,9,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,0,1,'N',1,null,100,9)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A034',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree10',null,'N',1,'N','N',null,0,'vfree10','pu.po_order_bb1.vfree10',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,59,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,59)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A035',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_flowstockorg_v',null,'N',1,'N','N',null,0,'pk_flowstockorg_v','pu.po_order_bb1.pk_flowstockorg_v','pk_flowstockorg=pk_stockorg','N',0,null,'1001Z8ARRPL0000HA001',null,1,'库存组织版本,code=N',null,null,'N',0,34,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,34)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A036',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree1',null,'N',1,'N','N',null,0,'vfree1','pu.po_order_bb1.vfree1',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,50,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,50)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A037',1,-1,null,null,0,0,null,-1,'N',null,-1,'cunitid',null,'N',1,'N','N',null,0,'cunitid','pu.po_order_bb1.cunitid',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,'计量单位,code=N',null,null,'N',0,15,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,15)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A038',1,-1,null,null,0,1,null,-1,'N',null,-1,'nweight',null,'N',1,'N','N',null,0,'nweight','pu.po_order_bb1.nweight',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,45,'pk_order_bb1','到货计划子子表',1,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,45)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A039',1,-1,null,null,0,1,null,-1,'N',null,-1,'cvenddevaddrid',null,'N',1,'N','Y',null,0,'cvenddevaddrid','pu.po_order_bb1.cvenddevaddrid',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,'地点档案,code=N',null,null,'N',1,31,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,31)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A040',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree4',null,'N',1,'N','N',null,0,'vfree4','pu.po_order_bb1.vfree4',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,53,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,53)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A041',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef11',null,'N',1,'N','N',null,0,'vbdef11','pu.po_order_bb1.vbdef11',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,70,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,70)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A042',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree8',null,'N',1,'N','N',null,0,'vfree8','pu.po_order_bb1.vfree8',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,57,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,57)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A043',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef17',null,'N',1,'N','N',null,0,'vbdef17','pu.po_order_bb1.vbdef17',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,76,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,76)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A044',1,-1,null,null,0,0,null,-1,'N',null,-1,'naccumstorenum',null,'N',1,'N','N',null,0,'naccumstorenum','pu.po_order_bb1.naccumstorenum',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,36,'pk_order_bb1','到货计划子子表',1,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,36)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A045',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree6',null,'N',1,'N','N',null,0,'vfree6','pu.po_order_bb1.vfree6',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,55,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,55)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A046',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef16',null,'N',1,'N','N',null,0,'vbdef16','pu.po_order_bb1.vbdef16',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,75,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,75)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A047',1,-1,null,null,0,0,null,-1,'N',null,-1,'naccumdevnum',null,'N',1,'N','N',null,0,'naccumdevnum','pu.po_order_bb1.naccumdevnum',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,40,'pk_order_bb1','到货计划子子表',1,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,40)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A048',1,-1,null,null,0,0,null,-1,'N',null,-1,'castunitid',null,'N',1,'N','Y',null,0,'castunitid','pu.po_order_bb1.castunitid',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,'计量单位,code=N',null,null,'N',1,17,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,17)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A049',1,-1,null,null,0,0,null,-1,'N',null,-1,'nbackstorenum',null,'N',1,'N','N',null,0,'nbackstorenum','pu.po_order_bb1.nbackstorenum',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,39,'pk_order_bb1','到货计划子子表',1,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,39)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A050',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',null,'N',1,'N','N',null,0,'pk_org','pu.po_order_bb1.pk_org',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,'采购组织,code=N',null,null,'N',0,7,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,0,1,'N',0,null,100,7)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A051',1,-1,null,null,0,1,null,-1,'N',null,-1,'npacknum',null,'N',1,'N','N',null,0,'npacknum','pu.po_order_bb1.npacknum',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,49,'pk_order_bb1','到货计划子子表',1,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,49)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A052',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',null,'N',1,'N','N',null,0,'pk_group','pu.po_order_bb1.pk_group',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,'集团,code=N',null,null,'N',0,6,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,0,1,'N',1,null,100,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A053',1,-1,null,null,0,0,null,-1,'N',null,-1,'naccumwastnum',null,'N',1,'N','N',null,0,'naccumwastnum','pu.po_order_bb1.naccumwastnum',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,37,'pk_order_bb1','到货计划子子表',1,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,37)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A054',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef4',null,'N',1,'N','N',null,0,'vbdef4','pu.po_order_bb1.vbdef4',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,63,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,63)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A055',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree3',null,'N',1,'N','N',null,0,'vfree3','pu.po_order_bb1.vfree3',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,52,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,52)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A056',1,5,'订单行号',null,0,1,null,-1,'N',null,20,'crowno',null,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,'01(自定义档案)','UC000-0003563',null,'N',1,5,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A057',1,-1,null,null,0,0,null,-1,'N',null,-1,'cqtunitid',null,'N',1,'N','N',null,0,'cqtunitid','pu.po_order_bb1.cqtunitid',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,'计量单位,code=N',null,null,'N',0,20,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,20)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A058',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_flowstockorg',null,'N',1,'N','N',null,0,'pk_flowstockorg','pu.po_order_bb1.pk_flowstockorg',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,'库存组织,code=N',null,null,'N',0,33,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,33)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A059',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef13',null,'N',1,'N','N',null,0,'vbdef13','pu.po_order_bb1.vbdef13',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,72,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,72)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A060',1,-1,null,null,0,1,null,-1,'N',null,-1,'cvendorid',null,'N',1,'N','N',null,0,'cvendorid','pu.po_order_bb1.cvendorid',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,'生产厂商(自定义档案),code=N',null,null,'N',0,46,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,46)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A061',1,-1,null,null,0,1,null,-1,'N',null,-1,'cvenddevareaid',null,'N',1,'N','Y',null,0,'cvenddevareaid','pu.po_order_bb1.cvenddevareaid',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,'地区分类,code=N',null,null,'N',1,30,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,30)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A062',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_order',null,'N',1,'N','N',null,0,'pk_order','pu.po_order_bb1.pk_order',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,3,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A063',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbatchcode',null,'N',1,'N','Y',null,0,'vbatchcode','pu.po_order_bb1.vbatchcode',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',1,13,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,13)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A064',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef10',null,'N',1,'N','N',null,0,'vbdef10','pu.po_order_bb1.vbdef10',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,69,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,69)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A065',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef6',null,'N',1,'N','N',null,0,'vbdef6','pu.po_order_bb1.vbdef6',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,65,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,65)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A066',1,-1,null,null,0,0,null,-1,'N',null,-1,'vchangerate',null,'N',1,'N','N',null,0,'vchangerate','pu.po_order_bb1.vchangerate',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,19,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,19)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A067',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef2',null,'N',1,'N','N',null,0,'vbdef2','pu.po_order_bb1.vbdef2',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,61,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,61)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A068',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbdef12',null,'N',1,'N','N',null,0,'vbdef12','pu.po_order_bb1.vbdef12',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,71,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,71)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A069',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_order_bb1',null,'N',1,'N','N',null,0,'pk_order_bb1','pu.po_order_bb1.pk_order_bb1',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,1,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A070',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree7',null,'N',1,'N','N',null,0,'vfree7','pu.po_order_bb1.vfree7',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,56,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,56)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A071',1,-1,null,null,0,0,null,-1,'N',null,-1,'blargess',null,'N',1,'N','N',null,0,'blargess','pu.po_order_bb1.blargess',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,43,'pk_order_bb1','到货计划子子表',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,43)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A072',1,-1,null,null,0,1,null,-1,'N',null,-1,'nvolumn',null,'N',1,'N','N',null,0,'nvolumn','pu.po_order_bb1.nvolumn',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,null,null,null,'N',0,48,'pk_order_bb1','到货计划子子表',1,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,48)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A073',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_arrvstoorg',0,'N',1,'N','N',null,0,'pk_arrvstoorg','pu.po_order_bb1.pk_arrvstoorg',null,'N',0,null,'1001Z8ARRPL0000HA001','@@@@',1,'库存组织,code=N',null,null,'N',0,26,'pk_order_bb1','pk_order_bb1',0,'2013-08-01 11:31:50','N',null,null,null,0,1,'N',1,null,100,26)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A074',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_arrvstoorg_v',0,'N',1,'N','Y',null,0,'pk_arrvstoorg_v','pu.po_order_bb1.pk_arrvstoorg_v','pk_arrvstoorg=pk_stockorg','N',1,null,'1001Z8ARRPL0000HA001','@@@@',1,'库存组织版本,code=N',null,null,'N',1,25,'pk_order_bb1','pk_order_bb1',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,25)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A075',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_srcmaterial',null,'N',1,'N','N',null,0,'pk_srcmaterial','pu.po_order_bb1.pk_srcmaterial',null,'N',0,null,'1001Z8ARRPL0000HA001',null,1,'物料,code=N',null,null,'N',0,82,'pk_order_bb1','pk_order_bb1',0,'2013-08-01 11:31:50','N',null,null,null,0,1,'N',1,null,100,82)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A076',1,-1,null,null,0,0,null,-1,'N',null,-1,'naccumreceivenum',0,'N',1,'N','Y',null,0,'naccumreceivenum','pu.po_order_bb1.naccumreceivenum',null,'N',0,null,'1001Z8ARRPL0000HA001','@@@@',1,null,null,null,'N',1,41,'pk_order_bb1','pk_order_bb1',1,'2013-08-01 11:31:50','N',null,null,null,0,1,'N',1,null,100,41)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A077',1,-1,null,null,0,1,null,-1,'N',null,-1,'vehicletype',0,'N',1,'N','N',null,0,'vehicletype','pu.po_order_bb1.vehicletype',null,'N',0,null,'1001Z8ARRPL0000HA001','@@@@',1,null,null,null,'N',0,85,'pk_order_bb1','pk_order_bb1',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,85)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A078',1,-1,null,null,0,1,null,-1,'N',null,-1,'vlinktype',0,'N',1,'N','N',null,0,'vlinktype','pu.po_order_bb1.vlinktype',null,'N',0,null,'1001Z8ARRPL0000HA001','@@@@',1,null,null,null,'N',0,88,'pk_order_bb1','pk_order_bb1',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,88)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A079',1,-1,null,null,0,1,null,-1,'N',null,-1,'dsenddate',0,'N',1,'N','N',null,0,'dsenddate','pu.po_order_bb1.dsenddate',null,'N',0,null,'1001Z8ARRPL0000HA001','@@@@',1,null,null,null,'N',0,84,'pk_order_bb1','pk_order_bb1',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,84)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A080',1,-1,null,null,0,1,null,-1,'N',null,-1,'vecbillcode',0,'N',1,'N','N',null,0,'vecbillcode','pu.po_order_bb1.vecbillcode',null,'N',0,null,'1001Z8ARRPL0000HA001','@@@@',1,null,null,null,'N',0,83,'pk_order_bb1','pk_order_bb1',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,83)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A081',1,-1,null,null,0,1,null,-1,'N',null,-1,'vehiclelicense',0,'N',1,'N','N',null,0,'vehiclelicense','pu.po_order_bb1.vehiclelicense',null,'N',0,null,'1001Z8ARRPL0000HA001','@@@@',1,null,null,null,'N',0,86,'pk_order_bb1','pk_order_bb1',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,86)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A082',1,-1,null,null,0,1,null,-1,'N',null,-1,'vlinkpsn',0,'N',1,'N','N',null,0,'vlinkpsn','pu.po_order_bb1.vlinkpsn',null,'N',0,null,'1001Z8ARRPL0000HA001','@@@@',1,null,null,null,'N',0,87,'pk_order_bb1','pk_order_bb1',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,87)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A083',1,-1,null,null,0,1,null,-1,'N',null,-1,'crownobb1',0,'N',1,'N','N',null,0,'crownobb1','pu.po_order_bb1.crownobb1',null,'N',0,null,'1001Z8ARRPL0000HA001','@@@@',1,null,null,null,'N',0,81,'pk_order_bb1','pk_order_bb1',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,81)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A084',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_receiveaddress',0,'N',1,'N','Y','formataddress(pk_receiveaddress)',0,'pk_receiveaddress','pu.po_order_bb1.pk_receiveaddress',null,'N',0,null,'1001Z8ARRPL0000HA001','@@@@',1,'地址簿,code=N',null,null,'N',1,29,'pk_order_bb1','pk_order_bb1',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,29)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A085',1,-1,null,null,0,1,null,-1,'N',null,-1,'vvenddevaddr',0,'N',1,'N','Y','formataddress(vvenddevaddr)',0,'vvenddevaddr','pu.po_order_bb1.vvenddevaddr',null,'N',0,null,'1001Z8ARRPL0000HA001','@@@@',1,'供应商发货地址,code=N',null,null,'N',1,32,'pk_order_bb1','pk_order_bb1',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,32)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A086',1,-1,null,null,0,0,null,-1,'N','pk_material',-1,'pk_material.materialtype',0,'N',1,'N','Y',null,0,'materialtype','uap.material.materialtype',null,'N',0,null,'1001Z8ARRPL0000HA001','@@@@',1,null,null,null,'N',1,11,'pk_order_bb1','pk_order_bb1',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,11)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A087',1,-1,null,null,0,0,null,-1,'N','pk_material',-1,'pk_material.name',0,'N',1,'N','Y',null,0,'name','uap.material.name',null,'N',0,null,'1001Z8ARRPL0000HA001','@@@@',1,null,null,null,'N',1,10,'pk_order_bb1','pk_order_bb1',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,10)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8ARRPL00000A088',1,-1,null,null,0,0,null,-1,'N','pk_material',-1,'pk_material.materialspec',0,'N',1,'N','Y',null,0,'materialspec','uap.material.materialspec',null,'N',0,null,'1001Z8ARRPL0000HA001','@@@@',1,null,null,null,'N',1,12,'pk_order_bb1','pk_order_bb1',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,12)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z81000000000OB0H',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_schedule_b',0,'N',1,'N','N',null,0,'pk_schedule_b','pu.po_order_b.pk_schedule_b',null,'N',0,null,'1001Z8ARRPL0000HA001','@@@@',1,null,null,null,'N',0,91,'pk_order_bb1','pk_order_bb1',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,91)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z81000000000OB0I',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_schedule',0,'N',1,'N','N',null,0,'pk_schedule','pu.po_order_b.pk_schedule',null,'N',0,null,'1001Z8ARRPL0000HA001','@@@@',1,null,null,null,'N',0,90,'pk_order_bb1','pk_order_bb1',0,'2013-08-01 11:31:50','N',null,null,null,1,1,'N',1,null,100,90)
go

