insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH3V',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org_v',0,'N',1,'N','Y',null,0,'pk_org_v','pu.po_storereq.pk_org_v','pk_org=pk_stockorg','N',1,null,'1002Z81000000001BH3U','@@@@',0,'库存组织版本',null,null,'N',0,1,'header','表头',0,'2012-06-27 11:32:33','N',null,null,null,0,1,'N',1,null,1,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH3X',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbillcode',0,'N',1,'Y','Y',null,0,'vbillcode','pu.po_storereq.vbillcode',null,'N',0,null,'1002Z81000000001BH3U','@@@@',0,null,null,null,'N',1,3,'header','表头',0,'2012-06-27 11:32:33','N',null,null,null,1,1,'N',1,null,1,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH3Y',1,-1,null,'@SYSDATE',0,1,null,-1,'N',null,-1,'dbilldate',0,'N',1,'N','Y',null,0,'dbilldate','pu.po_storereq.dbilldate',null,'N',1,null,'1002Z81000000001BH3U','@@@@',0,null,null,null,'N',1,4,'header','表头',0,'2012-06-27 11:32:33','N',null,null,null,1,1,'N',1,null,1,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH3Z',1,-1,null,null,0,1,'rowcount->getrowcount("bd_psnjob","pk_psndoc",pk_apppsnh ,"pk_org",pk_org);pk_appdepth->iif(rowcount==1,getcolvalue2(bd_psnjob,pk_dept,pk_psndoc,pk_apppsnh,pk_org,pk_org),pk_appdepth);pk_appdepth_v->iif(rowcount==1,getcolvalue(org_dept,pk_vid,pk_dept,pk_appdepth),pk_appdepth_v);',-1,'N',null,-1,'pk_apppsnh',0,'N',1,'N','Y',null,0,'pk_apppsnh','pu.po_storereq.pk_apppsnh',null,'N',0,null,'1002Z81000000001BH3U','@@@@',0,'人员',null,null,'N',1,5,'header','header',0,'2012-06-27 11:32:33','N',null,null,null,1,1,'N',1,null,1,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH40',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_appdepth_v',0,'N',1,'N','Y',null,0,'pk_appdepth_v','pu.po_storereq.pk_appdepth_v','pk_appdepth=pk_dept','N',0,null,'1002Z81000000001BH3U','@@@@',0,'部门版本',null,null,'N',1,6,'header','header',0,'2012-06-27 11:32:33','N',null,null,null,1,1,'N',1,null,1,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH41',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_appdepth',0,'N',1,'N','N',null,0,'pk_appdepth','pu.po_storereq.pk_appdepth',null,'N',0,null,'1002Z81000000001BH3U','@@@@',0,'部门',null,null,'N',0,7,'header','header',0,'2012-06-27 11:32:33','N',null,null,null,1,1,'N',1,null,1,7)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH44',1,-1,null,'false',0,1,null,-1,'N',null,-1,'burgency',0,'N',1,'N','Y',null,0,'burgency','pu.po_storereq.burgency',null,'N',0,null,'1002Z81000000001BH3U','@@@@',0,null,null,null,'N',1,10,'header','表头',0,'2012-06-27 11:32:33','N',null,null,null,1,1,'N',1,null,1,10)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH45',1,-1,null,null,0,1,null,-1,'N',null,-1,'vmemo',0,'N',1,'N','Y',null,0,'vmemo','pu.po_storereq.vmemo',null,'N',0,null,'1002Z81000000001BH3U','@@@@',0,null,null,null,'N',1,11,'header','表头',0,'2012-06-27 11:32:33','N',null,null,null,1,1,'N',1,null,1,11)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH46',1,-1,null,'0',0,0,null,-1,'N',null,-1,'fbillstatus',0,'N',1,'N','Y',null,0,'fbillstatus','pu.po_storereq.fbillstatus',null,'N',1,null,'1002Z81000000001BH3U','@@@@',0,null,null,null,'N',1,12,'header','header',0,'2012-06-27 11:32:33','N',null,null,null,0,1,'N',1,null,1,12)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH4W',1,-1,null,null,0,1,null,-1,'N',null,-1,'crowno',0,'N',1,'N','Y',null,0,'crowno','pu.po_storereq_b.crowno',null,'N',1,null,'1002Z81000000001BH3U','@@@@',1,null,null,null,'N',1,1,'body','表体',0,'2012-06-27 11:32:33','N',null,null,null,1,1,'N',1,null,100,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH4X',1,-1,'物料编码',null,0,1,null,-1,'Y',null,-1,'pk_material',0,'N',1,'Y','Y',null,0,'pk_material','pu.po_storereq_b.pk_material','cunitid=pk_measdoc,castunitid=pk_measdoc,pk_srcmaterial=pk_source','N',1,null,'1002Z81000000001BH3U','@@@@',1,'物料（多版本）,code=N','UC000-0002911',null,'N',1,2,'body','表体',0,'2012-06-27 11:32:33','N',null,null,null,1,1,'N',1,null,100,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH4Y',1,-1,null,null,0,0,null,-1,'N','pk_material',-1,'pk_material.name',0,'N',1,'N','Y',null,0,'name','uap.material.name',null,'N',0,null,'1002Z81000000001BH3U','@@@@',1,null,null,null,'N',1,3,'body','body',0,'2012-06-27 11:32:33','N',null,null,null,1,1,'N',1,null,100,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH4Z',1,-1,null,null,0,0,null,-1,'N','pk_material',-1,'pk_material.materialtype',0,'N',1,'N','Y',null,0,'materialtype','uap.material.materialtype',null,'N',0,null,'1002Z81000000001BH3U','@@@@',1,null,null,null,'N',1,4,'body','body',0,'2012-06-27 11:32:33','N',null,null,null,1,1,'N',1,null,100,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH50',1,-1,null,null,0,0,null,-1,'N','pk_material',-1,'pk_material.materialspec',0,'N',1,'N','Y',null,0,'materialspec','uap.material.materialspec',null,'N',0,null,'1002Z81000000001BH3U','@@@@',1,null,null,null,'N',1,5,'body','body',0,'2012-06-27 11:32:33','N',null,null,null,1,1,'N',1,null,100,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH51',1,-1,null,null,0,0,null,-1,'N',null,-1,'cunitid',0,'N',1,'N','N',null,0,'cunitid','pu.po_storereq_b.cunitid',null,'N',0,null,'1002Z81000000001BH3U','@@@@',1,'计量单位,code=N',null,null,'N',0,6,'body','表体',0,'2012-06-27 11:32:33','N',null,null,null,0,1,'N',1,null,100,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH55',1,-1,null,null,0,1,null,-1,'N',null,-1,'castunitid',0,'N',1,'N','Y',null,0,'castunitid','pu.po_storereq_b.castunitid',null,'N',0,null,'1002Z81000000001BH3U','@@@@',1,'计量单位,code=N',null,null,'N',1,10,'body','表体',0,'2012-06-27 11:32:33','N',null,null,null,1,1,'N',1,null,100,10)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH57',1,-1,null,null,0,1,null,-1,'N',null,-1,'nastnum',0,'N',1,'N','Y',null,0,'nastnum','pu.po_storereq_b.nastnum',null,'N',1,null,'1002Z81000000001BH3U','@@@@',1,null,null,null,'N',1,12,'body','表体',1,'2012-06-27 11:32:33','N',null,null,null,1,1,'N',1,null,100,12)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH58',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_reqstordoc',0,'N',1,'N','N',null,0,'pk_reqstordoc','pu.po_storereq_b.pk_reqstordoc',null,'N',0,null,'1002Z81000000001BH3U','@@@@',1,'仓库,code=N',null,null,'N',0,13,'body','表体',0,'2012-06-27 11:32:33','N',null,null,null,1,1,'N',1,null,100,13)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH59',1,-1,null,null,0,1,null,-1,'N',null,-1,'dreqdate',0,'N',1,'N','Y',null,0,'dreqdate','pu.po_storereq_b.dreqdate',null,'N',0,null,'1002Z81000000001BH3U','@@@@',1,null,null,null,'N',1,14,'body','表体',0,'2012-06-27 11:32:33','N',null,null,null,1,1,'N',1,null,100,14)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH5A',1,-1,null,null,0,1,'rowcount->getrowcount("bd_psnjob","pk_psndoc",pk_apppsn_ID,"pk_org",pk_org_ID);pk_appdept_ID->iif(rowcount==1,getcolvalue2(bd_psnjob,pk_dept,pk_psndoc,pk_apppsn_ID,pk_org,pk_org_ID),pk_appdept_ID);pk_appdept->iif(rowcount==1,getcolvalue2(org_dept,name,pk_dept,pk_appdept_ID,pk_org,pk_org_ID),pk_appdept);pk_appdept_v_ID->iif(rowcount==1,getcolvalue(org_dept,pk_vid,pk_dept,pk_appdept_ID),pk_appdept_v_ID);pk_appdept_v->iif(rowcount==1,getcolvalue(org_dept_v,name,pk_vid,pk_appdept_v_ID),pk_appdept_v);',-1,'N',null,-1,'pk_apppsn',0,'N',1,'N','N',null,0,'pk_apppsn','pu.po_storereq_b.pk_apppsn',null,'N',0,null,'1002Z81000000001BH3U','@@@@',1,'人员,code=N',null,null,'N',0,15,'body','body',0,'2012-06-27 11:32:33','N',null,null,null,1,1,'N',1,null,100,15)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH5B',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_appdept_v',0,'N',1,'N','N',null,0,'pk_appdept_v','pu.po_storereq_b.pk_appdept_v','pk_appdept=pk_dept','N',0,null,'1002Z81000000001BH3U','@@@@',1,'部门版本,code=N',null,null,'N',0,16,'body','body',0,'2012-06-27 11:32:33','N',null,null,null,1,1,'N',1,null,100,16)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH5C',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_appdept',0,'N',1,'N','N',null,0,'pk_appdept','pu.po_storereq_b.pk_appdept',null,'N',0,null,'1002Z81000000001BH3U','@@@@',1,'部门,code=N',null,null,'N',0,17,'body','body',0,'2012-06-27 11:32:33','N',null,null,null,1,1,'N',1,null,100,17)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH5E',1,-1,null,null,0,1,null,-1,'N',null,-1,'cprojectid',0,'N',1,'N','N',null,0,'cprojectid','pu.po_storereq_b.cprojectid',null,'N',0,null,'1002Z81000000001BH3U','@@@@',1,'项目,code=N',null,null,'N',0,19,'body','表体',0,'2012-06-27 11:32:33','N',null,null,null,1,1,'N',1,null,100,19)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH5F',1,-1,null,null,0,1,null,-1,'N',null,-1,'cprojecttaskid',0,'N',1,'N','N',null,0,'cprojecttaskid','pu.po_storereq_b.cprojecttaskid',null,'N',0,null,'1002Z81000000001BH3U','@@@@',1,'项目工作分解结构(WBS),code=N',null,null,'N',0,20,'body','body',0,'2012-06-27 11:32:33','N',null,null,null,1,1,'N',1,null,100,20)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH5G',1,-1,null,null,0,1,null,-1,'N',null,-1,'cdevareaid',0,'N',1,'N','N',null,0,'cdevareaid','pu.po_storereq_b.cdevareaid',null,'N',0,null,'1002Z81000000001BH3U','@@@@',1,'地区分类,code=N',null,null,'N',0,21,'body','表体',0,'2012-06-27 11:32:33','N',null,null,null,1,1,'N',1,null,100,21)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH5H',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_receiveaddress',0,'N',1,'N','N','formataddress(pk_receiveaddress_ID)',0,'pk_receiveaddress','pu.po_storereq_b.pk_receiveaddress',null,'N',0,null,'1002Z81000000001BH3U','@@@@',1,'地址簿,code=N',null,null,'N',0,22,'body','表体',0,'2012-06-27 11:32:33','N',null,null,null,1,1,'N',1,null,100,22)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH5I',1,-1,null,null,0,1,null,-1,'N',null,-1,'cdevaddrid',0,'N',1,'N','N',null,0,'cdevaddrid','pu.po_storereq_b.cdevaddrid',null,'N',0,null,'1002Z81000000001BH3U','@@@@',1,'地点档案,code=N',null,null,'N',0,23,'body','表体',0,'2012-06-27 11:32:33','N',null,null,null,1,1,'N',1,null,100,23)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH5J',1,-1,null,null,0,1,null,-1,'N',null,-1,'cvendorid',0,'N',1,'N','N',null,0,'cvendorid','pu.po_storereq_b.cvendorid',null,'N',0,null,'1002Z81000000001BH3U','@@@@',1,'供应商档案,code=N',null,null,'N',0,24,'body','表体',0,'2012-06-27 11:32:33','N',null,null,null,1,1,'N',1,null,100,24)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH5K',1,-1,null,null,0,1,null,-1,'N',null,-1,'cproductorid',0,'N',1,'N','N',null,0,'cproductorid','pu.po_storereq_b.cproductorid',null,'N',0,null,'1002Z81000000001BH3U','@@@@',1,'生产厂商(自定义档案),code=N',null,null,'N',0,25,'body','body',0,'2012-06-27 11:32:33','N',null,null,null,1,1,'N',1,null,100,25)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH75',1,-1,null,null,0,0,null,-1,'N',null,-1,'ccurrencyid',0,'N',1,'N','N',null,0,'ccurrencyid','pu.po_storereq_b.ccurrencyid',null,'N',0,null,'1002Z81000000001BH3U','@@@@',1,'币种档案,code=N',null,null,'N',0,82,'body','body',0,'2012-06-27 11:32:33','N',null,null,null,0,1,'N',1,null,100,82)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH77',1,-1,null,'@SYSOPER',0,0,null,-1,'N',null,-1,'billmaker',0,'N',1,'N','Y',null,0,'billmaker','pu.po_storereq.billmaker',null,'N',0,null,'1002Z81000000001BH3U','@@@@',2,'用户',null,null,'N',1,1,'tailinfo','tailinfo',0,'2012-06-27 11:32:33','N',null,null,null,0,1,'N',1,null,1,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH78',1,-1,null,'@SYSOPER',0,0,null,-1,'N',null,-1,'creator',0,'N',1,'N','Y',null,0,'creator','pu.po_storereq.creator',null,'N',0,null,'1002Z81000000001BH3U','@@@@',2,'用户',null,null,'N',1,1,'tail',null,0,'2012-06-27 11:32:33','N',null,null,null,0,0,'N',1,null,1,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH79',1,-1,null,null,0,0,null,-1,'N',null,-1,'dmakedate',0,'N',1,'N','Y',null,0,'dmakedate','pu.po_storereq.dmakedate',null,'N',0,null,'1002Z81000000001BH3U','@@@@',2,null,null,null,'N',1,2,'tailinfo','tailinfo',0,'2012-06-27 11:32:33','N',null,null,null,0,1,'N',1,null,1,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH7A',1,-1,'创建时间',null,0,0,null,-1,'N',null,-1,'creationtime',0,'N',1,'N','Y',null,0,'creationtime','pu.po_storereq.creationtime',null,'N',0,null,'1002Z81000000001BH3U','@@@@',2,null,'UC001-0000092',null,'N',1,2,'tail','tail',0,'2012-06-27 11:32:33','N',null,null,null,0,1,'N',1,null,1,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH7B',1,-1,null,null,0,0,null,-1,'N',null,-1,'approver',0,'N',1,'N','Y',null,0,'approver','pu.po_storereq.approver',null,'N',0,null,'1002Z81000000001BH3U','@@@@',2,'用户',null,null,'N',1,3,'tailinfo','tailinfo',0,'2012-06-27 11:32:33','N',null,null,null,0,1,'N',1,null,1,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH7C',1,-1,null,null,0,0,null,-1,'N',null,-1,'modifier',0,'N',1,'N','Y',null,0,'modifier','pu.po_storereq.modifier',null,'N',0,null,'1002Z81000000001BH3U','@@@@',2,'用户',null,null,'N',1,3,'tail','审计信息',0,'2012-06-27 11:32:33','N',null,null,null,0,0,'N',1,null,1,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH7D',1,-1,null,null,0,0,null,-1,'N',null,-1,'taudittime',0,'N',1,'N','Y',null,0,'taudittime','pu.po_storereq.taudittime',null,'N',0,null,'1002Z81000000001BH3U','@@@@',2,null,null,null,'N',1,4,'tailinfo','tailinfo',0,'2012-06-27 11:32:33','N',null,null,null,0,1,'N',1,null,1,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BH7E',1,-1,null,null,0,0,null,-1,'N',null,-1,'modifiedtime',0,'N',1,'N','Y',null,0,'modifiedtime','pu.po_storereq.modifiedtime',null,'N',0,null,'1002Z81000000001BH3U','@@@@',2,null,null,null,'N',1,4,'tail',null,0,'2012-06-27 11:32:33','N',null,null,null,0,0,'N',1,null,1,4)
go

