/***************************************************************
 * \ The skeleton of this class is generated by an automatic * code generator
 * for NC product. It is based on Velocity. * \
 ***************************************************************/
package nc.vo.pu.m21transtype.enumeration;

import nc.md.model.IEnumValue;
import nc.md.model.impl.MDEnum;
import nc.md.model.type.IType;
import nc.vo.pubapp.enumeration.NCMDEnum;

/**
 * <b> 在途状态 </b> 状态名称： 0 审批 1 输出 2 确认 3 发货 4 装运 5 报关 6 出关 7 到货 8 入库
 * 
 * @author GGR
 * @version v60
 */
public class OnwayStatus extends NCMDEnum {
  // 到货
  public static final OnwayStatus STATUS_ARRIVE = MDEnum.valueOf(
      OnwayStatus.class, Integer.valueOf(7));

  // 审批
  public static final OnwayStatus STATUS_AUDIT = MDEnum.valueOf(
      OnwayStatus.class, Integer.valueOf(0));

  // 报关
  public static final OnwayStatus STATUS_COMEIN = MDEnum.valueOf(
      OnwayStatus.class, Integer.valueOf(5));

  // 确认
  public static final OnwayStatus STATUS_CONFIRM = MDEnum.valueOf(
      OnwayStatus.class, Integer.valueOf(2));

  // 出关
  public static final OnwayStatus STATUS_GETOUT = MDEnum.valueOf(
      OnwayStatus.class, Integer.valueOf(6));

  // 输出
  public static final OnwayStatus STATUS_OUTPUT = MDEnum.valueOf(
      OnwayStatus.class, Integer.valueOf(1));

  // 发货
  public static final OnwayStatus STATUS_SENDOUT = MDEnum.valueOf(
      OnwayStatus.class, Integer.valueOf(3));

  // 装运
  public static final OnwayStatus STATUS_SHIP = MDEnum.valueOf(
      OnwayStatus.class, Integer.valueOf(4));

  // 入库
  public static final OnwayStatus STATUS_STORE = MDEnum.valueOf(
      OnwayStatus.class, Integer.valueOf(8));

  public OnwayStatus(IEnumValue enumvalue) {
    super(enumvalue);
  }

  @Override
  public int getReturnType() {
    return IType.TYPE_INT;
  }
}
