
package nc.ui.pu.qst.newoaspwh.websrv;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-23T09:48:10.705+08:00
 * Generated source version: 3.1.8
 * 
 */
public final class GMCGFAOA_Domino_Client {

    private static final QName SERVICE_NAME = new QName("urn:DefaultNamespace", "GMCGFA_OA");

    private GMCGFAOA_Domino_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GMCGFAOA_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        GMCGFAOA_Service ss = new GMCGFAOA_Service(wsdlURL, SERVICE_NAME);
        GMCGFAOA port = ss.getDomino();  
        
        {
        System.out.println("Invoking process...");
        nc.ui.pu.qst.newoaspwh.websrv.ALLDATAINFO _process_inputdata = null;
        java.lang.String _process__return = port.process(_process_inputdata);
        System.out.println("process.result=" + _process__return);


        }

        System.exit(0);
    }

}
