package nc.ui.pu.qst.newoaspwh.websrv;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-23T09:48:10.882+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebServiceClient(name = "GMCGFA_OA", 
                  wsdlLocation = "http://oa.ansteel.com.cn/ansteel/webServiceCG.nsf/GMCGFA_OA?wsdl",
                  targetNamespace = "urn:DefaultNamespace") 
public class GMCGFAOA_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:DefaultNamespace", "GMCGFA_OA");
    public final static QName Domino = new QName("urn:DefaultNamespace", "Domino");
    static {
        URL url = null;
        try {
            url = new URL("http://oa.ansteel.com.cn/ansteel/webServiceCG.nsf/GMCGFA_OA?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GMCGFAOA_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://oa.ansteel.com.cn/ansteel/webServiceCG.nsf/GMCGFA_OA?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GMCGFAOA_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GMCGFAOA_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GMCGFAOA_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    




    /**
     *
     * @return
     *     returns GMCGFAOA
     */
    @WebEndpoint(name = "Domino")
    public GMCGFAOA getDomino() {
        return super.getPort(Domino, GMCGFAOA.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GMCGFAOA
     */
    @WebEndpoint(name = "Domino")
    public GMCGFAOA getDomino(WebServiceFeature... features) {
        return super.getPort(Domino, GMCGFAOA.class, features);
    }

}
