package nc.ui.pu.qst.newoaspwh.websrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-23T09:48:10.875+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "urn:DefaultNamespace", name = "GMCGFAOA")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GMCGFAOA {

    @WebMethod(operationName = "PROCESS", action = "PROCESS")
    @WebResult(name = "PROCESSReturn", targetNamespace = "urn:DefaultNamespace", partName = "PROCESSReturn")
    public java.lang.String process(
        @WebParam(partName = "INPUTDATA", name = "INPUTDATA", targetNamespace = "urn:DefaultNamespace")
        ALLDATAINFO inputdata
    );
}
