insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQDA',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org_v',0,'N',1,'N','Y',null,0,'pk_org_v','pu.po_praybill.pk_org_v',null,'N',0,null,'1002Z81000000001BQD6','@@@@',0,'库存组织版本',null,null,'N',0,4,'po_praybill','请购单主表',0,'2012-06-28 09:20:10','N',null,null,null,0,1,'N',1,null,1,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQDC',1,-1,null,null,0,1,null,-1,'N',null,40,'vbillcode',0,'N',1,'Y','Y',null,0,'vbillcode','pu.po_praybill.vbillcode',null,'N',0,null,'1002Z81000000001BQD6','@@@@',0,null,null,null,'N',1,6,'po_praybill','请购单主表',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'N',1,null,1,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQDD',1,-1,null,'@SYSDATE',0,1,null,-1,'N',null,-1,'dbilldate',0,'N',1,'N','Y',null,0,'dbilldate','pu.po_praybill.dbilldate',null,'N',1,null,'1002Z81000000001BQD6','@@@@',0,null,null,null,'N',1,7,'po_praybill','请购单主表',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'Y',1,null,1,7)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQDE',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bsctype',0,'N',1,'N','Y',null,0,'bsctype','pu.po_praybill.bsctype',null,'N',0,null,'1002Z81000000001BQD6','@@@@',0,null,null,null,'N',1,8,'po_praybill','请购单主表',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'N',1,null,1,8)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQDF',1,-1,null,'5',0,0,null,-1,'N',null,-1,'fpraysource',0,'N',1,'N','Y',null,0,'fpraysource','pu.po_praybill.fpraysource',null,'N',1,null,'1002Z81000000001BQD6','@@@@',0,null,null,null,'N',1,9,'po_praybill','请购单主表',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'Y',1,null,1,9)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQDG',1,-1,null,null,0,1,null,-1,'N',null,-1,'ctrantypeid',0,'N',1,'N','Y',null,0,'ctrantypeid','pu.po_praybill.ctrantypeid','vtrantypecode=pk_billtypecode','N',1,null,'1002Z81000000001BQD6','@@@@',0,'影响因素交 易类型',null,null,'N',1,10,'po_praybill','请购单主表',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'Y',1,null,1,10)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQDH',1,-1,null,null,0,1,null,-1,'N',null,-1,'vtrantypecode',0,'N',1,'N','N',null,0,'vtrantypecode','pu.po_praybill.vtrantypecode',null,'N',1,null,'1002Z81000000001BQD6','@@@@',0,'影响因素单据类型',null,null,'N',0,10,'po_praybill','请购单主表',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'Y',1,null,1,10)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQDI',1,-1,null,null,0,1,'rowcount->getrowcount("bd_psnjob","pk_psndoc" ,pk_planpsn ,"pk_org",pk_org);pk_plandept->iif(rowcount==1,getcolvalue2(bd_psnjob ,pk_dept ,pk_psndoc , pk_planpsn,pk_org,pk_org),pk_plandept);pk_plandept_v->iif(rowcount==1,getcolvalue(org_dept ,pk_vid , pk_dept  , pk_plandept),pk_plandept_v)',-1,'N',null,-1,'pk_planpsn',0,'N',1,'N','Y',null,0,'pk_planpsn','pu.po_praybill.pk_planpsn',null,'N',0,null,'1002Z81000000001BQD6','@@@@',0,'人员',null,null,'N',1,11,'po_praybill','请购单主表',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'N',1,null,1,11)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQDK',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_plandept_v',0,'N',1,'N','Y',null,0,'pk_plandept_v','pu.po_praybill.pk_plandept_v','pk_plandept=pk_dept','N',0,null,'1002Z81000000001BQD6','@@@@',0,'部门版本',null,null,'N',1,13,'po_praybill','请购单主表',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'N',1,null,1,13)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQDL',1,-1,null,'false',0,0,null,-1,'N',null,-1,'bdirecttransit',0,'N',1,'N','Y',null,0,'bdirecttransit','pu.po_praybill.bdirecttransit',null,'N',1,null,'1002Z81000000001BQD6','@@@@',0,null,null,null,'N',1,14,'po_praybill','请购单主表',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'N',1,null,1,14)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQDM',1,-1,null,null,0,0,null,-1,'N',null,-1,'fbillstatus',0,'N',1,'N','Y',null,0,'fbillstatus','pu.po_praybill.fbillstatus',null,'N',0,null,'1002Z81000000001BQD6','@@@@',0,null,null,null,'N',1,15,'po_praybill','请购单主表',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'N',1,null,1,15)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQDR',1,-1,null,null,0,0,null,-1,'N',null,-1,'nversion',0,'N',1,'N','Y',null,0,'nversion','pu.po_praybill.nversion',null,'N',0,null,'1002Z81000000001BQD6','@@@@',0,null,null,null,'N',1,20,'po_praybill','请购单主表',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'N',1,null,1,20)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQEC',1,-1,null,null,0,1,null,-1,'N',null,-1,'vmemo',0,'N',1,'N','Y',null,0,'vmemo','pu.po_praybill.vmemo',null,'N',0,null,'1002Z81000000001BQD6','@@@@',0,null,null,null,'N',1,41,'po_praybill','请购单主表',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'N',1,null,1,41)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQEF',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','N',null,0,'pk_org','pu.po_praybill_b.pk_org',null,'N',0,null,'1002Z81000000001BQD6','@@@@',1,'库存组织,code=N',null,null,'N',0,2,'pk_praybill_b','请购单行ID',0,'2012-06-28 09:20:10','N',null,null,null,0,1,'N',1,null,100,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQEG',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org_v',0,'N',1,'N','N',null,0,'pk_org_v','pu.po_praybill_b.pk_org_v',null,'N',0,null,'1002Z81000000001BQD6','@@@@',1,'库存组织版本,code=N',null,null,'N',0,3,'pk_praybill_b','请购单行ID',0,'2012-06-28 09:20:10','N',null,null,null,0,1,'N',1,null,100,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQEH',1,-1,null,null,0,1,null,-1,'N',null,-1,'crowno',0,'N',1,'N','Y',null,0,'crowno','pu.po_praybill_b.crowno',null,'N',0,null,'1002Z81000000001BQD6','@@@@',1,null,null,null,'N',1,4,'pk_praybill_b','请购单行ID',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'N',1,null,100,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQEJ',1,-1,'物料编码',null,0,1,null,-1,'Y',null,-1,'pk_material',0,'N',1,'Y','Y',null,0,'pk_material','pu.po_praybill_b.pk_material','castunitid=pk_measdoc,cunitid=pk_measdoc,pk_srcmaterial=pk_source','N',1,null,'1002Z81000000001BQD6','@@@@',1,'物料（多版本）,code=N','UC000-0002911',null,'N',1,6,'pk_praybill_b','pk_praybill_b',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'N',1,null,100,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQEL',1,-1,null,null,0,0,null,-1,'N','pk_material',-1,'pk_material.name',0,'N',1,'N','Y',null,0,'name','uap.material.name',null,'N',0,null,'1002Z81000000001BQD6','@@@@',1,null,null,null,'N',1,8,'pk_praybill_b','pk_praybill_b',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'N',1,null,100,8)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQEM',1,-1,null,null,0,0,null,-1,'N','pk_material',-1,'pk_material.materialtype',0,'N',1,'N','Y',null,0,'materialtype','uap.material.materialtype',null,'N',0,null,'1002Z81000000001BQD6','@@@@',1,null,null,null,'N',1,9,'pk_praybill_b','pk_praybill_b',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'N',1,null,100,9)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQEN',1,-1,null,null,0,0,null,-1,'N','pk_material',-1,'pk_material.materialspec',0,'N',1,'N','Y',null,0,'materialspec','uap.material.materialspec',null,'N',0,null,'1002Z81000000001BQD6','@@@@',1,null,null,null,'N',1,10,'pk_praybill_b','pk_praybill_b',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'N',1,null,100,10)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQEO',1,-1,null,null,0,1,null,-1,'N',null,-1,'cprojectid',0,'N',1,'N','N',null,0,'cprojectid','pu.po_praybill_b.cprojectid',null,'N',0,null,'1002Z81000000001BQD6','@@@@',1,'项目,code=N',null,null,'N',0,11,'pk_praybill_b','请购单行ID',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'N',1,null,100,11)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQEP',1,-1,null,null,0,1,null,-1,'N',null,-1,'cprojecttaskid',0,'N',1,'N','N',null,0,'cprojecttaskid','pu.po_praybill_b.cprojecttaskid',null,'N',0,null,'1002Z81000000001BQD6','@@@@',1,'项目工作分解结构(WBS),code=N',null,null,'N',0,12,'pk_praybill_b','pk_praybill_b',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'N',1,null,100,12)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQEQ',1,-1,null,null,0,1,null,-1,'N',null,-1,'cproductorid',0,'N',1,'N','N',null,0,'cproductorid','pu.po_praybill_b.cproductorid',null,'N',0,null,'1002Z81000000001BQD6','@@@@',1,'生产厂商(自定义档案),code=N',null,null,'N',0,13,'pk_praybill_b','请购单行ID',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'N',1,null,100,13)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQF3',1,-1,null,null,0,1,null,-1,'N',null,-1,'castunitid',0,'N',1,'N','Y',null,0,'castunitid','pu.po_praybill_b.castunitid',null,'N',0,null,'1002Z81000000001BQD6','@@@@',1,'计量单位,code=N',null,null,'N',1,26,'pk_praybill_b','pk_praybill_b',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'N',1,null,100,26)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQF4',1,-1,null,null,0,1,'nnum->nastnum',-1,'N',null,28,'nastnum',0,'N',1,'N','Y',null,0,'nastnum','pu.po_praybill_b.nastnum',null,'N',1,null,'1002Z81000000001BQD6','@@@@',1,null,null,null,'N',1,27,'pk_praybill_b','请购单行ID',1,'2012-06-28 09:20:10','N',null,null,null,1,1,'N',1,null,100,27)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQF6',1,-1,null,null,0,0,null,-1,'N',null,-1,'cunitid',0,'N',1,'N','N',null,0,'cunitid','pu.po_praybill_b.cunitid',null,'N',0,null,'1002Z81000000001BQD6','@@@@',1,'计量单位,code=N',null,null,'N',0,29,'pk_praybill_b','请购单行ID',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'N',1,null,100,29)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQF8',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_reqdept',0,'N',1,'N','N',null,0,'pk_reqdept','pu.po_praybill_b.pk_reqdept',null,'N',0,null,'1002Z81000000001BQD6','@@@@',1,'部门,code=N',null,null,'N',0,31,'pk_praybill_b','请购单行ID',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'N',1,null,100,31)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQF9',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_reqdept_v',0,'N',1,'N','N',null,0,'pk_reqdept_v','pu.po_praybill_b.pk_reqdept_v','pk_reqdept=pk_dept','N',0,null,'1002Z81000000001BQD6','@@@@',1,'部门版本,code=N',null,null,'N',0,32,'pk_praybill_b','请购单行ID',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'N',1,null,100,32)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQFD',1,-1,null,null,0,1,null,-1,'N',null,-1,'dreqdate',0,'N',1,'N','Y',null,0,'dreqdate','pu.po_praybill_b.dreqdate',null,'N',1,null,'1002Z81000000001BQD6','@@@@',1,null,null,null,'N',1,36,'pk_praybill_b','请购单行ID',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'N',1,null,100,36)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQFE',1,-1,null,null,0,1,null,-1,'N',null,-1,'dsuggestdate',0,'N',1,'N','Y',null,0,'dsuggestdate','pu.po_praybill_b.dsuggestdate',null,'N',0,null,'1002Z81000000001BQD6','@@@@',1,null,null,null,'N',1,37,'pk_praybill_b','请购单行ID',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'N',1,null,100,37)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQFF',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_purchaseorg',0,'N',1,'N','N',null,0,'pk_purchaseorg','pu.po_praybill_b.pk_purchaseorg',null,'N',0,null,'1002Z81000000001BQD6','@@@@',1,'采购组织,code=N',null,null,'N',0,38,'pk_praybill_b','请购单行ID',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'N',1,null,100,38)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQFG',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_purchaseorg_v',0,'N',1,'N','Y',null,0,'pk_purchaseorg_v','pu.po_praybill_b.pk_purchaseorg_v','pk_purchaseorg=pk_purchaseorg','N',1,null,'1002Z81000000001BQD6','@@@@',1,'采购组织版本,code=N',null,null,'N',1,39,'pk_praybill_b','请购单行ID',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'N',1,null,100,39)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQFI',1,-1,null,null,0,1,null,-1,'N',null,-1,'cordertrantypecode',0,'N',1,'N','Y',null,0,'cordertrantypecode','pu.po_praybill_b.cordertrantypecode',null,'N',0,null,'1002Z81000000001BQD6','@@@@',1,'影响因素交 易类型,code=N',null,null,'N',1,41,'pk_praybill_b','请购单行ID',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'N',1,null,100,41)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQFJ',1,-1,null,null,0,1,null,-1,'Y',null,-1,'pk_suggestsupplier',0,'N',1,'Y','Y',null,0,'pk_suggestsupplier','pu.po_praybill_b.pk_suggestsupplier',null,'N',0,null,'1002Z81000000001BQD6','@@@@',1,'供应商档案,code=N',null,null,'N',1,42,'pk_praybill_b','pk_praybill_b',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'N',1,null,100,42)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQFK',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_reqstor',0,'N',1,'N','N',null,0,'pk_reqstor','pu.po_praybill_b.pk_reqstor',null,'N',0,null,'1002Z81000000001BQD6','@@@@',1,'仓库,code=N',null,null,'N',0,43,'pk_praybill_b','请购单行ID',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'N',1,null,100,43)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQFL',1,-1,'需求仓库地址',null,0,0,null,-1,'N','pk_reqstor',-1,'pk_reqstor.storaddr',0,'N',1,'N','N','formataddress(pk_reqstor.storaddr_ID)',0,'storaddr','uap.stordoc.storaddr',null,'N',0,null,'1002Z81000000001BQD6','@@@@',1,'地址簿,code=N','1400402000001',null,'N',0,45,'pk_praybill_b','pk_praybill_b',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'N',1,null,100,45)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQFY',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_employee',0,'N',1,'N','N',null,0,'pk_employee','pu.po_praybill_b.pk_employee',null,'N',0,null,'1002Z81000000001BQD6','@@@@',1,'人员,code=N',null,null,'N',0,58,'pk_praybill_b','请购单行ID',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'N',1,null,100,58)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQGQ',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_product',0,'N',1,'N','N',null,0,'pk_product','pu.po_praybill_b.pk_product','pk_product_v=pk_source','N',0,null,'1002Z81000000001BQD6','@@@@',1,'物料,code=N',null,null,'N',0,86,'pk_praybill_b','请购单行ID',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'N',1,null,100,86)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQGW',1,-1,null,null,0,1,null,-1,'N',null,-1,'casscustid',0,'N',1,'N','N',null,0,'casscustid','pu.po_praybill_b.casscustid',null,'N',0,null,'1002Z81000000001BQD6','@@@@',1,'客户档案,code=N',null,null,'N',0,94,'pk_praybill_b','pk_praybill_b',0,'2012-06-28 09:20:10','N',null,null,null,1,1,'N',1,null,100,94)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQGX',1,-1,null,'@SYSOPER',0,0,null,-1,'N',null,-1,'billmaker',0,'N',1,'N','Y',null,0,'billmaker','pu.po_praybill.billmaker',null,'N',0,null,'1002Z81000000001BQD6','@@@@',2,'用户',null,null,'N',1,1,'tailinfo',null,0,'2012-06-28 09:20:10','N',null,null,null,0,1,'N',1,null,1,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQGZ',1,-1,null,null,0,0,null,-1,'N',null,-1,'dmakedate',0,'N',1,'N','Y',null,0,'dmakedate','pu.po_praybill.dmakedate',null,'N',0,null,'1002Z81000000001BQD6','@@@@',2,null,null,null,'N',1,2,'tailinfo','tailinfo',0,'2012-06-28 09:20:10','N',null,null,null,0,1,'N',1,null,1,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQH2',1,-1,null,null,0,0,null,-1,'N',null,-1,'approver',0,'N',1,'N','Y',null,0,'approver','pu.po_praybill.approver',null,'N',0,null,'1002Z81000000001BQD6','@@@@',2,'用户',null,null,'N',1,3,'tailinfo',null,0,'2012-06-28 09:20:10','N',null,null,null,0,1,'N',1,null,1,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQH3',1,-1,null,'@SYSOPER',0,0,null,-1,'N',null,-1,'creator',0,'N',1,'N','Y',null,0,'creator','pu.po_praybill.creator',null,'N',0,null,'1002Z81000000001BQD6','@@@@',2,'用户',null,null,'N',1,4,'coperator',null,0,'2012-06-28 09:20:10','N',null,null,null,0,1,'N',1,null,1,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQH4',1,-1,null,null,0,0,null,-1,'N',null,-1,'taudittime',0,'N',1,'N','Y',null,0,'taudittime','pu.po_praybill.taudittime',null,'N',0,null,'1002Z81000000001BQD6','@@@@',2,null,null,null,'N',1,4,'tailinfo',null,0,'2012-06-28 09:20:10','N',null,null,null,0,1,'N',1,null,1,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQH5',1,-1,null,null,0,0,null,-1,'N',null,-1,'creationtime',0,'N',1,'N','Y',null,0,'creationtime','pu.po_praybill.creationtime',null,'N',0,null,'1002Z81000000001BQD6','@@@@',2,null,null,null,'N',1,5,'coperator',null,0,'2012-06-28 09:20:10','N',null,null,null,0,1,'N',1,null,1,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQH6',1,-1,null,null,0,0,null,-1,'N',null,-1,'modifier',0,'N',1,'N','Y',null,0,'modifier','pu.po_praybill.modifier',null,'N',0,null,'1002Z81000000001BQD6','@@@@',2,'用户',null,null,'N',1,6,'coperator',null,0,'2012-06-28 09:20:10','N',null,null,null,0,1,'N',1,null,1,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000001BQH7',1,-1,null,null,0,0,null,-1,'N',null,-1,'modifiedtime',0,'N',1,'N','Y',null,0,'modifiedtime','pu.po_praybill.modifiedtime',null,'N',0,null,'1002Z81000000001BQD6','@@@@',2,null,null,null,'N',1,7,'coperator',null,0,'2012-06-28 09:20:10','N',null,null,null,0,1,'N',1,null,1,7)
go

