insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000015SP5',1,0,'型号',null,0,0,null,-1,'N','pk_material',20,'pk_material.materialtype',null,'N',1,'N','Y',null,0,'materialtype','uap.material.materialtype',null,'N',0,null,'1002Z810000000015SP3',null,1,null,'UC000-0001240',null,'N',1,4,'body','表体',0,'2012-05-18 18:00:07','N',null,null,null,0,1,'N',1,null,100,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000015SP6',1,0,'物料名称',null,0,0,null,-1,'N','pk_material',20,'pk_material.name',null,'N',1,'N','Y',null,0,'name','uap.material.name',null,'N',0,null,'1002Z810000000015SP3',null,1,null,'UC000-0002908',null,'N',1,2,'body','表体',0,'2012-05-18 18:00:07','N',null,null,null,0,1,'N',1,null,100,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000015SP8',1,0,'规格',null,0,0,null,-1,'N','pk_material',20,'pk_material.materialspec',null,'N',1,'N','Y',null,0,'materialspec','uap.material.materialspec',null,'N',0,null,'1002Z810000000015SP3',null,1,null,'UC000-0003448',null,'N',1,3,'body','表体',0,'2012-05-18 18:00:07','N',null,null,null,0,1,'N',1,null,100,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000015SP9',1,5,'物料编码',null,0,0,null,-1,'N',null,20,'pk_material',null,'N',1,'N','Y',null,0,'pk_material','pu.po_order_b.pk_material',null,'N',0,null,'1002Z810000000015SP3',null,1,'物料（多版本）','UC000-0002911',null,'N',1,1,'body','表体',0,'2012-05-18 18:00:07','N',null,null,null,0,1,'N',1,null,100,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000015SPA',1,5,'主单位',null,0,0,null,-1,'N',null,20,'cunitid',null,'N',1,'N','Y',null,0,null,'pu.po_order_b.cunitid',null,'N',0,null,'1002Z810000000015SP3',null,1,'计量单位,code=N','1400404001001',null,'N',1,5,'body','表体',0,'2012-05-18 18:00:07','N',null,null,null,0,1,'N',1,null,100,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000015SPE',1,2,'销售发票量',null,0,0,null,-1,'N',null,20,'ninvoicenum',null,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'1002Z810000000015SP3',null,1,'8,,','1400404000022',null,'N',1,8,'body','表体',1,'2012-05-18 18:00:07','N',null,null,null,0,1,'N',1,null,100,8)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000015SPF',1,2,'销售出库量',null,0,0,null,-1,'N',null,20,'noutnum',null,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'1002Z810000000015SP3',null,1,'8,,','1400404000025',null,'N',1,7,'body','表体',1,'2012-05-18 18:00:07','N',null,null,null,0,1,'N',1,null,100,7)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000015SPG',1,2,'销售订单量',null,0,0,null,-1,'N',null,20,'nordernum',null,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'1002Z810000000015SP3',null,1,'8,,','1400404000006',null,'N',1,6,'body','表体',1,'2012-05-18 18:00:07','N',null,null,null,0,1,'N',1,null,100,6)
go

