insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000000OPH',1,-1,null,'0',0,1,null,-1,'N',null,-1,'fapportionmode',0,'N',1,'N','Y',null,0,'fapportionmode','pu.po_costfactor.fapportionmode',null,'N',0,null,'1001Z810000000000OPG','@@@@',0,null,null,null,'N',1,5,'po_costfactor','成本要素表头',0,'2011-07-25 14:48:34','N',null,null,null,1,1,'N',1,null,1,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000000OPI',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_costfactor',0,'N',1,'N','N',null,0,'pk_costfactor','pu.po_costfactor.pk_costfactor',null,'N',0,null,'1001Z810000000000OPG','@@@@',0,null,null,null,'N',0,1,'po_costfactor','成本要素表头',0,'2011-07-25 14:48:34','N',null,null,null,0,1,'N',1,null,1,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000000OPJ',1,-1,null,null,0,1,null,-1,'Y',null,-1,'pk_material',0,'N',1,'Y','Y',null,0,'pk_material','pu.po_costfactor_b.pk_material','pk_srcmaterial=pk_source','N',0,null,'1001Z810000000000OPG','@@@@',1,'物料（多版本）',null,null,'N',1,2,'costfactorbody','成本要素表体',0,'2011-07-25 14:48:34','N',null,null,null,1,1,'N',1,null,100,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000000OPK',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',null,0,'ts','pu.po_costfactor_b.ts',null,'N',0,null,'1001Z810000000000OPG','@@@@',1,null,null,null,'N',0,4,'costfactorbody','成本要素表体',0,'2011-07-25 14:48:34','N',null,null,null,1,1,'N',1,null,100,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000000OPL',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfactorname',0,'N',1,'N','Y',null,0,'vfactorname','pu.po_costfactor.vfactorname',null,'N',1,null,'1001Z810000000000OPG','@@@@',0,null,null,null,'N',1,4,'po_costfactor','成本要素表头',0,'2011-07-25 14:48:34','N',null,null,null,1,1,'N',1,null,1,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000000OPM',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','Y',null,0,'pk_org','pu.po_costfactor.pk_org','pk_org_v=pk_vid','N',1,null,'1001Z810000000000OPG','@@@@',0,'财务组织',null,null,'N',1,3,'po_costfactor','成本要素表头',0,'2011-07-25 14:48:34','N',null,null,null,1,1,'N',1,null,1,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000000OPN',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bentercost',0,'N',1,'N','Y',null,0,'bentercost','pu.po_costfactor.bentercost',null,'N',0,null,'1001Z810000000000OPG','@@@@',0,null,null,null,'N',1,6,'po_costfactor','成本要素表头',0,'2011-07-25 14:48:34','N',null,null,null,1,1,'N',1,null,1,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000000OPO',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',null,0,'pk_group','pu.po_costfactor.pk_group',null,'N',0,null,'1001Z810000000000OPG','@@@@',0,'集团',null,null,'N',0,2,'po_costfactor','成本要素表头',0,'2011-07-25 14:48:34','N',null,null,null,0,1,'N',1,null,1,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000000OPP',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',null,0,'ts','pu.po_costfactor.ts',null,'N',0,null,'1001Z810000000000OPG','@@@@',0,null,null,null,'N',0,7,'po_costfactor','成本要素表头',0,'2011-07-25 14:48:34','N',null,null,null,1,1,'N',1,null,1,7)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000000OPR',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_costfactor_b',0,'N',1,'N','N',null,0,'pk_costfactor_b','pu.po_costfactor_b.pk_costfactor_b',null,'N',0,null,'1001Z810000000000OPG','@@@@',1,null,null,null,'N',0,1,'costfactorbody','成本要素表体',0,'2011-07-25 14:48:34','N',null,null,null,0,1,'N',1,null,100,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000000OQ0',1,-1,null,null,0,0,null,-1,'N','pk_material',-1,'pk_material.name',0,'N',1,'N','Y',null,0,'name','uap.material.name',null,'N',0,null,'1001Z810000000000OPG','@@@@',1,null,null,null,'N',1,3,'costfactorbody','costfactorbody',0,'2011-07-25 14:48:34','N',null,null,null,1,1,'N',1,null,100,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000005P8X',1,-1,null,null,0,1,null,-1,'N',null,-1,'ishoworder',0,'N',1,'N','N',null,0,'ishoworder','pu.po_costfactor_b.ishoworder',null,'N',0,null,'1001Z810000000000OPG','@@@@',1,null,null,null,'N',0,7,'costfactorbody','costfactorbody',0,'2011-07-25 14:48:34','N',null,null,null,1,1,'N',1,null,100,7)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z810000000005P8Y',1,-1,null,null,0,1,null,-1,'N',null,-1,'bshow',0,'N',1,'N','N',null,0,'bshow','pu.po_costfactor_b.bshow',null,'N',0,null,'1001Z810000000000OPG','@@@@',1,null,null,null,'N',0,6,'costfactorbody','costfactorbody',0,'2011-07-25 14:48:34','N',null,null,null,1,1,'N',1,null,100,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1004Z8100000000065G9',1,-1,null,null,0,1,null,-1,'N',null,-1,'ifactororder',0,'N',1,'N','N',null,0,'ifactororder','pu.po_costfactor.ifactororder',null,'N',0,null,'1001Z810000000000OPG','@@@@',0,null,null,null,'N',0,9,'po_costfactor','po_costfactor',0,'2011-07-25 14:48:34','N',null,null,null,1,1,'N',1,null,1,9)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000002W64',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_srcmaterial',0,'N',1,'N','N',null,0,'pk_srcmaterial','pu.po_costfactor_b.pk_srcmaterial',null,'N',0,null,'1001Z810000000000OPG','@@@@',1,'物料',null,null,'N',0,5,'costfactorbody','costfactorbody',0,'2011-07-25 14:48:34','N',null,null,null,1,1,'N',1,null,100,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000002W67',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org_v',0,'N',1,'N','N',null,0,'pk_org_v','pu.po_costfactor.pk_org_v',null,'N',0,null,'1001Z810000000000OPG','@@@@',0,null,null,null,'N',1,8,'po_costfactor','po_costfactor',0,'2011-07-25 14:48:34','N',null,null,null,0,1,'N',1,null,1,8)
go

