insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK1N',1,-1,null,null,0,1,null,-1,'N',null,-1,'taudittime',null,'N',1,'N','N',null,0,'taudittime','pu.po_invoice.taudittime',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,59,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,59)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK1O',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef4',null,'N',1,'N','N',null,0,'vdef4','pu.po_invoice.vdef4',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,27,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,27)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK1P',1,-1,null,null,0,1,null,-1,'N',null,-1,'vmemo',null,'N',1,'N','N',null,0,'vmemo','pu.po_invoice.vmemo',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,51,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,51)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK1Q',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef17',null,'N',1,'N','N',null,0,'vdef17','pu.po_invoice.vdef17',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,40,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,40)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK1R',1,-1,null,null,0,1,null,-1,'N',null,-1,'corigcurrencyid',null,'N',1,'N','N',null,0,'corigcurrencyid','pu.po_invoice.corigcurrencyid',null,'N',0,null,'1001Z81000000000RCKI',null,1,'币种档案,code=N',null,null,'N',0,44,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,44)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK1S',1,-1,null,null,0,1,null,-1,'N',null,-1,'vvendorvatcode',null,'N',1,'N','N',null,0,'vvendorvatcode','pu.po_invoice.vvendorvatcode',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,82,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,82)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK1T',1,-1,null,null,0,1,null,-1,'N',null,-1,'ngroupexchgrate',null,'N',1,'N','N',null,0,'ngroupexchgrate','pu.po_invoice.ngroupexchgrate',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,68,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,68)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK1U',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef3',null,'N',1,'N','N',null,0,'vdef3','pu.po_invoice.vdef3',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,26,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,26)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK1V',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_bankaccbas',null,'N',1,'N','N',null,0,'pk_bankaccbas','pu.po_invoice.pk_bankaccbas',null,'N',0,null,'1001Z81000000000RCKI',null,1,'客商银行账户,code=N',null,null,'N',0,17,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,17)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK1W',1,-1,null,null,0,1,null,-1,'N',null,-1,'crececountryid',null,'N',1,'N','N',null,0,'crececountryid','pu.po_invoice.crececountryid',null,'N',0,null,'1001Z81000000000RCKI',null,1,'国家地区,code=N',null,null,'N',0,75,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,75)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK1X',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef7',null,'N',1,'N','N',null,0,'vdef7','pu.po_invoice.vdef7',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,30,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,30)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK1Y',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_purchaseorg_v',null,'N',1,'N','N',null,0,'pk_purchaseorg_v','pu.po_invoice.pk_purchaseorg_v',null,'N',0,null,'1001Z81000000000RCKI',null,1,'采购组织版本,code=N',null,null,'N',0,13,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,13)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK1Z',1,-1,null,null,0,1,null,-1,'N',null,-1,'dbilldate',null,'N',1,'N','Y',null,0,'dbilldate','pu.po_invoice.dbilldate',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,'1400410000027',null,'N',1,6,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK20',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',null,'N',1,'N','N',null,0,'ts','pu.po_invoice.ts',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,85,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,85)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK21',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_invoice',null,'N',1,'N','N',null,0,'pk_invoice','pu.po_invoice.pk_invoice',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,1,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK22',1,-1,null,null,0,1,null,-1,'N',null,-1,'creationtime',null,'N',1,'N','N',null,0,'creationtime','pu.po_invoice.creationtime',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,57,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,57)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK23',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_freecust',null,'N',1,'N','N',null,0,'pk_freecust','pu.po_invoice.pk_freecust',null,'N',0,null,'1001Z81000000000RCKI',null,1,'散户,code=N',null,null,'N',0,18,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,18)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK24',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef12',null,'N',1,'N','N',null,0,'vdef12','pu.po_invoice.vdef12',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,35,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,35)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK25',1,-1,null,null,0,1,null,-1,'N',null,-1,'ctrantypeid',null,'N',1,'N','Y',null,0,'ctrantypeid','pu.po_invoice.ctrantypeid',null,'N',0,null,'1001Z81000000000RCKI',null,1,'影响因素交 易类型,code=N,dpc=SCMDefault','1400410000028',null,'N',1,9,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,9)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK26',1,-1,null,null,0,1,null,-1,'N',null,-1,'ccurrencyid',null,'N',1,'N','N',null,0,'ccurrencyid','pu.po_invoice.ccurrencyid',null,'N',0,null,'1001Z81000000000RCKI',null,1,'币种档案,code=N',null,null,'N',0,67,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,67)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK27',1,-1,null,null,0,1,null,-1,'N',null,-1,'modifier',null,'N',1,'N','N',null,0,'modifier','pu.po_invoice.modifier',null,'N',0,null,'1001Z81000000000RCKI',null,1,'用户,code=N',null,null,'N',0,60,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,60)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK28',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbankaccount',null,'N',1,'N','N',null,0,'vbankaccount','pu.po_invoice.vbankaccount',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,73,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,73)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK29',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_payterm',null,'N',1,'N','N',null,0,'pk_payterm','pu.po_invoice.pk_payterm',null,'N',0,null,'1001Z81000000000RCKI',null,1,'付款协议,code=N',null,null,'N',0,23,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,23)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK2A',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef18',null,'N',1,'N','N',null,0,'vdef18','pu.po_invoice.vdef18',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,41,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,41)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK2B',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_stockorg',null,'N',1,'N','N',null,0,'pk_stockorg','pu.po_invoice.pk_stockorg',null,'N',0,null,'1001Z81000000000RCKI',null,1,'库存组织,code=N',null,null,'N',0,14,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,14)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK2C',1,-1,null,null,0,1,null,-1,'N',null,-1,'vtrantypecode',null,'N',1,'N','N',null,0,'vtrantypecode','pu.po_invoice.vtrantypecode',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,8,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,8)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK2D',1,-1,null,null,0,1,null,-1,'N',null,-1,'modifiedtime',null,'N',1,'N','N',null,0,'modifiedtime','pu.po_invoice.modifiedtime',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,61,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,61)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK2E',1,-1,null,null,0,1,null,-1,'N',null,-1,'dmakedate',null,'N',1,'N','N',null,0,'dmakedate','pu.po_invoice.dmakedate',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,56,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,56)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK2F',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef8',null,'N',1,'N','N',null,0,'vdef8','pu.po_invoice.vdef8',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,31,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,31)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK2G',1,-1,null,'false',0,1,null,-1,'N',null,-1,'btriatradeflag',null,'N',1,'N','N',null,0,'btriatradeflag','pu.po_invoice.btriatradeflag',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,78,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,78)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK2H',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef2',null,'N',1,'N','N',null,0,'vdef2','pu.po_invoice.vdef2',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,25,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,25)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK2I',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef14',null,'N',1,'N','N',null,0,'vdef14','pu.po_invoice.vdef14',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,37,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,37)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK2J',1,-1,null,null,0,1,null,-1,'N',null,-1,'fbillstatus',null,'N',1,'N','N',null,0,'fbillstatus','pu.po_invoice.fbillstatus',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,54,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,54)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK2K',1,-1,null,null,0,1,null,-1,'N',null,-1,'csendcountryid',null,'N',1,'N','N',null,0,'csendcountryid','pu.po_invoice.csendcountryid',null,'N',0,null,'1001Z81000000000RCKI',null,1,'国家地区,code=N',null,null,'N',0,74,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,74)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK2L',1,-1,null,'0',0,1,null,-1,'N',null,-1,'iprintcount',null,'N',1,'N','N',null,0,'iprintcount','pu.po_invoice.iprintcount',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,62,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,62)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK2M',1,-1,null,null,0,1,null,-1,'N',null,-1,'tfrozentime',null,'N',1,'N','N',null,0,'tfrozentime','pu.po_invoice.tfrozentime',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,53,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,53)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK2N',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_parentinvoice',null,'N',1,'N','N',null,0,'pk_parentinvoice','pu.po_invoice.pk_parentinvoice',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,63,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,63)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK2O',1,-1,null,null,0,1,null,-1,'N',null,-1,'vvatcode',null,'N',1,'N','N',null,0,'vvatcode','pu.po_invoice.vvatcode',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,81,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,81)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK2P',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_group',null,'N',1,'N','N',null,0,'pk_group','pu.po_invoice.pk_group',null,'N',0,null,'1001Z81000000000RCKI',null,1,'集团,code=N',null,null,'N',0,2,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK2Q',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef16',null,'N',1,'N','N',null,0,'vdef16','pu.po_invoice.vdef16',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,39,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,39)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK2R',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_bizpsn',null,'N',1,'N','Y',null,0,'pk_bizpsn','pu.po_invoice.pk_bizpsn',null,'N',0,null,'1001Z81000000000RCKI',null,1,'人员,code=N,dpc=SCMDefault','1400410000029',null,'N',1,19,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,19)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK2S',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bfee',null,'N',1,'N','N',null,0,'bfee','pu.po_invoice.bfee',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,11,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,11)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK2T',1,-1,null,null,0,1,null,-1,'N',null,-1,'fbuysellflag',null,'N',1,'N','N',null,0,'fbuysellflag','pu.po_invoice.fbuysellflag',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,77,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,77)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK2U',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef11',null,'N',1,'N','N',null,0,'vdef11','pu.po_invoice.vdef11',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,34,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,34)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK2V',1,-1,null,null,0,1,null,-1,'N',null,-1,'ntaxrateh',null,'N',1,'N','N',null,0,'ntaxrateh','pu.po_invoice.ntaxrateh',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,66,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,66)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK2W',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org_v',null,'N',1,'N','N',null,0,'pk_org_v','pu.po_invoice.pk_org_v',null,'N',0,null,'1001Z81000000000RCKI',null,1,'财务组织版本,code=N',null,null,'N',0,4,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK2X',1,-1,null,null,0,1,null,-1,'N',null,-1,'ctradewordid',null,'N',1,'N','N',null,0,'ctradewordid','pu.po_invoice.ctradewordid',null,'N',0,null,'1001Z81000000000RCKI',null,1,'贸易术语,code=N',null,null,'N',0,79,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,79)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK2Y',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org',null,'N',1,'N','N',null,0,'pk_org','pu.po_invoice.pk_org',null,'N',0,null,'1001Z81000000000RCKI',null,1,'财务组织,code=N',null,null,'N',0,3,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK2Z',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef20',null,'N',1,'N','N',null,0,'vdef20','pu.po_invoice.vdef20',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,43,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,43)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK30',1,-1,null,'0',0,1,null,-1,'N',null,-1,'finvoiceclass',null,'N',1,'N','N',null,0,'finvoiceclass','pu.po_invoice.finvoiceclass',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,64,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,64)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK31',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bopptaxflag',null,'N',1,'N','N',null,0,'bopptaxflag','pu.po_invoice.bopptaxflag',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,80,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,80)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK32',1,-1,null,null,0,1,null,-1,'N',null,-1,'billmaker',null,'N',1,'N','Y',null,0,'billmaker','pu.po_invoice.billmaker',null,'N',0,null,'1001Z81000000000RCKI',null,1,'用户,code=N,dpc=SCMDefault',null,null,'N',1,55,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,55)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK33',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef5',null,'N',1,'N','N',null,0,'vdef5','pu.po_invoice.vdef5',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,28,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,28)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK34',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_dept_v',null,'N',1,'N','N',null,0,'pk_dept_v','pu.po_invoice.pk_dept_v',null,'N',0,null,'1001Z81000000000RCKI',null,1,'部门版本,code=N',null,null,'N',0,21,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,21)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK35',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_supplier',null,'N',1,'N','Y',null,0,'pk_supplier','pu.po_invoice.pk_supplier',null,'N',0,null,'1001Z81000000000RCKI',null,1,'供应商档案,code=N,dpc=SCMDefault',null,null,'N',1,16,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,16)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK36',1,-1,null,null,0,1,null,-1,'N',null,-1,'darrivedate',null,'N',1,'N','N',null,0,'darrivedate','pu.po_invoice.darrivedate',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,7,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,7)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK37',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_paytosupplier',null,'N',1,'N','N',null,0,'pk_paytosupplier','pu.po_invoice.pk_paytosupplier',null,'N',0,null,'1001Z81000000000RCKI',null,1,'供应商档案,code=N',null,null,'N',0,22,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,22)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK38',1,-1,null,'false',0,1,null,-1,'N',null,-1,'binitial',null,'N',1,'N','N',null,0,'binitial','pu.po_invoice.binitial',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,70,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,70)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK39',1,-1,null,'1.00000000',0,1,null,-1,'N',null,-1,'nexchangerate',null,'N',1,'N','N',null,0,'nexchangerate','pu.po_invoice.nexchangerate',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,45,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,45)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK3A',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef10',null,'N',1,'N','N',null,0,'vdef10','pu.po_invoice.vdef10',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,33,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,33)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK3B',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_stockorg_v',null,'N',1,'N','N',null,0,'pk_stockorg_v','pu.po_invoice.pk_stockorg_v',null,'N',0,null,'1001Z81000000000RCKI',null,1,'库存组织版本,code=N',null,null,'N',0,15,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,15)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK3C',1,-1,null,null,0,1,null,-1,'N',null,-1,'ctaxcountryid',null,'N',1,'N','N',null,0,'ctaxcountryid','pu.po_invoice.ctaxcountryid',null,'N',0,null,'1001Z81000000000RCKI',null,1,'国家地区,code=N',null,null,'N',0,76,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,76)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK3D',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_busitype',null,'N',1,'N','N',null,0,'pk_busitype','pu.po_invoice.pk_busitype',null,'N',0,null,'1001Z81000000000RCKI',null,1,'业务流程,code=N',null,null,'N',0,10,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,10)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK3E',1,-1,null,'1',0,1,null,-1,'N',null,-1,'ftaxtypeflagh',null,'N',1,'N','N',null,0,'ftaxtypeflagh','pu.po_invoice.ftaxtypeflagh',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,65,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,65)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK3F',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef15',null,'N',1,'N','N',null,0,'vdef15','pu.po_invoice.vdef15',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,38,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,38)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK3G',1,-1,null,null,0,1,null,-1,'N',null,-1,'nglobalexchgrate',null,'N',1,'N','N',null,0,'nglobalexchgrate','pu.po_invoice.nglobalexchgrate',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,69,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,69)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK3H',1,-1,null,null,0,1,null,-1,'N',null,-1,'creator',null,'N',1,'N','N',null,0,'creator','pu.po_invoice.creator',null,'N',0,null,'1001Z81000000000RCKI',null,1,'用户,code=N',null,null,'N',0,71,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,71)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK3I',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bfrozen',null,'N',1,'N','N',null,0,'bfrozen','pu.po_invoice.bfrozen',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,47,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,47)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK3J',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef1',null,'N',1,'N','N',null,0,'vdef1','pu.po_invoice.vdef1',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,24,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,24)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK3K',1,-1,null,null,0,1,null,-1,'N',null,-1,'approver',null,'N',1,'N','N',null,0,'approver','pu.po_invoice.approver',null,'N',0,null,'1001Z81000000000RCKI',null,1,'用户,code=N',null,null,'N',0,58,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,58)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK3L',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef13',null,'N',1,'N','N',null,0,'vdef13','pu.po_invoice.vdef13',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,36,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,36)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK3M',1,-1,null,null,0,1,null,-1,'N',null,-1,'ntotalastnum',null,'N',1,'N','N',null,0,'ntotalastnum','pu.po_invoice.ntotalastnum',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,49,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,49)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK3N',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfrozenreason',null,'N',1,'N','N',null,0,'vfrozenreason','pu.po_invoice.vfrozenreason',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,48,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,48)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK3O',1,-1,null,null,0,1,null,-1,'N',null,-1,'ntotalorigmny',null,'N',1,'N','N',null,0,'ntotalorigmny','pu.po_invoice.ntotalorigmny',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,50,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,50)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK3P',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bvirtual',null,'N',1,'N','N',null,0,'bvirtual','pu.po_invoice.bvirtual',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,72,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,72)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK3Q',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_purchaseorg',null,'N',1,'N','N',null,0,'pk_purchaseorg','pu.po_invoice.pk_purchaseorg',null,'N',0,null,'1001Z81000000000RCKI',null,1,'采购组织,code=N',null,null,'N',0,12,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,12)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK3R',1,-1,null,null,0,1,null,-1,'N',null,-1,'vadjustreason',null,'N',1,'N','N',null,0,'vadjustreason','pu.po_invoice.vadjustreason',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,84,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,84)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK3S',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_frozenuser',null,'N',1,'N','N',null,0,'pk_frozenuser','pu.po_invoice.pk_frozenuser',null,'N',0,null,'1001Z81000000000RCKI',null,1,'用户,code=N',null,null,'N',0,52,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,52)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK3T',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef19',null,'N',1,'N','N',null,0,'vdef19','pu.po_invoice.vdef19',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,42,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,42)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK3U',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef6',null,'N',1,'N','N',null,0,'vdef6','pu.po_invoice.vdef6',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,29,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,29)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK3V',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbillcode',null,'N',1,'N','Y',null,0,'vbillcode','pu.po_invoice.vbillcode',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,'1400410000030',null,'N',1,5,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK3W',1,-1,null,null,0,1,null,-1,'N',null,-1,'finvoicetype',null,'N',1,'N','N',null,0,'finvoicetype','pu.po_invoice.finvoicetype',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,83,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,83)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK3X',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_dept',null,'N',1,'N','N',null,0,'pk_dept','pu.po_invoice.pk_dept',null,'N',0,null,'1001Z81000000000RCKI',null,1,'部门,code=N',null,null,'N',0,20,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,20)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK3Y',1,-1,null,null,0,1,null,-1,'N',null,-1,'vdef9',null,'N',1,'N','N',null,0,'vdef9','pu.po_invoice.vdef9',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,32,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,32)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000TK3Z',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bapflag',null,'N',1,'N','N',null,0,'bapflag','pu.po_invoice.bapflag',null,'N',0,null,'1001Z81000000000RCKI',null,1,null,null,null,'N',0,46,'po_invoice','采购发票主表',0,'2015-03-04 15:53:40','N',null,null,null,1,1,'N',1,null,100,46)
go

