/***************************************************************
 * \ The skeleton of this class is generated by an automatic * code generator
 * for NC product. It is based on Velocity. * \
 ***************************************************************/
package nc.vo.pu.m21.entity;

import nc.vo.pub.IVOMeta;
import nc.vo.pub.SuperVO;
import nc.vo.pub.lang.UFDate;
import nc.vo.pub.lang.UFDateTime;
import nc.vo.pub.lang.UFDouble;
import nc.vo.pubapp.pattern.model.meta.entity.vo.VOMetaFactory;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:2010-08-06 14:53:39
 * 
 * @author
 * @version NCPrj ??
 */
public class OrderOnwayItemVO extends SuperVO {

  /** 确认标识 */
  public static final String BCONFIRMFLAG = "bconfirmflag";

  /** 承运商 */
  public static final String CCARRIER = "ccarrier";

  /** 货柜号 */
  public static final String CCASECODE = "ccasecode";

  /** 到货港口 */
  public static final String CLANDPORT = "clandport";

  /** 装船港口 */
  public static final String CLOADPORT = "cloadport";

  /** 行号 */
  public static final String CROWNO = "crowno";

  /** 船次号 */
  public static final String CSHIPLINE = "cshipline";

  /** 船名 */
  public static final String CSHIPNAME = "cshipname";

  /** 主单位 */
  public static final String CUNITID = "cunitid";

  /** 单据日期 */
  public static final String DBILLDATE = "dbilldate";

  /** 计划到货日期 */
  public static final String DPLANARRVDATE = "dplanarrvdate";

  /** 计划到港日期 */
  public static final String DPLANFREIGHTDATE = "dplanfreightdate";

  /** dr */
  public static final String DR = "dr";

  /** 在途状态 */
  public static final String FONWAYSTATUS = "fonwaystatus";

  /** 行状态 */
  public static final String FORDERROWSTATUS = "forderrowstatus";

  /** 累计数量 */
  public static final String NACCUNUM = "naccunum";

  /** 确认数量 */
  public static final String NCONFIRMNUM = "nconfirmnum";

  /** 主数量 */
  public static final String NNUM = "nnum";

  /** 已发货金额 */
  public static final String NONWAYMNY = "nonwaymny";

  /** 在途数量 */
  public static final String NONWAYNUM = "nonwaynum";

  /** 原币无税金额 */
  public static final String NORIGMNY = "norigmny";

  /** 主无税净价 */
  public static final String NORIGNETPRICE = "norignetprice";

  /** 本次发货数量 */
  public static final String NSENDOUTNUM = "nsendoutnum";

  /** 本次发货金额 */
  public static final String NSTATUSMNY = "nstatusmny";

  /** 所属集团 */
  public static final String PK_GROUP = "pk_group";

  /** 物料版本信息 */
  public static final String PK_MATERIAL = "pk_material";

  /** 采购订单在途状态 */
  public static final String PK_ORDER = "pk_order";

  /** 采购订单子表 */
  public static final String PK_ORDER_B = "pk_order_b";

  /** 采购订单在途状态 */
  public static final String PK_ORDER_BB = "pk_order_bb";

  /** 采购组织版本信息 */
  public static final String PK_ORG = "pk_org";

  /** 采购组织 */
  public static final String PK_ORG_V = "pk_org_v";

  /** ts */
  public static final String TS = "ts";

  /** 自定义项1 */
  public static final String VBDEF1 = "vbdef1";

  /** 自定义项10 */
  public static final String VBDEF10 = "vbdef10";

  /** 自定义项11 */
  public static final String VBDEF11 = "vbdef11";

  /** 自定义项12 */
  public static final String VBDEF12 = "vbdef12";

  /** 自定义项13 */
  public static final String VBDEF13 = "vbdef13";

  /** 自定义项14 */
  public static final String VBDEF14 = "vbdef14";

  /** 自定义项15 */
  public static final String VBDEF15 = "vbdef15";

  /** 自定义项16 */
  public static final String VBDEF16 = "vbdef16";

  /** 自定义项17 */
  public static final String VBDEF17 = "vbdef17";

  /** 自定义项18 */
  public static final String VBDEF18 = "vbdef18";

  /** 自定义项19 */
  public static final String VBDEF19 = "vbdef19";

  /** 自定义项2 */
  public static final String VBDEF2 = "vbdef2";

  /** 自定义项20 */
  public static final String VBDEF20 = "vbdef20";

  /** 自定义项21 */
  public static final String VBDEF21 = "vbdef21";

  /** 自定义项22 */
  public static final String VBDEF22 = "vbdef22";

  /** 自定义项23 */
  public static final String VBDEF23 = "vbdef23";

  /** 自定义项24 */
  public static final String VBDEF24 = "vbdef24";

  /** 自定义项25 */
  public static final String VBDEF25 = "vbdef25";

  /** 自定义项26 */
  public static final String VBDEF26 = "vbdef26";

  /** 自定义项27 */
  public static final String VBDEF27 = "vbdef27";

  /** 自定义项28 */
  public static final String VBDEF28 = "vbdef28";

  /** 自定义项29 */
  public static final String VBDEF29 = "vbdef29";

  /** 自定义项3 */
  public static final String VBDEF3 = "vbdef3";

  /** 自定义项30 */
  public static final String VBDEF30 = "vbdef30";

  /** 自定义项31 */
  public static final String VBDEF31 = "vbdef31";

  /** 自定义项32 */
  public static final String VBDEF32 = "vbdef32";

  /** 自定义项33 */
  public static final String VBDEF33 = "vbdef33";

  /** 自定义项34 */
  public static final String VBDEF34 = "vbdef34";

  /** 自定义项35 */
  public static final String VBDEF35 = "vbdef35";

  /** 自定义项36 */
  public static final String VBDEF36 = "vbdef36";

  /** 自定义项37 */
  public static final String VBDEF37 = "vbdef37";

  /** 自定义项38 */
  public static final String VBDEF38 = "vbdef38";

  /** 自定义项39 */
  public static final String VBDEF39 = "vbdef39";

  /** 自定义项4 */
  public static final String VBDEF4 = "vbdef4";

  /** 自定义项40 */
  public static final String VBDEF40 = "vbdef40";

  /** 自定义项5 */
  public static final String VBDEF5 = "vbdef5";

  /** 自定义项6 */
  public static final String VBDEF6 = "vbdef6";

  /** 自定义项7 */
  public static final String VBDEF7 = "vbdef7";

  /** 自定义项8 */
  public static final String VBDEF8 = "vbdef8";

  /** 自定义项9 */
  public static final String VBDEF9 = "vbdef9";

  /** 单据编号 */
  public static final String VBILLCODE = "vbillcode";

  private static final long serialVersionUID = 423486022846913136L;

  /** 承运商 getter 方法 */
  public String getCcarrier() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.CCARRIER);
  }

  /** 货柜号 getter 方法 */
  public String getCcasecode() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.CCASECODE);
  }

  /** 到货港口 getter 方法 */
  public String getClandport() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.CLANDPORT);
  }

  /** 装船港口 getter 方法 */
  public String getCloadport() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.CLOADPORT);
  }

  /** 行号 getter 方法 */
  public String getCrowno() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.CROWNO);
  }

  /** 船次号 getter 方法 */
  public String getCshipline() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.CSHIPLINE);
  }

  /** 船名 getter 方法 */
  public String getCshipname() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.CSHIPNAME);
  }

  /** 主单位 getter 方法 */
  public String getCunitid() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.CUNITID);
  }

  /** 单据日期 getter 方法 */
  public UFDate getDbilldate() {
    return (UFDate) this.getAttributeValue(OrderOnwayItemVO.DBILLDATE);
  }

  /** 计划到货日期 getter 方法 */
  public UFDate getDplanarrvdate() {
    return (UFDate) this.getAttributeValue(OrderOnwayItemVO.DPLANARRVDATE);
  }

  /** 计划到港日期 getter 方法 */
  public UFDate getDplanfreightdate() {
    return (UFDate) this.getAttributeValue(OrderOnwayItemVO.DPLANFREIGHTDATE);
  }

  /** dr getter 方法 */
  public Integer getDr() {
    return (Integer) this.getAttributeValue(OrderOnwayItemVO.DR);
  }

  /** 在途状态 getter 方法 */
  public Integer getFonwaystatus() {
    return (Integer) this.getAttributeValue(OrderOnwayItemVO.FONWAYSTATUS);
  }

  /** 行状态 getter 方法 */
  public Integer getForderrowstatus() {
    return (Integer) this.getAttributeValue(OrderOnwayItemVO.FORDERROWSTATUS);
  }

  @Override
  public IVOMeta getMetaData() {
    IVOMeta meta = VOMetaFactory.getInstance().getVOMeta("pu.po_order_bb_vo");
    return meta;
  }

  /** 累计数量 getter 方法 */
  public UFDouble getNaccunum() {
    return (UFDouble) this.getAttributeValue(OrderOnwayItemVO.NACCUNUM);
  }

  /** 确认数量 getter 方法 */
  public UFDouble getNconfirmnum() {
    return (UFDouble) this.getAttributeValue(OrderOnwayItemVO.NCONFIRMNUM);
  }

  /** 主数量 getter 方法 */
  public UFDouble getNnum() {
    return (UFDouble) this.getAttributeValue(OrderOnwayItemVO.NNUM);
  }

  /** 已发货金额 getter 方法 */
  public UFDouble getNonwaymny() {
    return (UFDouble) this.getAttributeValue(OrderOnwayItemVO.NONWAYMNY);
  }

  /** 在途数量 getter 方法 */
  public UFDouble getNonwaynum() {
    return (UFDouble) this.getAttributeValue(OrderOnwayItemVO.NONWAYNUM);
  }

  /** 原币无税金额 getter 方法 */
  public UFDouble getNorigmny() {
    return (UFDouble) this.getAttributeValue(OrderOnwayItemVO.NORIGMNY);
  }

  /** 主无税净价 getter 方法 */
  public UFDouble getNorignetprice() {
    return (UFDouble) this.getAttributeValue(OrderOnwayItemVO.NORIGNETPRICE);
  }

  /** 本次发货数量 getter 方法 */
  public UFDouble getNsendoutnum() {
    return (UFDouble) this.getAttributeValue(OrderOnwayItemVO.NSENDOUTNUM);
  }

  /** 本次发货金额 getter 方法 */
  public UFDouble getNstatusmny() {
    return (UFDouble) this.getAttributeValue(OrderOnwayItemVO.NSTATUSMNY);
  }

  /** 所属集团 getter 方法 */
  public String getPk_group() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.PK_GROUP);
  }

  /** 物料版本信息 getter 方法 */
  public String getPk_material() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.PK_MATERIAL);
  }

  /** 采购订单在途状态 getter 方法 */
  public String getPk_order() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.PK_ORDER);
  }

  /** 采购订单子表 getter 方法 */
  public String getPk_order_b() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.PK_ORDER_B);
  }

  /** 采购订单在途状态 getter 方法 */
  public String getPk_order_bb() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.PK_ORDER_BB);
  }

  /** 采购组织版本信息 getter 方法 */
  public String getPk_org() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.PK_ORG);
  }

  /** 采购组织 getter 方法 */
  public String getPk_org_v() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.PK_ORG_V);
  }

  /** ts getter 方法 */
  public UFDateTime getTs() {
    return (UFDateTime) this.getAttributeValue(OrderOnwayItemVO.TS);
  }

  /** 自定义项1 getter 方法 */
  public String getVbdef1() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF1);
  }

  /** 自定义项10 getter 方法 */
  public String getVbdef10() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF10);
  }

  /** 自定义项11 getter 方法 */
  public String getVbdef11() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF11);
  }

  /** 自定义项12 getter 方法 */
  public String getVbdef12() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF12);
  }

  /** 自定义项13 getter 方法 */
  public String getVbdef13() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF13);
  }

  /** 自定义项14 getter 方法 */
  public String getVbdef14() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF14);
  }

  /** 自定义项15 getter 方法 */
  public String getVbdef15() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF15);
  }

  /** 自定义项16 getter 方法 */
  public String getVbdef16() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF16);
  }

  /** 自定义项17 getter 方法 */
  public String getVbdef17() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF17);
  }

  /** 自定义项18 getter 方法 */
  public String getVbdef18() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF18);
  }

  /** 自定义项19 getter 方法 */
  public String getVbdef19() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF19);
  }

  /** 自定义项2 getter 方法 */
  public String getVbdef2() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF2);
  }

  /** 自定义项20 getter 方法 */
  public String getVbdef20() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF20);
  }

  /** 自定义项21 getter 方法 */
  public String getVbdef21() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF21);
  }

  /** 自定义项22 getter 方法 */
  public String getVbdef22() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF22);
  }

  /** 自定义项23 getter 方法 */
  public String getVbdef23() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF23);
  }

  /** 自定义项24 getter 方法 */
  public String getVbdef24() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF24);
  }

  /** 自定义项25 getter 方法 */
  public String getVbdef25() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF25);
  }

  /** 自定义项26 getter 方法 */
  public String getVbdef26() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF26);
  }

  /** 自定义项27 getter 方法 */
  public String getVbdef27() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF27);
  }

  /** 自定义项28 getter 方法 */
  public String getVbdef28() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF28);
  }

  /** 自定义项29 getter 方法 */
  public String getVbdef29() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF29);
  }

  /** 自定义项3 getter 方法 */
  public String getVbdef3() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF3);
  }

  /** 自定义项30 getter 方法 */
  public String getVbdef30() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF30);
  }

  /** 自定义项31 getter 方法 */
  public String getVbdef31() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF31);
  }

  /** 自定义项32 getter 方法 */
  public String getVbdef32() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF32);
  }

  /** 自定义项33 getter 方法 */
  public String getVbdef33() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF33);
  }

  /** 自定义项34 getter 方法 */
  public String getVbdef34() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF34);
  }

  /** 自定义项35 getter 方法 */
  public String getVbdef35() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF35);
  }

  /** 自定义项36 getter 方法 */
  public String getVbdef36() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF36);
  }

  /** 自定义项37 getter 方法 */
  public String getVbdef37() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF37);
  }

  /** 自定义项38 getter 方法 */
  public String getVbdef38() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF38);
  }

  /** 自定义项39 getter 方法 */
  public String getVbdef39() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF39);
  }

  /** 自定义项4 getter 方法 */
  public String getVbdef4() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF4);
  }

  /** 自定义项40 getter 方法 */
  public String getVbdef40() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF40);
  }

  /** 自定义项5 getter 方法 */
  public String getVbdef5() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF5);
  }

  /** 自定义项6 getter 方法 */
  public String getVbdef6() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF6);
  }

  /** 自定义项7 getter 方法 */
  public String getVbdef7() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF7);
  }

  /** 自定义项8 getter 方法 */
  public String getVbdef8() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF8);
  }

  /** 自定义项9 getter 方法 */
  public String getVbdef9() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBDEF9);
  }

  /** 单据编号 getter 方法 */
  public String getVbillcode() {
    return (String) this.getAttributeValue(OrderOnwayItemVO.VBILLCODE);
  }

  /** 承运商 setter 方法 */
  public void setCcarrier(String ccarrier) {
    this.setAttributeValue(OrderOnwayItemVO.CCARRIER, ccarrier);
  }

  /** 货柜号 setter 方法 */
  public void setCcasecode(String ccasecode) {
    this.setAttributeValue(OrderOnwayItemVO.CCASECODE, ccasecode);
  }

  /** 到货港口 setter 方法 */
  public void setClandport(String clandport) {
    this.setAttributeValue(OrderOnwayItemVO.CLANDPORT, clandport);
  }

  /** 装船港口 setter 方法 */
  public void setCloadport(String cloadport) {
    this.setAttributeValue(OrderOnwayItemVO.CLOADPORT, cloadport);
  }

  /** 行号 setter 方法 */
  public void setCrowno(String crowno) {
    this.setAttributeValue(OrderOnwayItemVO.CROWNO, crowno);
  }

  /** 船次号 setter 方法 */
  public void setCshipline(String cshipline) {
    this.setAttributeValue(OrderOnwayItemVO.CSHIPLINE, cshipline);
  }

  /** 船名 setter 方法 */
  public void setCshipname(String cshipname) {
    this.setAttributeValue(OrderOnwayItemVO.CSHIPNAME, cshipname);
  }

  /** 主单位 setter 方法 */
  public void setCunitid(String cunitid) {
    this.setAttributeValue(OrderOnwayItemVO.CUNITID, cunitid);
  }

  /** 单据日期 setter 方法 */
  public void setDbilldate(UFDate dbilldate) {
    this.setAttributeValue(OrderOnwayItemVO.DBILLDATE, dbilldate);
  }

  /** 计划到货日期 setter 方法 */
  public void setDplanarrvdate(UFDate dplanarrvdate) {
    this.setAttributeValue(OrderOnwayItemVO.DPLANARRVDATE, dplanarrvdate);
  }

  /** 计划到港日期 setter 方法 */
  public void setDplanfreightdate(UFDate dplanfreightdate) {
    this.setAttributeValue(OrderOnwayItemVO.DPLANFREIGHTDATE, dplanfreightdate);
  }

  /** dr setter 方法 */
  public void setDr(Integer dr) {
    this.setAttributeValue(OrderOnwayItemVO.DR, dr);
  }

  /** 在途状态 setter 方法 */
  public void setFonwaystatus(Integer fonwaystatus) {
    this.setAttributeValue(OrderOnwayItemVO.FONWAYSTATUS, fonwaystatus);
  }

  /** 行状态 setter 方法 */
  public void setForderrowstatus(Integer forderrowstatus) {
    this.setAttributeValue(OrderOnwayItemVO.FORDERROWSTATUS, forderrowstatus);
  }

  /** 累计数量 setter 方法 */
  public void setNaccunum(UFDouble naccunum) {
    this.setAttributeValue(OrderOnwayItemVO.NACCUNUM, naccunum);
  }

  /** 确认数量 setter 方法 */
  public void setNconfirmnum(UFDouble nconfirmnum) {
    this.setAttributeValue(OrderOnwayItemVO.NCONFIRMNUM, nconfirmnum);
  }

  /** 主数量 setter 方法 */
  public void setNnum(UFDouble nnum) {
    this.setAttributeValue(OrderOnwayItemVO.NNUM, nnum);
  }

  /** 已发货金额 setter 方法 */
  public void setNonwaymny(UFDouble nonwaymny) {
    this.setAttributeValue(OrderOnwayItemVO.NONWAYMNY, nonwaymny);
  }

  /** 在途数量 setter 方法 */
  public void setNonwaynum(UFDouble nonwaynum) {
    this.setAttributeValue(OrderOnwayItemVO.NONWAYNUM, nonwaynum);
  }

  /** 本币币种 setter 方法 */
  public void setNorigmny(UFDouble norigmny) {
    this.setAttributeValue(OrderOnwayItemVO.NORIGMNY, norigmny);
  }

  /** 主无税净价 setter 方法 */
  public void setNorignetprice(UFDouble norignetprice) {
    this.setAttributeValue(OrderOnwayItemVO.NORIGNETPRICE, norignetprice);
  }

  /** 本次发货数量 setter 方法 */
  public void setNsendoutnum(UFDouble nsendoutnum) {
    this.setAttributeValue(OrderOnwayItemVO.NSENDOUTNUM, nsendoutnum);
  }

  /** 本次发货金额 setter 方法 */
  public void setNstatusmny(UFDouble nstatusmny) {
    this.setAttributeValue(OrderOnwayItemVO.NSTATUSMNY, nstatusmny);
  }

  /** 所属集团 setter 方法 */
  public void setPk_group(String pk_group) {
    this.setAttributeValue(OrderOnwayItemVO.PK_GROUP, pk_group);
  }

  /** 物料版本信息 setter 方法 */
  public void setPk_material(String pk_material) {
    this.setAttributeValue(OrderOnwayItemVO.PK_MATERIAL, pk_material);
  }

  /** 采购订单在途状态 setter 方法 */
  public void setPk_order(String pk_order) {
    this.setAttributeValue(OrderOnwayItemVO.PK_ORDER, pk_order);
  }

  /** 采购订单子表 setter 方法 */
  public void setPk_order_b(String pk_order_b) {
    this.setAttributeValue(OrderOnwayItemVO.PK_ORDER_B, pk_order_b);
  }

  /** 采购订单在途状态 setter 方法 */
  public void setPk_order_bb(String pk_order_bb) {
    this.setAttributeValue(OrderOnwayItemVO.PK_ORDER_BB, pk_order_bb);
  }

  /** 采购组织版本信息 setter 方法 */
  public void setPk_org(String pk_org) {
    this.setAttributeValue(OrderOnwayItemVO.PK_ORG, pk_org);
  }

  /** 采购组织 setter 方法 */
  public void setPk_org_v(String pk_org_v) {
    this.setAttributeValue(OrderOnwayItemVO.PK_ORG_V, pk_org_v);
  }

  /** ts setter 方法 */
  public void setTs(UFDateTime ts) {
    this.setAttributeValue(OrderOnwayItemVO.TS, ts);
  }

  /** 自定义项1 setter 方法 */
  public void setVbdef1(String vbdef1) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF1, vbdef1);
  }

  /** 自定义项10 setter 方法 */
  public void setVbdef10(String vbdef10) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF10, vbdef10);
  }

  /** 自定义项11 setter 方法 */
  public void setVbdef11(String vbdef11) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF11, vbdef11);
  }

  /** 自定义项12 setter 方法 */
  public void setVbdef12(String vbdef12) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF12, vbdef12);
  }

  /** 自定义项13 setter 方法 */
  public void setVbdef13(String vbdef13) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF13, vbdef13);
  }

  /** 自定义项14 setter 方法 */
  public void setVbdef14(String vbdef14) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF14, vbdef14);
  }

  /** 自定义项15 setter 方法 */
  public void setVbdef15(String vbdef15) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF15, vbdef15);
  }

  /** 自定义项16 setter 方法 */
  public void setVbdef16(String vbdef16) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF16, vbdef16);
  }

  /** 自定义项17 setter 方法 */
  public void setVbdef17(String vbdef17) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF17, vbdef17);
  }

  /** 自定义项18 setter 方法 */
  public void setVbdef18(String vbdef18) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF18, vbdef18);
  }

  /** 自定义项19 setter 方法 */
  public void setVbdef19(String vbdef19) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF19, vbdef19);
  }

  /** 自定义项2 setter 方法 */
  public void setVbdef2(String vbdef2) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF2, vbdef2);
  }

  /** 自定义项20 setter 方法 */
  public void setVbdef20(String vbdef20) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF20, vbdef20);
  }

  /** 自定义项21 setter 方法 */
  public void setVbdef21(String vbdef21) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF21, vbdef21);
  }

  /** 自定义项22 setter 方法 */
  public void setVbdef22(String vbdef22) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF22, vbdef22);
  }

  /** 自定义项23 setter 方法 */
  public void setVbdef23(String vbdef23) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF23, vbdef23);
  }

  /** 自定义项24 setter 方法 */
  public void setVbdef24(String vbdef24) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF24, vbdef24);
  }

  /** 自定义项25 setter 方法 */
  public void setVbdef25(String vbdef25) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF25, vbdef25);
  }

  /** 自定义项26 setter 方法 */
  public void setVbdef26(String vbdef26) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF26, vbdef26);
  }

  /** 自定义项27 setter 方法 */
  public void setVbdef27(String vbdef27) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF27, vbdef27);
  }

  /** 自定义项28 setter 方法 */
  public void setVbdef28(String vbdef28) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF28, vbdef28);
  }

  /** 自定义项29 setter 方法 */
  public void setVbdef29(String vbdef29) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF29, vbdef29);
  }

  /** 自定义项3 setter 方法 */
  public void setVbdef3(String vbdef3) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF3, vbdef3);
  }

  /** 自定义项30 setter 方法 */
  public void setVbdef30(String vbdef30) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF30, vbdef30);
  }

  /** 自定义项31 setter 方法 */
  public void setVbdef31(String vbdef31) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF31, vbdef31);
  }

  /** 自定义项32 setter 方法 */
  public void setVbdef32(String vbdef32) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF32, vbdef32);
  }

  /** 自定义项33 setter 方法 */
  public void setVbdef33(String vbdef33) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF33, vbdef33);
  }

  /** 自定义项34 setter 方法 */
  public void setVbdef34(String vbdef34) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF34, vbdef34);
  }

  /** 自定义项35 setter 方法 */
  public void setVbdef35(String vbdef35) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF35, vbdef35);
  }

  /** 自定义项36 setter 方法 */
  public void setVbdef36(String vbdef36) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF36, vbdef36);
  }

  /** 自定义项37 setter 方法 */
  public void setVbdef37(String vbdef37) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF37, vbdef37);
  }

  /** 自定义项38 setter 方法 */
  public void setVbdef38(String vbdef38) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF38, vbdef38);
  }

  /** 自定义项39 setter 方法 */
  public void setVbdef39(String vbdef39) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF39, vbdef39);
  }

  /** 自定义项4 setter 方法 */
  public void setVbdef4(String vbdef4) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF4, vbdef4);
  }

  /** 自定义项40 setter 方法 */
  public void setVbdef40(String vbdef40) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF40, vbdef40);
  }

  /** 自定义项5 setter 方法 */
  public void setVbdef5(String vbdef5) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF5, vbdef5);
  }

  /** 自定义项6 setter 方法 */
  public void setVbdef6(String vbdef6) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF6, vbdef6);
  }

  /** 自定义项7 setter 方法 */
  public void setVbdef7(String vbdef7) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF7, vbdef7);
  }

  /** 自定义项8 setter 方法 */
  public void setVbdef8(String vbdef8) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF8, vbdef8);
  }

  /** 自定义项9 setter 方法 */
  public void setVbdef9(String vbdef9) {
    this.setAttributeValue(OrderOnwayItemVO.VBDEF9, vbdef9);
  }

  /** 单据编号 setter 方法 */
  public void setVbillcode(String vbillcode) {
    this.setAttributeValue(OrderOnwayItemVO.VBILLCODE, vbillcode);
  }
}
