insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JPS',1,-1,null,null,0,1,null,-1,'N',null,-1,'vhashcode',0,'N',1,'N','N',null,0,'vhashcode','ic.OnhandDimVO.vhashcode',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,null,null,null,'N',0,33,'OnhandDimVO','现存量维度',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JPT',1,-1,null,null,0,0,null,-1,'N','cmaterialvid',-1,'cmaterialvid.materialtype',0,'N',1,'N','Y',null,0,'materialtype','uap.material.materialtype',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,null,null,null,'N',1,11,'OnhandDimVO','OnhandDimVO',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JPU',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree5',0,'N',1,'N','N',null,0,'vfree5','ic.OnhandDimVO.vfree5',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,null,null,null,'N',0,29,'OnhandDimVO','现存量维度',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JPV',1,2,'本次数量',null,0,1,null,-1,'N',null,20,'onhandshouldassnum',0,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'1001Z810000000004JPR','@@@@',0,'8,,','24004000-0009',null,'N',1,39,'OnhandDimVO','现存量维度',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JPW',1,0,'行号',null,0,1,null,-1,'N',null,20,'crowno',0,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'1001Z810000000004JPR','@@@@',0,null,'24004000-0010',null,'N',1,3,'OnhandDimVO','现存量维度',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JPX',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree6',0,'N',1,'N','N',null,0,'vfree6','ic.OnhandDimVO.vfree6',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,null,null,null,'N',0,30,'OnhandDimVO','现存量维度',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JPY',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree2',0,'N',1,'N','N',null,0,'vfree2','ic.OnhandDimVO.vfree2',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,null,null,null,'N',0,26,'OnhandDimVO','现存量维度',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JPZ',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree8',0,'N',1,'N','N',null,0,'vfree8','ic.OnhandDimVO.vfree8',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,null,null,null,'N',0,32,'OnhandDimVO','现存量维度',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JQ0',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',null,0,'pk_group','ic.OnhandDimVO.pk_group',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,'集团',null,null,'N',0,2,'OnhandDimVO','现存量维度',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JQ1',1,-1,null,null,0,0,null,-1,'N','cmaterialvid',-1,'cmaterialvid.materialspec',0,'N',1,'N','Y',null,0,'materialspec','uap.material.materialspec',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,null,null,null,'N',1,10,'OnhandDimVO','OnhandDimVO',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JQ2',1,-1,null,null,0,1,null,-1,'N',null,-1,'cwarehouseid',0,'N',1,'N','Y',null,0,'cwarehouseid','ic.OnhandDimVO.cwarehouseid',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,'仓库',null,null,'N',1,5,'OnhandDimVO','现存量维度',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JQ3',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','Y',null,0,'pk_org','ic.OnhandDimVO.pk_org',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,'库存组织',null,null,'N',1,4,'OnhandDimVO','现存量维度',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JQ4',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',null,0,'ts','ic.OnhandDimVO.ts',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,null,null,null,'N',0,35,'OnhandDimVO','现存量维度',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JQ5',1,2,'本次主数量',null,0,1,null,-1,'N',null,20,'onhandshouldnum',0,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'1001Z810000000004JPR','@@@@',0,'8,,','24004000-0011',null,'N',1,38,'OnhandDimVO','现存量维度',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JQ6',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree10',0,'N',1,'N','N',null,0,'vfree10','ic.OnhandDimVO.vfree10',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,null,null,null,'N',0,37,'OnhandDimVO','现存量维度',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JQ7',1,-1,null,null,0,1,null,-1,'N',null,-1,'cproductorid',0,'N',1,'N','N',null,0,'cproductorid','ic.OnhandDimVO.cproductorid',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,'生产厂商(自定义档案)',null,null,'N',0,23,'OnhandDimVO','现存量维度',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JQ8',1,-1,null,null,0,1,null,-1,'N',null,-1,'ctplcustomerid',0,'N',1,'N','N',null,0,'ctplcustomerid','ic.OnhandDimVO.ctplcustomerid',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,'客户档案',null,null,'N',0,19,'OnhandDimVO','现存量维度',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JQ9',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree9',0,'N',1,'N','N',null,0,'vfree9','ic.OnhandDimVO.vfree9',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,null,null,null,'N',0,36,'OnhandDimVO','现存量维度',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JQA',1,-1,null,null,0,1,null,-1,'N',null,-1,'vchangerate',0,'N',1,'N','N',null,0,'vchangerate','ic.OnhandDimVO.vchangerate',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,null,null,null,'N',0,17,'OnhandDimVO','现存量维度',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JQC',1,-1,null,null,0,1,null,-1,'N',null,-1,'cmaterialvid',0,'N',1,'N','N',null,0,'cmaterialvid','ic.OnhandDimVO.cmaterialvid',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,'物料（多版本）,dpc=SCMDefault',null,null,'N',0,7,'OnhandDimVO','现存量维度',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JQD',1,-1,null,null,0,1,null,-1,'N',null,-1,'cvendorid',0,'N',1,'N','N',null,0,'cvendorid','ic.OnhandDimVO.cvendorid',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,'供应商档案',null,null,'N',0,21,'OnhandDimVO','现存量维度',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JQE',1,-1,null,null,0,1,null,-1,'N',null,-1,'clocationid',0,'N',1,'N','N',null,0,'clocationid','ic.OnhandDimVO.clocationid',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,null,null,null,'N',0,6,'OnhandDimVO','现存量维度',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JQF',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_batchcode',0,'N',1,'N','N',null,0,'pk_batchcode','ic.OnhandDimVO.pk_batchcode',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,'批次号档案',null,null,'N',0,15,'OnhandDimVO','现存量维度',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JQG',1,-1,null,null,0,1,null,-1,'N',null,-1,'castunitid',0,'N',1,'N','N',null,0,'castunitid','ic.OnhandDimVO.castunitid',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,'计量单位',null,null,'N',0,14,'OnhandDimVO','现存量维度',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JQH',1,-1,null,null,0,1,null,-1,'N',null,-1,'cprojectid',0,'N',1,'N','N',null,0,'cprojectid','ic.OnhandDimVO.cprojectid',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,'项目',null,null,'N',0,22,'OnhandDimVO','现存量维度',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JQI',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_onhanddim',0,'N',1,'N','N',null,0,'pk_onhanddim','ic.OnhandDimVO.pk_onhanddim',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,null,null,null,'N',0,1,'OnhandDimVO','现存量维度',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JQJ',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree7',0,'N',1,'N','N',null,0,'vfree7','ic.OnhandDimVO.vfree7',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,null,null,null,'N',0,31,'OnhandDimVO','现存量维度',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JQK',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree1',0,'N',1,'N','N',null,0,'vfree1','ic.OnhandDimVO.vfree1',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,null,null,null,'N',0,25,'OnhandDimVO','现存量维度',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JQL',1,-1,null,null,0,1,null,-1,'N',null,-1,'casscustid',0,'N',1,'N','N',null,0,'casscustid','ic.OnhandDimVO.casscustid',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,'客户档案',null,null,'N',0,24,'OnhandDimVO','现存量维度',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JQM',1,-1,null,null,0,1,null,-1,'N',null,-1,'cvmivenderid',0,'N',1,'N','N',null,0,'cvmivenderid','ic.OnhandDimVO.cvmivenderid',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,'供应商档案',null,null,'N',0,18,'OnhandDimVO','现存量维度',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JQN',1,-1,null,null,0,0,null,-1,'N','cmaterialvid',-1,'cmaterialvid.code',0,'N',1,'N','Y',null,0,'code','uap.material.code',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,null,null,null,'N',1,8,'OnhandDimVO','OnhandDimVO',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JQO',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree4',0,'N',1,'N','N',null,0,'vfree4','ic.OnhandDimVO.vfree4',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,null,null,null,'N',0,28,'OnhandDimVO','现存量维度',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JQP',1,-1,null,null,0,1,null,-1,'N',null,-1,'vsubhashcode',0,'N',1,'N','N',null,0,'vsubhashcode','ic.OnhandDimVO.vsubhashcode',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,null,null,null,'N',0,34,'OnhandDimVO','现存量维度',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JQQ',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree3',0,'N',1,'N','N',null,0,'vfree3','ic.OnhandDimVO.vfree3',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,null,null,null,'N',0,27,'OnhandDimVO','现存量维度',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JQR',1,-1,null,null,0,1,null,-1,'N',null,-1,'cmaterialoid',0,'N',1,'N','N',null,0,'cmaterialoid','ic.OnhandDimVO.cmaterialoid',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,'物料档案',null,null,'N',0,13,'OnhandDimVO','现存量维度',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JQS',1,-1,null,null,0,1,null,-1,'N',null,-1,'cstateid',0,'N',1,'N','N',null,0,'cstateid','ic.OnhandDimVO.cstateid',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,'库存状态',null,null,'N',0,20,'OnhandDimVO','现存量维度',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004JQT',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbatchcode',0,'N',1,'N','N',null,0,'vbatchcode','ic.OnhandDimVO.vbatchcode',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,null,null,null,'N',0,16,'OnhandDimVO','现存量维度',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004O7P',1,5,'主单位',null,null,0,null,-1,'N',null,20,'cunitid',0,'N',1,'N','Y',null,0,null,'uap.material_v.pk_measdoc',null,'N',1,null,'1001Z810000000004JPR','@@@@',0,'计量单位','24004000-0012',null,'N',1,12,'OnhandDimVO','现存量维度',0,'2015-05-11 15:18:08','N',null,null,null,1,1,'N',1,null,1,12)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VBP',1,-1,null,null,0,0,null,-1,'N','cmaterialvid',-1,'cmaterialvid.name',null,'N',1,'N','Y',null,0,'name','uap.material.name',null,'N',0,null,'1001Z810000000004JPR',null,0,null,null,null,'N',1,9,'OnhandDimVO','OnhandDimVO',0,'2015-01-09 09:40:27','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000003UIVY',1,-1,null,null,0,1,null,-1,'N',null,-1,'cffileid',0,'N',1,'N','N',null,0,'cffileid','ic.OnhandDimVO.cffileid',null,'N',0,null,'1001Z810000000004JPR','@@@@',0,'特征码档案',null,null,'N',0,41,'OnhandDimVO','OnhandDimVO',0,'2015-04-29 10:31:22','N',null,null,null,1,1,'N',1,null,1,41)
go

