/***************************************************************
 * \ The skeleton of this class is generated by an automatic * code generator
 * for NC product. It is based on Velocity. * \
 ***************************************************************/
package nc.vo.pu.m21transtype.enumeration;

import nc.md.model.IEnumValue;
import nc.md.model.impl.MDEnum;
import nc.md.model.type.IType;
import nc.vo.pubapp.enumeration.NCMDEnum;

/**
 * 请购单生成订单限制方式：不限制、存在供应商有效价格才能生成、经过价格审批才能生成
 * 
 * @author GGR
 * @version v60
 */
public class CreateorderType extends NCMDEnum {
  // 经过价格审批才能生成
  public static final CreateorderType MODE_EXIST_BILL = MDEnum.valueOf(
      CreateorderType.class, Integer.valueOf(2));

  // 存在供应商有效价格才能生成
  public static final CreateorderType MODE_EXIST_PRICE = MDEnum.valueOf(
      CreateorderType.class, Integer.valueOf(1));

  // 不限制
  public static final CreateorderType MODE_NO_CTRL = MDEnum.valueOf(
      CreateorderType.class, Integer.valueOf(0));

  public CreateorderType(IEnumValue enumvalue) {
    super(enumvalue);
  }

  @Override
  public int getReturnType() {
    return IType.TYPE_INT;
  }

  @Override
  public int hashCode() {
    return ((Integer) this.value()).intValue();
  }
}
