insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VBV',1,-1,null,null,0,1,null,-1,'N',null,-1,'castunitid',null,'N',1,'N','Y',null,0,'castunitid','ic.OnhandDimVO.castunitid',null,'N',0,null,'1001Z810000000004VBU',null,0,'计量单位',null,null,'N',1,10,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,10)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VBW',1,-1,null,null,0,0,null,-1,'N','pk_batchcode',-1,'pk_batchcode.dproducedate',null,'N',1,'N','Y',null,0,'dproducedate','ic.BatchcodeVO.dproducedate',null,'N',0,null,'1001Z810000000004VBU',null,0,null,null,null,'N',1,7,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,7)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VBX',1,5,'主单位',null,0,0,null,-1,'N',null,20,'cunitid',0,'N',1,'N','Y',null,0,null,'uap.material_v.pk_measdoc',null,'N',1,null,'1001Z810000000004VBU','@@@@',0,'计量单位','24004000-0012',null,'N',1,12,'pk_org','pk_org',0,'2015-04-20 14:51:21','N',null,null,null,1,1,'N',1,null,1,12)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VBY',1,-1,null,null,0,0,null,-1,'N',null,-1,'cwarehouseid',null,'N',1,'N','N',null,0,'cwarehouseid','ic.OnhandDimVO.cwarehouseid',null,'N',0,null,'1001Z810000000004VBU',null,0,'仓库',null,null,'N',0,3,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VBZ',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org',null,'N',1,'N','N',null,0,'pk_org','ic.OnhandDimVO.pk_org',null,'N',0,null,'1001Z810000000004VBU',null,0,'库存组织',null,null,'N',0,1,'pk_org','库存组织',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VC0',1,-1,null,null,0,0,null,-1,'N',null,-1,'cmaterialvid',null,'N',1,'N','N',null,0,'cmaterialvid','ic.OnhandDimVO.cmaterialvid',null,'N',0,null,'1001Z810000000004VBU',null,0,'物料（多版本）',null,null,'N',0,11,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,11)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VC1',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_batchcode',null,'N',1,'N','N',null,0,'pk_batchcode','ic.OnhandDimVO.pk_batchcode',null,'N',0,null,'1001Z810000000004VBU',null,0,'批次号档案',null,null,'N',0,5,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VC2',1,-1,null,null,0,0,null,-1,'N','pk_batchcode',-1,'pk_batchcode.cqualitylevelid',null,'N',1,'N','Y',null,0,'cqualitylevelid','ic.BatchcodeVO.cqualitylevelid',null,'N',0,null,'1001Z810000000004VBU',null,0,'质量等级(树表)',null,null,'N',1,9,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,9)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VC3',1,-1,null,null,0,0,null,-1,'N','pk_batchcode',-1,'pk_batchcode.dvalidate',null,'N',1,'N','Y',null,0,'dvalidate','ic.BatchcodeVO.dvalidate',null,'N',0,null,'1001Z810000000004VBU',null,0,null,null,null,'N',1,8,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,8)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VC4',1,-1,null,null,0,0,null,-1,'N','pk_batchcode',-1,'pk_batchcode.vbatchcode',null,'N',1,'N','Y',null,0,'vbatchcode','ic.BatchcodeVO.vbatchcode',null,'N',0,null,'1001Z810000000004VBU',null,0,null,null,null,'N',1,6,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VC7',1,2,'结存数量',null,0,0,null,-1,'N',null,20,'nonhandastnum',0,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'1001Z810000000004VBU','@@@@',0,'8,,','24004000-0013',null,'N',1,15,'pk_org','库存组织',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,15)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VC8',1,2,'本次主数量',null,0,1,null,-1,'N',null,20,'nnum',0,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'1001Z810000000004VBU','@@@@',0,'8,,','24004000-0011',null,'N',1,14,'pk_org','库存组织',1,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,14)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VC9',1,2,'本次数量',null,0,1,null,-1,'N',null,20,'nassistnum',0,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'1001Z810000000004VBU','@@@@',0,'8,,','24004000-0009',null,'N',1,13,'pk_org','库存组织',1,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,13)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VCA',1,2,'可用量',null,0,0,null,-1,'N',null,20,'natpnum',0,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'1001Z810000000004VBU','@@@@',0,'8,,','24004000-0014',null,'N',1,17,'pk_org','库存组织',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,17)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VCB',1,2,'结存主数量',null,0,0,null,-1,'N',null,20,'nonhandnum',0,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'1001Z810000000004VBU','@@@@',0,'8,,','24004000-0015',null,'N',1,16,'pk_org','库存组织',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,16)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VCO',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree6',null,'N',1,'N','N',null,0,'vfree6','ic.OnhandDimVO.vfree6',null,'N',0,null,'1001Z810000000004VBU',null,0,null,null,null,'N',0,36,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,36)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VCP',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_group',null,'N',1,'N','N',null,0,'pk_group','ic.OnhandDimVO.pk_group',null,'N',0,null,'1001Z810000000004VBU',null,0,'集团',null,null,'N',0,19,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,19)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VCQ',1,-1,null,null,0,1,null,-1,'N',null,-1,'cproductorid',null,'N',1,'N','N',null,0,'cproductorid','ic.OnhandDimVO.cproductorid',null,'N',0,null,'1001Z810000000004VBU',null,0,'生产厂商(自定义档案)',null,null,'N',0,29,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,29)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VCR',1,-1,null,null,0,1,null,-1,'N',null,-1,'cprojectid',null,'N',1,'N','N',null,0,'cprojectid','ic.OnhandDimVO.cprojectid',null,'N',0,null,'1001Z810000000004VBU',null,0,'项目',null,null,'N',0,28,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,28)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VCS',1,-1,null,null,0,1,null,-1,'N',null,-1,'ctplcustomerid',null,'N',1,'N','N',null,0,'ctplcustomerid','ic.OnhandDimVO.ctplcustomerid',null,'N',0,null,'1001Z810000000004VBU',null,0,'客户档案',null,null,'N',0,25,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,25)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VCT',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree10',null,'N',1,'N','N',null,0,'vfree10','ic.OnhandDimVO.vfree10',null,'N',0,null,'1001Z810000000004VBU',null,0,null,null,null,'N',0,40,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,40)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VCU',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_onhanddim',null,'N',1,'N','N',null,0,'pk_onhanddim','ic.OnhandDimVO.pk_onhanddim',null,'N',0,null,'1001Z810000000004VBU',null,0,null,null,null,'N',0,18,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,18)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VCV',1,-1,null,null,0,1,null,-1,'N',null,-1,'clocationid',null,'N',1,'N','N',null,0,'clocationid','ic.OnhandDimVO.clocationid',null,'N',0,null,'1001Z810000000004VBU',null,0,null,null,null,'N',0,20,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,20)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VCW',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree8',null,'N',1,'N','N',null,0,'vfree8','ic.OnhandDimVO.vfree8',null,'N',0,null,'1001Z810000000004VBU',null,0,null,null,null,'N',0,38,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,38)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VCX',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree1',null,'N',1,'N','N',null,0,'vfree1','ic.OnhandDimVO.vfree1',null,'N',0,null,'1001Z810000000004VBU',null,0,null,null,null,'N',0,31,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,31)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VCY',1,-1,null,null,0,1,null,-1,'N',null,-1,'cstateid',null,'N',1,'N','N',null,0,'cstateid','ic.OnhandDimVO.cstateid',null,'N',0,null,'1001Z810000000004VBU',null,0,'库存状态',null,null,'N',0,26,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,26)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VCZ',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbatchcode',null,'N',1,'N','N',null,0,'vbatchcode','ic.OnhandDimVO.vbatchcode',null,'N',0,null,'1001Z810000000004VBU',null,0,null,null,null,'N',0,22,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,22)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VD0',1,-1,null,null,0,1,null,-1,'N',null,-1,'casscustid',null,'N',1,'N','N',null,0,'casscustid','ic.OnhandDimVO.casscustid',null,'N',0,null,'1001Z810000000004VBU',null,0,'客户档案',null,null,'N',0,30,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,30)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VD1',1,-1,null,null,0,1,null,-1,'N',null,-1,'vchangerate',null,'N',1,'N','N',null,0,'vchangerate','ic.OnhandDimVO.vchangerate',null,'N',0,null,'1001Z810000000004VBU',null,0,null,null,null,'N',0,23,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,23)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VD2',1,-1,null,null,0,1,null,-1,'N',null,-1,'cmaterialoid',null,'N',1,'N','N',null,0,'cmaterialoid','ic.OnhandDimVO.cmaterialoid',null,'N',0,null,'1001Z810000000004VBU',null,0,'物料档案',null,null,'N',0,21,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,21)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VD3',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',null,'N',1,'N','N',null,0,'ts','ic.OnhandDimVO.ts',null,'N',0,null,'1001Z810000000004VBU',null,0,null,null,null,'N',0,43,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,43)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VD4',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree7',null,'N',1,'N','N',null,0,'vfree7','ic.OnhandDimVO.vfree7',null,'N',0,null,'1001Z810000000004VBU',null,0,null,null,null,'N',0,37,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,37)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VD5',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree2',null,'N',1,'N','N',null,0,'vfree2','ic.OnhandDimVO.vfree2',null,'N',0,null,'1001Z810000000004VBU',null,0,null,null,null,'N',0,32,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,32)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VD6',1,-1,null,null,0,1,null,-1,'N',null,-1,'cvmivenderid',null,'N',1,'N','N',null,0,'cvmivenderid','ic.OnhandDimVO.cvmivenderid',null,'N',0,null,'1001Z810000000004VBU',null,0,'供应商档案',null,null,'N',0,24,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,24)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VD7',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree3',null,'N',1,'N','N',null,0,'vfree3','ic.OnhandDimVO.vfree3',null,'N',0,null,'1001Z810000000004VBU',null,0,null,null,null,'N',0,33,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,33)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VD8',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree9',null,'N',1,'N','N',null,0,'vfree9','ic.OnhandDimVO.vfree9',null,'N',0,null,'1001Z810000000004VBU',null,0,null,null,null,'N',0,39,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,39)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VD9',1,-1,null,null,0,1,null,-1,'N',null,-1,'vsubhashcode',null,'N',1,'N','N',null,0,'vsubhashcode','ic.OnhandDimVO.vsubhashcode',null,'N',0,null,'1001Z810000000004VBU',null,0,null,null,null,'N',0,42,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,42)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VDA',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree4',null,'N',1,'N','N',null,0,'vfree4','ic.OnhandDimVO.vfree4',null,'N',0,null,'1001Z810000000004VBU',null,0,null,null,null,'N',0,34,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,34)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VDB',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree5',null,'N',1,'N','N',null,0,'vfree5','ic.OnhandDimVO.vfree5',null,'N',0,null,'1001Z810000000004VBU',null,0,null,null,null,'N',0,35,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,35)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VDC',1,-1,null,null,0,1,null,-1,'N',null,-1,'cvendorid',null,'N',1,'N','N',null,0,'cvendorid','ic.OnhandDimVO.cvendorid',null,'N',0,null,'1001Z810000000004VBU',null,0,'供应商档案',null,null,'N',0,27,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,27)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VDD',1,-1,null,null,0,1,null,-1,'N',null,-1,'vhashcode',null,'N',1,'N','N',null,0,'vhashcode','ic.OnhandDimVO.vhashcode',null,'N',0,null,'1001Z810000000004VBU',null,0,null,null,null,'N',0,41,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,41)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VDE',1,-1,null,null,0,0,null,-1,'N','cwarehouseid',-1,'cwarehouseid.name',0,'N',1,'N','Y',null,0,'name','uap.stordoc.name',null,'N',0,null,'1001Z810000000004VBU','@@@@',0,null,null,null,'N',1,4,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000004VDF',1,-1,null,null,0,0,null,-1,'N','pk_org',-1,'pk_org.name',0,'N',1,'N','Y',null,0,'name','uap.stockorg.name',null,'N',0,null,'1001Z810000000004VBU','@@@@',0,null,null,null,'N',1,2,'pk_org','pk_org',0,'2015-03-31 10:22:42','N',null,null,null,1,1,'N',1,null,1,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000003UIVW',1,-1,null,null,0,1,null,-1,'N',null,-1,'cffileid',0,'N',1,'N','N',null,0,'cffileid','ic.OnhandDimVO.cffileid',null,'N',0,null,'1001Z810000000004VBU','@@@@',0,'特征码档案',null,null,'N',0,44,'pk_org','pk_org',0,'2015-04-29 10:26:09','N',null,null,null,1,1,'N',1,null,1,44)
go

