insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z810000000000BKS',1,-1,null,null,0,1,null,-1,'N',null,-1,'nchecknum',0,'N',1,'N','N',null,0,'nchecknum','pu.po_arriveorder_b.nchecknum',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,null,null,null,'N',0,22,'header','header',1,'2015-02-11 11:00:32','N',null,null,null,1,1,'N',1,null,1,22)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z81000000000MI6Y',1,-1,null,null,0,0,null,-1,'N',null,-1,'csourcebid',0,'N',1,'N','N',null,0,'csourcebid','pu.po_arriveorder_b.csourcebid',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,null,null,null,'N',0,40,'header',null,0,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,40)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z81000000000MI6Z',1,-1,null,null,0,0,null,-1,'N',null,-1,'cfirstbid',0,'N',1,'N','N',null,0,'cfirstbid','pu.po_arriveorder_b.cfirstbid',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,null,null,null,'N',0,31,'header',null,0,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,31)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z81000000000MI70',1,-1,null,null,0,0,null,-1,'N',null,-1,'csourceid',0,'N',1,'N','N',null,0,'csourceid','pu.po_arriveorder_b.csourceid',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,null,null,null,'N',0,34,'header',null,0,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,34)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z81000000000MI71',1,-1,null,null,0,0,null,-1,'N',null,-1,'cfirstid',0,'N',1,'N','N',null,0,'cfirstid','pu.po_arriveorder_b.cfirstid',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,null,null,null,'N',0,38,'header',null,0,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,38)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z81000000001WEYR',1,-1,null,null,0,0,null,-1,'N',null,-1,'nwillnotelignum',0,'N',1,'N','N',null,0,'nwillnotelignum','pu.po_arriveorder_b.nwillnotelignum',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,null,null,null,'N',0,24,'header','header',1,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,24)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('0001Z81000000001WEYS',1,-1,null,null,0,1,null,-1,'N',null,-1,'nwillelignum',0,'N',1,'N','N',null,0,'nwillelignum','pu.po_arriveorder_b.nwillelignum',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,null,null,null,'N',0,23,'header','header',1,'2015-02-11 11:00:32','N',null,null,null,1,1,'N',1,null,1,23)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000007EZU',1,-1,null,null,0,0,null,-1,'N',null,-1,'cqualitylevelid',0,'N',1,'N','N',null,0,'cqualitylevelid','pu.po_arriveorder_b.cqualitylevelid',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,'质量等级',null,null,'N',0,28,'header',null,0,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,28)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000W9AW',1,-1,null,null,0,0,null,-1,'Y',null,-1,'cffileid',0,'N',1,'Y','N',null,0,'cffileid','pu.po_arriveorder_b.cffileid',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,'普通特征码档案',null,null,'N',0,33,'header','header',0,'2015-03-10 11:07:54','N',null,null,null,1,1,'N',1,null,1,33)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000002SEG',1,-1,null,null,0,0,null,-1,'N',null,-1,'dbilldate',0,'N',1,'N','Y',null,0,'dbilldate','pu.po_arriveorder.dbilldate',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,null,null,null,'N',1,8,'header','header',0,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,8)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000002SEH',1,-1,null,null,0,0,null,-1,'N',null,-1,'naccumchecknum',0,'N',1,'N','Y',null,0,'naccumchecknum','pu.po_arriveorder_b.naccumchecknum',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,null,null,null,'N',1,36,'header',null,1,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,36)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000713B',1,-1,null,null,0,0,null,-1,'N',null,-1,'fproductclass',null,'N',1,'N','N',null,0,'fproductclass','pu.po_arriveorder_b.fproductclass',null,'N',0,null,'1002Z81000000000I5JZ',null,0,null,null,null,'N',0,14,'header','header',0,'2015-02-11 11:00:32','N',null,null,null,1,1,'N',1,null,1,14)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000I5K0',1,-1,null,null,0,0,null,-1,'N',null,-1,'csourcetypecode',0,'N',1,'N','N',null,0,'csourcetypecode','pu.po_arriveorder_b.csourcetypecode',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,'影响因素单据类型,code=Y',null,null,'N',0,25,'header',null,0,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,25)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000I5K1',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbatchcode',0,'N',1,'N','Y',null,0,'vbatchcode','pu.po_arriveorder_b.vbatchcode',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,null,null,null,'N',1,16,'header','header',0,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,16)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000I5K2',1,-1,null,null,0,0,null,-1,'N',null,-1,'vchangerate',0,'N',1,'N','N',null,0,'vchangerate','pu.po_arriveorder_b.vchangerate',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,null,null,null,'N',0,21,'header','header',0,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,21)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000I5K3',1,-1,null,null,0,0,null,-1,'N',null,-1,'nnotelignum',0,'N',1,'N','N',null,0,'nnotelignum','pu.po_arriveorder_b.nnotelignum',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,null,null,null,'N',0,26,'header',null,1,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,26)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000I5K4',1,-1,null,null,0,0,null,-1,'N','pk_material',-1,'pk_material.materialspec',0,'N',1,'N','Y',null,0,'materialspec','uap.material.materialspec',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,null,null,null,'N',1,13,'header','header',0,'2015-02-11 11:00:32','N',null,null,null,1,1,'N',1,null,1,13)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000I5K5',1,-1,null,null,0,0,null,-1,'N','pk_material',-1,'pk_material.name',0,'N',1,'N','Y',null,0,'name','uap.material.name',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,null,null,null,'N',1,11,'header','header',0,'2015-02-11 11:00:32','N',null,null,null,1,1,'N',1,null,1,11)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000I5K6',1,-1,null,null,0,0,null,-1,'N',null,-1,'nelignum',0,'N',1,'N','N',null,0,'nelignum','pu.po_arriveorder_b.nelignum',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,null,null,null,'N',0,30,'header',null,1,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,30)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000I5K7',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbillcode',0,'N',1,'N','Y',null,0,'vbillcode','pu.po_arriveorder.vbillcode',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,null,null,null,'N',1,7,'header','header',0,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,7)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000I5K8',1,-1,null,null,0,0,null,-1,'N',null,-1,'cunitid',0,'N',1,'N','N',null,0,'cunitid','pu.po_arriveorder_b.cunitid',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,'计量单位',null,null,'N',0,20,'header','header',0,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,20)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000I5K9',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfirstrowno',0,'N',1,'N','N',null,0,'vfirstrowno','pu.po_arriveorder_b.vfirstrowno',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,null,null,null,'N',0,29,'header',null,0,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,29)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000I5KA',1,-1,'物料编码',null,0,0,null,-1,'Y',null,-1,'pk_material',0,'N',1,'Y','Y',null,0,'pk_material','pu.po_arriveorder_b.pk_material',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,'物料（多版本）','UC000-0002911',null,'N',0,10,'header','header',0,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,10)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000I5KB',1,-1,null,null,0,0,null,-1,'N',null,-1,'crowno',0,'N',1,'N','Y',null,0,'crowno','pu.po_arriveorder_b.crowno',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,null,null,null,'N',1,9,'header','header',0,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,9)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000I5KC',1,-1,null,null,0,0,null,-1,'N',null,-1,'cfirsttypecode',0,'N',1,'N','N',null,0,'cfirsttypecode','pu.po_arriveorder_b.cfirsttypecode',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,'影响因素单据类型,code=Y',null,null,'N',0,41,'header',null,0,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,41)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000I5KD',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org_v',0,'N',1,'N','N',null,0,'pk_org_v','pu.po_arriveorder.pk_org_v',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,'库存组织版本',null,null,'N',0,1,'header','header',0,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000I5KE',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_purchaseorg_v',0,'N',1,'N','N',null,0,'pk_purchaseorg_v','pu.po_arriveorder.pk_purchaseorg_v',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,'采购组织版本',null,null,'N',0,6,'header','header',0,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000I5KF',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_arriveorder',0,'N',1,'N','N',null,0,'pk_arriveorder','pu.po_arriveorder.pk_arriveorder',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,null,null,null,'N',0,3,'header','表头',0,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000I5KG',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_receivestore',0,'N',1,'N','Y',null,0,'pk_receivestore','pu.po_arriveorder_b.pk_receivestore',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,'仓库',null,null,'N',1,37,'header',null,0,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,37)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000I5KH',1,-1,null,null,0,0,null,-1,'Y',null,-1,'vsourcecode',0,'N',1,'Y','N',null,0,'vsourcecode','pu.po_arriveorder_b.vsourcecode',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,null,null,null,'N',0,27,'header',null,0,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,27)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000I5KI',1,-1,null,null,0,0,null,-1,'Y',null,-1,'pk_supplier',0,'N',1,'Y','Y',null,0,'pk_supplier','pu.po_arriveorder.pk_supplier',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,'供应商档案',null,null,'N',1,2,'header','header',0,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000I5KJ',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_purchaseorg',0,'N',1,'N','N',null,0,'pk_purchaseorg','pu.po_arriveorder.pk_purchaseorg',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,'采购组织',null,null,'N',0,5,'header','header',0,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000I5KK',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','Y',null,0,'pk_org','pu.po_arriveorder.pk_org',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,'库存组织',null,null,'N',1,0,'header','header',0,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000I5KL',1,-1,null,null,0,0,null,-1,'Y',null,-1,'vfirstcode',0,'N',1,'Y','N',null,0,'vfirstcode','pu.po_arriveorder_b.vfirstcode',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,null,null,null,'N',0,35,'header',null,0,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,35)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000I5KM',1,-1,null,null,0,0,null,-1,'N',null,-1,'castunitid',0,'N',1,'N','Y',null,0,'castunitid','pu.po_arriveorder_b.castunitid',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,'计量单位',null,null,'N',1,17,'header','header',0,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,17)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000I5KN',1,-1,null,null,0,0,null,-1,'N','pk_material',-1,'pk_material.materialtype',0,'N',1,'N','Y',null,0,'materialtype','uap.material.materialtype',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,null,null,null,'N',1,12,'header','header',0,'2015-02-11 11:00:32','N',null,null,null,1,1,'N',1,null,1,12)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000I5KO',1,-1,null,null,0,0,null,-1,'N',null,-1,'nnum',0,'N',1,'N','N',null,0,'nnum','pu.po_arriveorder_b.nnum',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,null,null,null,'N',0,19,'header','header',1,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,19)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000I5KP',1,-1,null,null,0,0,null,-1,'N',null,-1,'nastnum',0,'N',1,'N','Y',null,0,'nastnum','pu.po_arriveorder_b.nastnum',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,null,null,null,'N',1,18,'header','header',1,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,18)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000I5KQ',1,-1,null,null,0,0,null,-1,'N',null,-1,'vsourcerowno',0,'N',1,'N','N',null,0,'vsourcerowno','pu.po_arriveorder_b.vsourcerowno',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,null,null,null,'N',0,39,'header',null,0,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,39)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000I5KR',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_batchcode',0,'N',1,'N','N',null,0,'pk_batchcode','pu.po_arriveorder_b.pk_batchcode',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,null,null,null,'N',0,15,'header','header',0,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,15)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000I5KS',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',null,0,'pk_group','pu.po_arriveorder.pk_group',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,'集团',null,null,'N',0,4,'header','header',0,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000I5KT',1,-1,null,null,0,0,null,-1,'N',null,-1,'cprojectid',0,'N',1,'N','N',null,0,'cprojectid','pu.po_arriveorder_b.cprojectid',null,'N',0,null,'1002Z81000000000I5JZ','@@@@',0,'项目',null,null,'N',0,32,'header',null,0,'2015-02-11 11:00:32','N',null,null,null,0,1,'N',1,null,1,32)
go

