insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041U4',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree2',null,'N',1,'N','N',null,0,'vfree2','ic.OnhandDimVO.vfree2',null,'N',0,null,'1006Z8100000000041U3',null,0,null,null,null,'N',0,25,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,25)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041U5',1,-1,null,null,0,1,null,-1,'N',null,-1,'ctplcustomerid',null,'N',1,'N','N',null,0,'ctplcustomerid','ic.OnhandDimVO.ctplcustomerid',null,'N',0,null,'1006Z8100000000041U3',null,0,'客户档案',null,null,'N',0,18,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,18)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041U6',1,-1,null,null,0,1,null,-1,'N',null,-1,'vhashcode',null,'N',1,'N','N',null,0,'vhashcode','ic.OnhandDimVO.vhashcode',null,'N',0,null,'1006Z8100000000041U3',null,0,null,null,null,'N',0,34,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,34)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041U7',1,-1,null,null,0,1,null,-1,'N',null,-1,'castunitid',null,'N',1,'N','Y',null,0,'castunitid','ic.OnhandDimVO.castunitid',null,'N',0,null,'1006Z8100000000041U3',null,0,'计量单位',null,null,'N',1,13,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,13)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041U8',1,-1,null,null,0,1,null,-1,'N',null,-1,'cffileid',null,'N',1,'N','Y',null,0,'cffileid','ic.OnhandDimVO.cffileid',null,'N',0,null,'1006Z8100000000041U3',null,0,'特征码档案',null,null,'N',1,36,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,36)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041U9',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_onhanddim',null,'N',1,'N','N',null,0,'pk_onhanddim','ic.OnhandDimVO.pk_onhanddim',null,'N',0,null,'1006Z8100000000041U3',null,0,null,null,null,'N',0,1,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041UA',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree9',null,'N',1,'N','N',null,0,'vfree9','ic.OnhandDimVO.vfree9',null,'N',0,null,'1006Z8100000000041U3',null,0,null,null,null,'N',0,32,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,32)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041UB',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree7',null,'N',1,'N','N',null,0,'vfree7','ic.OnhandDimVO.vfree7',null,'N',0,null,'1006Z8100000000041U3',null,0,null,null,null,'N',0,30,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,30)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041UC',1,-1,null,null,0,1,null,-1,'N',null,-1,'cstateid',null,'N',1,'N','N',null,0,'cstateid','ic.OnhandDimVO.cstateid',null,'N',0,null,'1006Z8100000000041U3',null,0,'库存状态',null,null,'N',0,19,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,19)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041UD',1,-1,null,null,0,1,null,-1,'N',null,-1,'vchangerate',null,'N',1,'N','N',null,0,'vchangerate','ic.OnhandDimVO.vchangerate',null,'N',0,null,'1006Z8100000000041U3',null,0,null,null,null,'N',0,16,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,16)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041UE',1,-1,null,null,0,1,null,-1,'N',null,-1,'casscustid',null,'N',1,'N','N',null,0,'casscustid','ic.OnhandDimVO.casscustid',null,'N',0,null,'1006Z8100000000041U3',null,0,'客户档案',null,null,'N',0,23,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,23)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041UF',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_batchcode',null,'N',1,'N','N',null,0,'pk_batchcode','ic.OnhandDimVO.pk_batchcode',null,'N',0,null,'1006Z8100000000041U3',null,0,'批次号档案',null,null,'N',0,14,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,14)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041UG',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree10',null,'N',1,'N','N',null,0,'vfree10','ic.OnhandDimVO.vfree10',null,'N',0,null,'1006Z8100000000041U3',null,0,null,null,null,'N',0,33,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,33)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041UH',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree1',null,'N',1,'N','N',null,0,'vfree1','ic.OnhandDimVO.vfree1',null,'N',0,null,'1006Z8100000000041U3',null,0,null,null,null,'N',0,24,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,24)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041UI',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree8',null,'N',1,'N','N',null,0,'vfree8','ic.OnhandDimVO.vfree8',null,'N',0,null,'1006Z8100000000041U3',null,0,null,null,null,'N',0,31,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,31)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041UJ',1,-1,null,null,0,1,null,-1,'N',null,-1,'cvmivenderid',null,'N',1,'N','N',null,0,'cvmivenderid','ic.OnhandDimVO.cvmivenderid',null,'N',0,null,'1006Z8100000000041U3',null,0,'供应商档案',null,null,'N',0,17,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,17)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041UK',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree3',null,'N',1,'N','N',null,0,'vfree3','ic.OnhandDimVO.vfree3',null,'N',0,null,'1006Z8100000000041U3',null,0,null,null,null,'N',0,26,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,26)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041UL',1,0,'行号',null,0,1,null,-1,'N',null,20,'crowno',null,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'1006Z8100000000041U3',null,0,null,'24004000-0010',null,'N',1,3,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041UM',1,-1,null,null,0,1,null,-1,'N',null,-1,'vsubhashcode',null,'N',1,'N','N',null,0,'vsubhashcode','ic.OnhandDimVO.vsubhashcode',null,'N',0,null,'1006Z8100000000041U3',null,0,null,null,null,'N',0,35,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,35)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041UN',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbatchcode',null,'N',1,'N','N',null,0,'vbatchcode','ic.OnhandDimVO.vbatchcode',null,'N',0,null,'1006Z8100000000041U3',null,0,null,null,null,'N',0,15,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,15)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041UO',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org',null,'N',1,'N','Y',null,0,'pk_org','ic.OnhandDimVO.pk_org',null,'N',0,null,'1006Z8100000000041U3',null,0,'库存组织',null,null,'N',1,4,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041UP',1,-1,null,null,0,1,null,-1,'N',null,-1,'cvendorid',null,'N',1,'N','N',null,0,'cvendorid','ic.OnhandDimVO.cvendorid',null,'N',0,null,'1006Z8100000000041U3',null,0,'供应商档案',null,null,'N',0,20,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,20)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041UQ',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',null,'N',1,'N','N',null,0,'ts','ic.OnhandDimVO.ts',null,'N',0,null,'1006Z8100000000041U3',null,0,null,null,null,'N',0,37,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,37)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041UR',1,-1,null,null,0,1,null,-1,'N',null,-1,'cproductorid',null,'N',1,'N','N',null,0,'cproductorid','ic.OnhandDimVO.cproductorid',null,'N',0,null,'1006Z8100000000041U3',null,0,'生产厂商(自定义档案)',null,null,'N',0,22,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,22)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041US',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree5',null,'N',1,'N','N',null,0,'vfree5','ic.OnhandDimVO.vfree5',null,'N',0,null,'1006Z8100000000041U3',null,0,null,null,null,'N',0,28,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,28)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041UT',1,-1,null,null,0,1,null,-1,'N',null,-1,'cprojectid',null,'N',1,'N','N',null,0,'cprojectid','ic.OnhandDimVO.cprojectid',null,'N',0,null,'1006Z8100000000041U3',null,0,'项目',null,null,'N',0,21,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,21)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041UU',1,-1,null,null,0,1,null,-1,'N',null,-1,'clocationid',null,'N',1,'N','N',null,0,'clocationid','ic.OnhandDimVO.clocationid',null,'N',0,null,'1006Z8100000000041U3',null,0,null,null,null,'N',0,6,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041UV',1,-1,null,null,0,1,null,-1,'N',null,-1,'cwarehouseid',null,'N',1,'N','Y',null,0,'cwarehouseid','ic.OnhandDimVO.cwarehouseid',null,'N',0,null,'1006Z8100000000041U3',null,0,'仓库',null,null,'N',1,5,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041UW',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree4',null,'N',1,'N','N',null,0,'vfree4','ic.OnhandDimVO.vfree4',null,'N',0,null,'1006Z8100000000041U3',null,0,null,null,null,'N',0,27,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,27)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041UX',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree6',null,'N',1,'N','N',null,0,'vfree6','ic.OnhandDimVO.vfree6',null,'N',0,null,'1006Z8100000000041U3',null,0,null,null,null,'N',0,29,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,29)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041UY',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_group',null,'N',1,'N','N',null,0,'pk_group','ic.OnhandDimVO.pk_group',null,'N',0,null,'1006Z8100000000041U3',null,0,'集团',null,null,'N',0,2,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041UZ',1,-1,null,null,0,1,null,-1,'N',null,-1,'cmaterialvid',null,'N',1,'N','Y',null,0,'cmaterialvid','ic.OnhandDimVO.cmaterialvid',null,'N',0,null,'1006Z8100000000041U3',null,0,'物料（多版本）,code=Y',null,null,'N',1,7,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,7)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041V0',1,-1,null,null,0,1,null,-1,'N',null,-1,'cmaterialoid',null,'N',1,'N','Y',null,0,'cmaterialoid','ic.OnhandDimVO.cmaterialoid',null,'N',0,null,'1006Z8100000000041U3',null,0,'物料档案',null,null,'N',1,12,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,12)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041V2',1,2,'本次主数量',null,0,1,null,-1,'N',null,20,'onhandshouldnum',0,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'1006Z8100000000041U3','@@@@',0,'8,,','24004000-0011',null,'N',1,39,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,39)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041V3',1,-1,null,null,0,0,null,-1,'N','cmaterialvid',-1,'cmaterialvid.materialspec',0,'N',1,'N','Y',null,0,'materialspec','uap.material.materialspec',null,'N',0,null,'1006Z8100000000041U3','@@@@',0,null,null,null,'N',1,9,'OnhandDimVO','OnhandDimVO',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,9)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041V4',1,-1,null,null,0,0,null,-1,'N','cmaterialvid',-1,'cmaterialvid.name',0,'N',1,'N','Y',null,0,'name','uap.material.name',null,'N',0,null,'1006Z8100000000041U3','@@@@',0,null,null,null,'N',1,8,'OnhandDimVO','OnhandDimVO',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,8)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041V5',1,5,'主单位',null,null,0,null,-1,'N',null,20,'cunitid',0,'N',1,'N','Y',null,0,null,'uap.material_v.pk_measdoc',null,'N',1,null,'1006Z8100000000041U3','@@@@',0,'计量单位','24004000-0012',null,'N',1,11,'OnhandDimVO','现存量维度',0,'2015-05-11 15:19:09','N',null,null,null,1,1,'N',1,null,1,11)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041V6',1,-1,null,null,0,0,null,-1,'N','cmaterialvid',-1,'cmaterialvid.materialtype',0,'N',1,'N','Y',null,0,'materialtype','uap.material.materialtype',null,'N',0,null,'1006Z8100000000041U3','@@@@',0,null,null,null,'N',1,10,'OnhandDimVO','OnhandDimVO',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,10)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1006Z8100000000041V8',1,2,'本次数量',null,0,1,null,-1,'N',null,20,'onhandshouldassnum',0,'N',1,'N','Y',null,0,null,null,null,'N',0,null,'1006Z8100000000041U3','@@@@',0,'8,,','24004000-0009',null,'N',1,38,'OnhandDimVO','现存量维度',0,'2015-02-11 11:11:24','N',null,null,null,1,1,'N',1,null,1,38)
go

