insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8100000000001JL',1,2,'成本要素3',null,0,0,null,-1,'N',null,20,'ncostfactor3',0,'N',1,null,'Y',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',0,'2','UC000-0001965',null,'N',1,41,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,1,1,'N',1,null,1,41)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8100000000001JM',1,2,'成本要素2',null,0,0,null,-1,'N',null,20,'ncostfactor2',0,'N',1,null,'Y',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',0,'2','UC000-0001964',null,'N',1,40,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,1,1,'N',1,null,1,40)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8100000000001JN',1,2,'成本要素5',null,0,0,null,-1,'N',null,20,'ncostfactor5',0,'N',1,null,'Y',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',0,'2','UC000-0001967',null,'N',1,43,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,43)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8100000000001JO',1,2,'成本要素4',null,0,0,null,-1,'N',null,20,'ncostfactor4',0,'N',1,null,'Y',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',0,'2','UC000-0001966',null,'N',1,42,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,42)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000CBOB',1,0,'本位币',null,0,0,null,-1,'N',null,20,'ccurrencyid',0,'N',1,null,'N',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',1,null,'1400414001011',null,'N',0,1,'body','表体',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,100,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000CBOC',1,0,'本位币',null,0,0,null,-1,'N',null,20,'ccurrencyid',0,'N',1,null,'N',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',0,null,'1400414001011',null,'N',0,4,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000DV89',1,0,'自由辅助属性3',null,0,0,null,-1,'N',null,20,'vfree3',null,'N',1,null,'N',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK',null,0,null,'1400414001002',null,'N',0,15,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,15)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000DV8A',1,0,'自由辅助属性8',null,0,0,null,-1,'N',null,20,'vfree8',null,'N',1,null,'N',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK',null,0,null,'1400414001007',null,'N',0,20,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,20)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000DV8B',1,0,'自由辅助属性6',null,0,0,null,-1,'N',null,20,'vfree6',null,'N',1,null,'N',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK',null,0,null,'1400414001005',null,'N',0,18,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,18)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000DV8C',1,0,'自由辅助属性10',null,0,0,null,-1,'N',null,20,'vfree10',null,'N',1,null,'N',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK',null,0,null,'1400414001009',null,'N',0,22,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,22)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000DV8D',1,0,'自由辅助属性9',null,0,0,null,-1,'N',null,20,'vfree9',null,'N',1,null,'N',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK',null,0,null,'1400414001008',null,'N',0,21,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,21)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000DV8F',1,0,'自由辅助属性5',null,0,0,null,-1,'N',null,20,'vfree5',null,'N',1,null,'N',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK',null,0,null,'1400414001004',null,'N',0,17,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,17)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000DV8G',1,0,'自由辅助属性4',null,0,0,null,-1,'N',null,20,'vfree4',null,'N',1,null,'N',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK',null,0,null,'1400414001003',null,'N',0,16,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,16)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000DV8H',1,0,'生产厂商',null,0,0,null,-1,'N',null,20,'cproductorid',null,'N',1,null,'N',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK',null,0,null,'UC000-0002929',null,'N',0,11,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,11)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000DV8I',1,0,'自由辅助属性2',null,0,0,null,-1,'N',null,20,'vfree2',null,'N',1,null,'N',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK',null,0,null,'1400414001001',null,'N',0,14,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,14)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000DV8J',1,0,'自由辅助属性7',null,0,0,null,-1,'N',null,20,'vfree7',null,'N',1,null,'N',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK',null,0,null,'1400414001006',null,'N',0,19,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,19)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000DV8K',1,0,'项目',null,0,0,null,-1,'N',null,20,'cprojectid',null,'N',1,null,'N',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK',null,0,null,'UC000-0004165',null,'N',0,12,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,12)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000DV8M',1,0,'自由辅助属性1',null,0,0,null,-1,'N',null,20,'vfree1',null,'N',1,null,'N',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK',null,0,null,'1400414001000',null,'N',0,13,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,13)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8SCM40040001445',1,0,'单据类型',null,0,0,null,-1,'N',null,20,'ctrantypeid',null,'N',1,null,'N',null,0,'ctrantypeid',null,'vtrantypecode=pk_billtypecode','N',0,null,'1002Z810000000001XOK',null,0,'影响因素交 易类型','UC000-0000807',null,'N',0,2,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001S1L',1,0,'是否发票',null,0,0,null,-1,'N',null,20,'binvoice',null,'N',1,null,'N',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK',null,0,null,'1400414000017',null,'N',0,47,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,0,'N',0,null,1,47)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001S1M',1,0,'是否入库单',null,0,0,null,-1,'N',null,20,'bstock',null,'N',1,null,'N',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK',null,0,null,'1400414000022',null,'N',0,48,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,0,'N',0,null,1,48)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001XOL',1,0,'单据类型',null,0,0,null,-1,'N',null,20,'vtrantypecode',null,'N',1,null,'N',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK',null,0,null,'UC000-0000807',null,'N',0,2,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001XON',1,0,'物料ID',null,0,0,null,-1,'Y',null,20,'pk_material',null,'N',1,'Y','N',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK',null,0,null,'1400414000001',null,'N',0,5,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001XOO',1,2,'未结算数量',null,0,0,null,-1,'N',null,20,'ncansettlenum',null,'N',1,null,'Y',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',0,'2','1400414000018',null,'N',1,24,'main','表头',1,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,24)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001XOP',1,0,'主单位',null,0,0,null,-1,'N',null,20,'cunitid',null,'N',1,null,'N',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK',null,0,null,'1400414001010',null,'N',0,8,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,8)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001XOQ',1,2,'单价',null,0,0,null,-1,'N',null,20,'nprice',null,'N',1,null,'Y',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',0,'2','UC000-0000741',null,'N',1,25,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,25)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001XOS',1,0,'物料编码',null,0,0,null,-1,'Y',null,20,'materialcode',null,'N',1,'Y','Y',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK',null,0,null,'UC000-0002911',null,'N',1,6,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001XOT',1,2,'入库数量',null,0,0,null,-1,'N',null,20,'nstockinnum',null,'N',1,null,'Y',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',0,'2','UC000-0000377',null,'N',1,23,'main','表头',1,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,23)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001XOU',1,0,'单据号',null,0,0,null,-1,'N',null,20,'billcode',null,'N',1,null,'Y',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK',null,0,null,'UC000-0000814',null,'N',1,3,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001XOV',1,0,'批次号',null,0,0,null,-1,'N',null,20,'vbatchcode',null,'N',1,null,'N',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK',null,0,null,'UC000-0002060',null,'N',0,10,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,10)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001XOX',1,2,'折扣',null,0,0,null,-1,'N',null,20,'ndiscount',null,'N',1,null,'Y',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',0,'2','UC000-0002087',null,'N',1,38,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,38)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001XOY',1,2,'未暂估已结算数量',null,0,0,null,-1,'N',null,20,'nnoestsettlenum',null,'N',1,null,'N',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',0,'2','1400414000004',null,'N',0,30,'main','表头',1,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,30)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001XOZ',1,2,'成本要素1',null,0,0,null,-1,'N',null,20,'ncostfactor1',null,'N',1,null,'Y',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',0,'2','UC000-0001963',null,'N',1,39,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,39)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001XP0',1,2,'合理损耗数量',null,0,1,null,-1,'N',null,20,'nreasonwastenum',null,'N',1,null,'Y',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',0,'2','UC000-0001145',null,'N',1,37,'main','表头',1,'2011-05-04 09:54:31','N',null,null,null,1,1,'N',1,null,1,37)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001XP1',1,2,'暂估金额',null,0,0,null,-1,'N',null,20,'nestmny',null,'N',1,null,'N',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',0,'2','UC000-0002455',null,'N',0,35,'main','表头',1,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,35)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001XP2',1,2,'本次入库结算数量',null,0,1,null,-1,'N',null,20,'ncurstocksettlenum',null,'N',1,null,'Y',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',0,'2','1400414000033',null,'N',1,27,'main','表头',1,'2011-05-04 09:54:31','N',null,null,null,1,1,'N',1,null,1,27)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001XP3',1,2,'结算平均单价',null,0,0,null,-1,'N',null,20,'nsettleavgprice',null,'N',1,null,'N',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',0,'2','1400414000005',null,'N',0,31,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,31)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001XP4',1,2,'未结算金额',null,0,0,null,-1,'N',null,20,'ncansettlemny',null,'N',1,null,'Y',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',0,'2','1400414000003',null,'N',1,26,'main','表头',1,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,26)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001XP5',1,2,'未暂估已结算金额',null,0,0,null,-1,'N',null,20,'nnoestsettlemny',null,'N',1,null,'N',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',0,'2','1400414000032',null,'N',0,32,'main','表头',1,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,32)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001XP6',1,2,'暂估单价',null,0,0,null,-1,'N',null,20,'nestprice',null,'N',1,null,'N',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',0,'2','UC000-0002453',null,'N',0,34,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,34)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001XP7',1,2,'暂估数量',null,0,0,null,-1,'N',null,20,'nestnum',null,'N',1,null,'N',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',0,'2','1400414000028',null,'N',0,33,'main','表头',1,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,33)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001XP8',1,2,'本次发票结算数量',null,0,1,null,-1,'N',null,20,'ncurinvoicesettlenum',null,'N',1,null,'Y',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',0,'2','1400414000029',null,'N',1,28,'main','表头',1,'2011-05-04 09:54:31','N',null,null,null,1,1,'Y',1,null,1,28)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001XP9',1,2,'本次发票结算金额',null,0,0,null,-1,'N',null,20,'ncurinvoicesettlemny',null,'N',1,null,'Y',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',0,'2','1400414000006',null,'N',1,29,'main','表头',1,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,29)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001XPA',1,2,'本次结算金额',null,0,0,null,-1,'N',null,20,'ncurseetlemny',null,'N',1,null,'Y',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',0,'2','1400414000030',null,'N',1,36,'main','表头',1,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,36)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z8100000000020J7',1,0,'物料名称',null,0,0,null,-1,'N',null,20,'material_name',0,'N',1,null,'Y','material_name->getmlcvalue("bd_material","name","pk_material",pk_material);materialcode->getColValue(bd_material,code,pk_material,pk_material);',0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',0,null,'UC000-0002908',null,'N',1,7,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,7)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z8100000000025XL',1,0,'单据类型',null,0,0,null,-1,'N',null,20,'vtrantypename',null,'N',1,null,'Y','billtypecode->getColValue(bd_billtype,parentbilltype,pk_billtypecode,vtrantypecode);vtrantypename->getmlcvalue("bd_billtype","billtypename","pk_billtypecode",billtypecode);',0,null,null,null,'N',0,null,'1002Z810000000001XOK',null,0,null,'UC000-0000807',null,'N',1,1,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,0,'N',0,null,1,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z8100000000025XN',1,0,'主单位',null,0,0,null,-1,'N',null,20,'cunitname',null,'N',1,null,'Y','cunitname->getmlcvalue("bd_measdoc","name","pk_measdoc",cunitid)',0,null,null,null,'N',0,null,'1002Z810000000001XOK',null,0,null,'1400414001010',null,'N',1,9,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,9)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000GMRR',1,0,'成本要素ID',null,0,0,null,-1,'N',null,20,'pk_costfactor',null,'N',1,null,'N',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK',null,1,null,'1400414000013',null,'N',0,2,'body','表体',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,100,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000GMRS',1,0,'成本要素',null,0,0,null,-1,'N',null,20,'costfactorname',null,'N',1,null,'Y','costfactorname->getmlcvalue("po_costfactor","vfactorname","pk_costfactor",pk_costfactor)',0,null,null,null,'N',0,null,'1002Z810000000001XOK',null,1,null,'1400414000002',null,'N',1,3,'body','表体',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,100,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000GMRX',1,0,'费用项VID',null,0,0,null,-1,'Y',null,20,'pk_material',null,'N',1,'Y','N',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK',null,1,null,'1400414000014',null,'N',0,7,'body','表体',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,100,7)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000GMRY',1,0,'费用项OID',null,0,0,null,-1,'N',null,20,'pk_srcmaterial',null,'N',1,null,'N',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK',null,1,null,'1400414000019',null,'N',0,8,'body','表体',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,100,8)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000GMRZ',1,0,'费用编码',null,0,0,null,-1,'N',null,20,'materialcode',null,'N',1,null,'Y',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK',null,1,null,'UC000-0003868',null,'N',1,9,'body','表体',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,100,9)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000GMS0',1,0,'费用名称',null,0,0,null,-1,'N',null,20,'materialname',null,'N',1,null,'Y','materialname->getmlcvalue("bd_material","name","pk_material",pk_material);materialcode->getColValue(bd_material,code,pk_material,pk_material);',0,null,null,null,'N',0,null,'1002Z810000000001XOK',null,1,null,'UC000-0003865',null,'N',1,10,'body','表体',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,100,10)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000GMSE',1,2,'未结算金额',null,0,0,null,-1,'N',null,20,'ncansettlemny',null,'N',1,null,'Y',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',1,null,'1400414000003',null,'N',1,12,'body','表体',1,'2011-11-23 11:54:32','N',null,null,null,0,1,'N',1,null,100,12)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000GMSF',1,2,'金额',null,0,0,null,-1,'N',null,20,'nmny',null,'N',1,null,'Y',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',1,null,'UC000-0004112',null,'N',1,11,'body','表体',1,'2011-11-23 11:54:32','N',null,null,null,0,1,'N',1,null,100,11)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000GMSG',1,2,'结算金额',null,0,1,null,-1,'N',null,20,'ncurrentinvoicesettlemny',null,'N',1,null,'Y',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',1,null,'UC000-0003259',null,'N',1,13,'body','表体',1,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,100,13)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000GMSH',1,6,'分摊方式',null,0,0,null,-1,'N',null,20,'fapportionmode',null,'N',1,null,'Y',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK',null,1,'IX,按数量=0,按金额=1,按重量=2,按体积=3','1400414000020',null,'N',1,14,'body','表体',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,100,14)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000J5TH',1,0,'发票号',null,0,0,null,-1,'N',null,20,'vbillcode',0,'N',1,null,'Y',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',1,null,'UC000-0000981',null,'N',1,4,'body','表体',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,100,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000J5TI',1,5,'供应商ID',null,0,0,null,-1,'Y',null,20,'pk_supplier',0,'N',1,'Y','N',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',1,'供应商档案','UC000-0000278',null,'N',0,5,'body','表体',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,100,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000J7CZ',1,0,'供应商',null,0,0,null,-1,'Y',null,20,'suppliername',null,'N',1,'Y','Y','suppliername->getmlcvalue("bd_supplier","name","pk_supplier",pk_supplier);',0,null,null,null,'N',0,null,'1002Z810000000001XOK',null,1,null,'UC000-0000275',null,'N',1,6,'body','表体',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,100,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OQFL',0,0,'pk_billbid',null,0,0,null,-1,'N',null,20,'pk_billbid',0,'N',1,null,'N',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',0,null,'1400414000052',null,'N',0,49,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,0,'N',0,null,1,49)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000OQFM',0,0,'pk_billid',null,0,0,null,-1,'N',null,20,'pk_billid',0,'N',1,null,'N',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',0,null,'1400414000053',null,'N',0,50,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,0,'N',0,null,1,50)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000018MHG',1,0,'发票行ID',null,0,0,null,-1,'N',null,20,'pk_invoice_b',0,'N',1,null,'N',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',1,null,'UC000-0000992',null,'N',0,16,'body','表体',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,100,16)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000018MHH',1,0,'发票ID',null,0,0,null,-1,'Y',null,20,'pk_invoice',0,'N',1,'Y','N',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',1,null,'UC000-0000979',null,'N',0,15,'body','表体',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,100,15)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z81000000000222P',1,2,'成本要素6',null,0,0,null,-1,'N',null,20,'ncostfactor6',null,'N',1,null,'Y',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',0,'2','1400414000023',null,'N',1,44,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,44)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z81000000000222Q',1,2,'成本要素8',null,0,0,null,-1,'N',null,20,'ncostfactor8',null,'N',1,null,'Y',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',0,'2','1400414000008',null,'N',1,46,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,46)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z81000000000222R',1,2,'成本要素7',null,0,0,null,-1,'N',null,20,'ncostfactor7',null,'N',1,null,'Y',null,0,null,null,null,'N',0,null,'1002Z810000000001XOK','@@@@',0,'2','1400414000007',null,'N',1,45,'main','表头',0,'2011-05-04 09:54:31','N',null,null,null,0,1,'N',1,null,1,45)
go

