insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8yrTranTypeC2FA',1,-1,null,null,0,1,null,-1,'N',null,-1,'ctrantypeid',null,'N',1,'N','N',null,0,'ctrantypeid','pu.po_buyrtrantype.ctrantypeid','vtrantypecode=pk_billtypecode','N',0,null,'1001Z8PoBuyrTranType',null,0,null,null,null,'N',0,6,'po_buyrtrantype','请购单交易类型',0,'2014-11-14 16:38:24','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8yrTranTypeC2FB',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',null,'N',1,'N','N',null,0,'pk_group','pu.po_buyrtrantype.pk_group',null,'N',0,null,'1001Z8PoBuyrTranType',null,0,'集团',null,null,'N',0,5,'po_buyrtrantype','请购单交易类型',0,'2014-11-14 16:38:24','N',null,null,null,0,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8yrTranTypeC2FC',1,-1,null,null,0,1,null,-1,'N',null,-1,'vtrantypecode',null,'N',1,'N','N',null,0,'vtrantypecode','pu.po_buyrtrantype.vtrantypecode',null,'N',0,null,'1001Z8PoBuyrTranType',null,0,null,null,null,'N',0,6,'po_buyrtrantype','请购单交易类型',0,'2014-11-14 16:38:24','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8yrTranTypeC2FD',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_buyrtrantype',null,'N',1,'N','N',null,0,'pk_buyrtrantype','pu.po_buyrtrantype.pk_buyrtrantype',null,'N',0,null,'1001Z8PoBuyrTranType',null,0,null,null,null,'N',0,1,'po_buyrtrantype','请购单交易类型',0,'2014-11-14 16:38:24','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8yrTranTypeC2FG',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bneedarrange',null,'N',1,'N','Y',null,0,'bneedarrange','pu.po_buyrtrantype.bneedarrange',null,'N',0,null,'1001Z8PoBuyrTranType',null,0,null,null,null,'N',1,4,'po_buyrtrantype','请购单交易类型',0,'2014-11-14 16:38:24','N',null,null,null,1,1,'N',1,null,1,0)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8yrTranTypeC2FH',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',null,'N',1,'N','N',null,0,'ts','pu.po_buyrtrantype.ts',null,'N',0,null,'1001Z8PoBuyrTranType',null,0,null,null,null,'N',0,7,'po_buyrtrantype','请购单交易类型',0,'2014-11-14 16:38:24','N',null,null,null,1,1,'N',1,null,1,0)
go

