insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000000IIR',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_order',0,'N',1,'N','N',null,0,'pk_order','pu.po_order.pk_order',null,'N',0,null,'1001Z81000000000B3OZ','@@@@',1,null,null,null,'N',0,29,'body','body',0,'2013-01-21 10:25:10','N',null,null,null,0,1,'N',1,null,100,29)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000B3P0',1,-1,null,null,0,1,null,-1,'N',null,-1,'denddate',0,'N',1,'N','Y',null,0,'denddate','pu.po_order_payplan.denddate',null,'N',0,null,'1001Z81000000000B3OZ','@@@@',1,null,null,null,'N',1,12,'body','付款计划',0,'2013-01-21 10:25:10','N',null,null,null,1,1,'N',1,null,100,12)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000B3P1',1,-1,null,null,0,1,null,-1,'N',null,-1,'bpreflag',0,'N',1,'N','Y',null,0,'bpreflag','pu.po_order_payplan.bpreflag',null,'N',0,null,'1001Z81000000000B3OZ','@@@@',1,null,null,null,'N',1,13,'body','付款计划',0,'2013-01-21 10:25:10','N',null,null,null,1,1,'N',1,null,100,13)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000B3P2',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',null,0,'ts','pu.po_order_payplan.ts',null,'N',0,null,'1001Z81000000000B3OZ','@@@@',1,null,null,null,'N',0,28,'body','付款计划',0,'2013-01-21 10:25:10','N',null,null,null,1,1,'N',1,null,100,28)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000B3P3',1,-1,null,null,0,0,null,-1,'N',null,-1,'ntotalorigmny',0,'N',1,'N','N',null,0,'ntotalorigmny','pu.po_order_payplan.ntotalorigmny',null,'N',0,null,'1001Z81000000000B3OZ','@@@@',1,null,null,null,'N',0,26,'body','付款计划',1,'2013-01-21 10:25:10','N',null,null,null,0,1,'N',1,null,100,26)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000B3P6',1,-1,'比率%',null,0,1,null,-1,'N',null,-1,'nrate',0,'N',1,'N','Y',null,0,'nrate','pu.po_order_payplan.nrate',null,'N',0,null,'1001Z81000000000B3OZ','@@@@',1,null,'1400404070003',null,'N',1,14,'body','付款计划',0,'2015-05-27 15:54:48','N',null,null,null,1,1,'N',1,null,100,14)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000B3P8',1,-1,null,null,0,0,null,-1,'N',null,-1,'dbilldate',0,'N',1,'N','N',null,0,'dbilldate','pu.po_order.dbilldate',null,'N',1,null,'1001Z81000000000B3OZ','@@@@',1,null,null,null,'N',0,3,'body','body',0,'2013-01-21 10:25:10','N',null,null,null,0,1,'N',0,null,100,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000B3P9',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbillcode',0,'N',1,'N','Y',null,0,'vbillcode','pu.po_order.vbillcode',null,'N',1,null,'1001Z81000000000B3OZ','@@@@',1,null,null,null,'N',1,2,'body','body',0,'2013-01-21 10:25:10','N',null,null,null,0,1,'N',1,null,100,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000B3PA',1,-1,null,null,0,0,null,-1,'N',null,-1,'nexchangerate',0,'N',1,'N','N',null,0,'nexchangerate','pu.po_order_payplan.nexchangerate',null,'N',1,null,'1001Z81000000000B3OZ','@@@@',1,null,null,null,'N',0,19,'body','付款计划',0,'2013-01-21 10:25:10','N',null,null,null,0,1,'N',1,null,100,19)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000B3PB',1,-1,null,null,0,0,null,-1,'N',null,-1,'corigcurrencyid',0,'N',1,'N','N',null,0,'corigcurrencyid','pu.po_order_payplan.corigcurrencyid',null,'N',1,null,'1001Z81000000000B3OZ','@@@@',1,'币种档案,code=N',null,null,'N',0,17,'body','付款计划',0,'2013-01-21 10:25:10','N',null,null,null,0,1,'N',1,null,100,17)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000B3PC',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_payterm',0,'N',1,'N','N',null,0,'pk_payterm','pu.po_order_payplan.pk_payterm',null,'N',0,null,'1001Z81000000000B3OZ','@@@@',1,'付款协议,code=N',null,null,'N',0,8,'body','付款计划',0,'2013-01-21 10:25:10','N',null,null,null,1,1,'N',1,null,100,8)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000B3PD',1,-1,null,null,0,0,null,-1,'N',null,-1,'ccurrencyid',0,'N',1,'N','N',null,0,'ccurrencyid','pu.po_order_payplan.ccurrencyid',null,'N',1,null,'1001Z81000000000B3OZ','@@@@',1,'币种档案,code=N',null,null,'N',0,18,'body','付款计划',0,'2013-01-21 10:25:10','N',null,null,null,0,1,'N',1,null,100,18)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000B3PE',1,-1,null,null,0,0,null,-1,'N',null,-1,'nmny',0,'N',1,'N','N',null,0,'nmny','pu.po_order_payplan.nmny',null,'N',1,null,'1001Z81000000000B3OZ','@@@@',1,null,null,null,'N',0,16,'body','付款计划',1,'2013-01-21 10:25:10','N',null,null,null,0,1,'N',1,null,100,16)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000B3PF',1,-1,null,null,0,1,null,-1,'N',null,-1,'dbegindate',0,'N',1,'N','Y',null,0,'dbegindate','pu.po_order_payplan.dbegindate',null,'N',0,null,'1001Z81000000000B3OZ','@@@@',1,null,null,null,'N',1,10,'body','付款计划',0,'2013-01-21 10:25:10','N',null,null,null,1,1,'N',1,null,100,10)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000B3PG',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_financeorg_v',0,'N',1,'N','Y',null,0,'pk_financeorg_v','pu.po_order_payplan.pk_financeorg_v','pk_financeorg=pk_financeorg','N',1,null,'1001Z81000000000B3OZ','@@@@',1,'财务组织版本,code=N',null,null,'N',1,25,'body','付款计划',0,'2013-01-21 10:25:10','N',null,null,null,0,1,'N',1,null,100,25)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000B3PH',1,-1,null,null,0,1,null,-1,'N',null,-1,'crowno',0,'N',1,'N','Y',null,0,'crowno','pu.po_order_payplan.crowno',null,'N',0,null,'1001Z81000000000B3OZ','@@@@',1,null,null,null,'N',1,1,'body','付款计划',0,'2013-01-21 10:25:10','N',null,null,null,1,1,'N',1,null,100,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000B3PI',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_order_payplan',0,'N',1,'N','N',null,0,'pk_order_payplan','pu.po_order_payplan.pk_order_payplan',null,'N',0,null,'1001Z81000000000B3OZ','@@@@',1,null,null,null,'N',0,27,'body','付款计划',0,'2013-01-21 10:25:10','N',null,null,null,0,1,'N',1,null,100,27)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000B3PJ',1,-1,null,null,0,1,null,-1,'N',null,-1,'feffdatetype',0,'N',1,'N','Y',null,0,'feffdatetype','pu.po_order_payplan.feffdatetype',null,'N',0,null,'1001Z81000000000B3OZ','@@@@',1,'付款时点,code=N',null,null,'N',1,9,'body','付款计划',0,'2013-01-21 10:25:10','N',null,null,null,1,1,'N',1,null,100,9)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000B3PK',1,-1,null,null,0,1,null,-1,'N',null,-1,'iitermdays',0,'N',1,'N','Y',null,0,'iitermdays','pu.po_order_payplan.iitermdays',null,'N',0,null,'1001Z81000000000B3OZ','@@@@',1,null,null,null,'N',1,11,'body','付款计划',0,'2013-01-21 10:25:10','N',null,null,null,1,1,'N',1,null,100,11)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000B3PL',1,-1,null,null,0,0,null,-1,'N',null,-1,'naccumpayorgmny',0,'N',1,'N','Y',null,0,'naccumpayorgmny','pu.po_order_payplan.naccumpayorgmny',null,'N',0,null,'1001Z81000000000B3OZ','@@@@',1,null,null,null,'N',1,22,'body','付款计划',1,'2013-01-21 10:25:10','N',null,null,null,0,1,'N',1,null,100,22)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000B3PM',1,-1,null,null,0,0,null,-1,'N',null,-1,'iaccounttermno',0,'N',1,'N','Y',null,0,'iaccounttermno','pu.po_order_payplan.iaccounttermno',null,'N',0,null,'1001Z81000000000B3OZ','@@@@',1,null,null,null,'N',1,6,'body','付款计划',0,'2013-01-21 10:25:10','N',null,null,null,0,1,'N',1,null,100,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000B3PN',1,-1,'金额',null,0,1,null,-1,'N',null,-1,'norigmny',0,'N',1,'N','Y',null,0,'norigmny','pu.po_order_payplan.norigmny',null,'N',1,null,'1001Z81000000000B3OZ','@@@@',1,null,'UC000-0004112',null,'N',1,15,'body','付款计划',1,'2013-01-21 10:25:10','N',null,null,null,1,1,'N',1,null,100,15)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000B3PO',1,-1,null,null,0,0,null,-1,'N',null,-1,'naccumpaymny',0,'N',1,'N','N',null,0,'naccumpaymny','pu.po_order_payplan.naccumpaymny',null,'N',0,null,'1001Z81000000000B3OZ','@@@@',1,null,null,null,'N',0,23,'body','付款计划',1,'2013-01-21 10:25:10','N',null,null,null,0,1,'N',1,null,100,23)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000B3PP',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_paymentch',0,'N',1,'N','N',null,0,'pk_paymentch','pu.po_order_payplan.pk_paymentch',null,'N',0,null,'1001Z81000000000B3OZ','@@@@',1,null,null,null,'N',0,7,'body','付款计划',0,'2013-01-21 10:25:10','N',null,null,null,1,1,'N',1,null,100,7)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000B3PQ',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_financeorg',0,'N',1,'N','N',null,0,'pk_financeorg','pu.po_order_payplan.pk_financeorg',null,'N',1,null,'1001Z81000000000B3OZ','@@@@',1,'财务组织,code=N',null,null,'N',0,24,'body','付款计划',0,'2013-01-21 10:25:10','N',null,null,null,1,1,'N',1,null,100,24)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000B3Q1',1,-1,null,null,0,0,null,-1,'Y',null,-1,'pk_supplier',0,'N',1,'Y','Y',null,0,'pk_supplier','pu.po_order.pk_supplier',null,'N',1,null,'1001Z81000000000B3OZ','@@@@',1,'供应商档案,code=N',null,null,'N',1,4,'body','body',0,'2013-01-21 10:25:10','N',null,null,null,0,1,'N',1,null,100,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BM80',1,15,'hts',null,0,0,null,-1,'N',null,20,'hts',0,'N',1,'N','N',null,0,null,null,null,'N',0,null,'1001Z81000000000B3OZ','@@@@',1,null,'1400404070002',null,'N',0,30,'body','付款计划',0,'2013-01-21 10:25:10','N',null,null,null,0,1,'N',1,null,100,30)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000BM88',1,-1,null,null,0,0,null,-1,'N',null,-1,'forderstatus',0,'N',1,'N','N',null,0,'forderstatus','pu.po_order.forderstatus',null,'N',0,null,'1001Z81000000000B3OZ','@@@@',1,null,null,null,'N',0,31,'body','body',0,'2013-01-21 10:25:10','N',null,null,null,0,1,'N',1,null,100,31)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000F6AP',1,-1,null,null,0,0,null,-1,'N',null,-1,'naccumpayappmny',0,'N',1,'N','N',null,0,'naccumpayappmny','pu.po_order_payplan.naccumpayappmny',null,'N',0,null,'1001Z81000000000B3OZ','@@@@',1,null,null,null,'N',0,20,'body','body',1,'2013-01-21 10:25:10','N',null,null,null,0,1,'N',1,null,100,20)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000F6AQ',1,-1,null,null,0,0,null,-1,'N',null,-1,'naccumpayapporgmny',0,'N',1,'N','Y',null,0,'naccumpayapporgmny','pu.po_order_payplan.naccumpayapporgmny',null,'N',0,null,'1001Z81000000000B3OZ','@@@@',1,null,null,null,'N',1,21,'body','body',1,'2013-01-21 10:25:10','N',null,null,null,0,1,'N',1,null,100,21)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z81000000000F6AR',1,-1,null,null,0,0,null,-1,'N',null,-1,'ccontractid',0,'N',1,'N','N',null,0,'ccontractid','pu.po_order_payplan.ccontractid',null,'N',0,null,'1001Z81000000000B3OZ','@@@@',1,'采购合同,code=N',null,null,'N',0,32,'body','body',0,'2013-01-21 10:25:10','N',null,null,null,0,1,'N',1,null,100,32)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001EVA',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',null,0,'pk_group','pu.po_order_payplan.pk_group',null,'N',0,null,'1001Z81000000000B3OZ','@@@@',1,'集团,code=N',null,null,'N',0,33,'body','body',0,'2013-01-21 10:25:10','N',null,null,null,0,1,'N',1,null,100,33)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000YWY3',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_invcsupllier',null,'N',1,'N','N',null,0,'pk_invcsupllier','pu.po_order.pk_invcsupllier',null,'N',0,null,'1001Z81000000000B3OZ',null,1,'供应商档案,code=N',null,null,'N',0,5,'body','body',0,'2013-01-21 10:25:10','N',null,null,null,0,0,'N',1,null,100,5)
go

