insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002OGB','IM,079d81df-600a-48e9-83fc-4134e49f6d8f',6,0,1,null,null,'RETURNTYPE','退货类型',null,'N','Y','N','Y','N','N','N','N','Y','Y','N','N','N','N','Y',null,'N',9999,null,'=@','等于@',0,'@@@@','1001Z810000000002OG9',null,'1400408080001',2,null,null,'2011-09-05 10:37:49','N','0,1')
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002OGC','采购组织',5,1,1,null,null,'PK_PURCHASEORG','采购组织',null,'N','Y','N','Y','N','N','N','N','Y','Y','N','N','N','Y','Y',null,'N',9999,null,'=@','等于@',0,'@@@@','1001Z810000000002OG9',null,'UC000-0004091',2,null,null,'2011-09-02 11:31:38','N','#mainorg#')
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002OGD','库存组织',5,2,1,null,null,'PK_ORG','库存组织',null,'N','Y','N','Y','N','N','N','N','Y','Y','N','N','N','Y','Y',null,'N',9999,null,'=@','等于@',0,'@@@@','1001Z810000000002OG9',null,'UC000-0001825',2,null,null,'2011-09-02 11:31:38','N','#mainorg#')
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002OGE','-99',3,3,1,null,null,'DBILLDATE','退货日期',null,'N','Y','N','Y','N','N','N','N','Y','Y','N','N','N','Y','Y',null,'N',9999,null,'between@=@','介于@等于@',0,'@@@@','1001Z810000000002OG9',null,'1400408080002',2,null,null,'2011-09-05 10:42:04','N','#month(0)#,#day(0)#')
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002OGF','供应商档案',5,4,1,null,null,'PK_SUPPLIER','供应商',null,'N','Y','N','Y','N','N','N','N','N','Y','N','N','N','N','Y',null,'N',9999,null,'=@','等于@',0,'@@@@','1001Z810000000002OG9',null,'1400408080021',2,null,null,'2013-05-22 15:50:04','N',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values('1001Z810000000002OGG','物料',5,5,1,null,null,'PK_SRCMATERIAL','物料',null,'N','Y','N','Y','N','N','N','N','N','Y','N','N','N','N','Y',null,'N',9999,null,'=@','等于@',0,'@@@@','1001Z810000000002OG9',null,'1400408080022',2,null,null,'2013-05-22 15:50:04','N',null)
go

