package nc.vo.pu.m25trantype.entity;

/**
 * 功能说明: 基于SmartVO的业务VO.采购发票交易类型,
 * 调试时可以使用nc.vo.scm.bd.SmartVODataUtils.expose()展示其数据。 Generated By CodeSeed 3.1
 * 修改记录： 修改人, 日期, 说明
 */
import nc.vo.pub.IVOMeta;
import nc.vo.pub.SuperVO;
import nc.vo.pub.lang.UFBoolean;
import nc.vo.pub.lang.UFDateTime;
import nc.vo.pubapp.pattern.model.meta.entity.vo.VOMetaFactory;

/**
 * 采购发票交易类型扩展属性VO
 * 
 * @author GGR
 * @time 2009-12-22 下午04:33:56
 * @since 6.0
 */
public class InvcTranTypeVO extends SuperVO {

  // 是否调整发票
  public static final String BAJUST = "bajust";

  // 是否质量合格检查
  public static final String BCHECKQUALITY = "bcheckquality";

  // 是否消耗性采购
  public static final String BCONSUMEPUR = "bconsumepur";

  // 结算完毕自动传应付
  public static final String BSENDPAY = "bsendpay";

  /** 交易类型编码 */
  public static final String CTRANTYPEID = "ctrantypeid";

  // 传应付控制
  public static final String ITOARAPMODE = "itoarapmode";

  // 所属集团
  public static final String PK_GROUP = "pk_group";

  // 采购发票交易类型ID
  public static final String PK_INVCTRANTYPE = "pk_invctrantype";

  // 时间戳
  public static final String TS = "ts";

  // 交易类型编码
  public static final String VTRANTYPECODE = "vtrantypecode";

  /**
   * serialVersionUID
   */
  private static final long serialVersionUID = -2645719781706315591L;

  /**
   * 属性是否调整发票的Getter方法.
   * 
   * @time 2013-7-9 15:55:49
   * @return 是否调整发票
   */
  public UFBoolean getBajust() {
    return (UFBoolean) this.getAttributeValue(InvcTranTypeVO.BAJUST);
  }

  /**
   * 属性是否质量合格检查的Getter方法.
   * 
   * @time 2009-12-22 15:55:49
   * @return 是否质量合格检查
   */
  public UFBoolean getBcheckquality() {
    return (UFBoolean) this.getAttributeValue(InvcTranTypeVO.BCHECKQUALITY);
  }

  /**
   * 属性是否消耗性采购的Getter方法.
   * 
   * @time 2009-12-22 15:55:49
   * @return 是否消耗性采购
   */
  public UFBoolean getBconsumepur() {
    return (UFBoolean) this.getAttributeValue(InvcTranTypeVO.BCONSUMEPUR);
  }

  /**
   * 属性结算完毕自动传应付的Getter方法.
   * 
   * @time 2009-12-22 15:55:49
   * @return 结算完毕自动传应付
   */
  public UFBoolean getBsendpay() {
    return (UFBoolean) this.getAttributeValue(InvcTranTypeVO.BSENDPAY);
  }

  /** 交易类型编码 getter 方法 */
  public String getCtrantypeid() {
    return (String) this.getAttributeValue(InvcTranTypeVO.CTRANTYPEID);
  }

  /**
   * 属性传应付控制的Getter方法.
   * 
   * @time 2009-12-22 15:55:49
   * @return 传应付控制
   */
  public Integer getItoarapmode() {
    return (Integer) this.getAttributeValue(InvcTranTypeVO.ITOARAPMODE);
  }

  @Override
  public IVOMeta getMetaData() {
    IVOMeta meta = VOMetaFactory.getInstance().getVOMeta("pu.po_invctrantype");
    return meta;
  }

  /**
   * 属性所属集团的Getter方法.
   * 
   * @time 2009-12-22 15:55:49
   * @return 所属集团
   */
  public String getPk_group() {
    return (String) this.getAttributeValue(InvcTranTypeVO.PK_GROUP);
  }

  /**
   * 属性采购发票交易类型ID的Getter方法.
   * 
   * @time 2009-12-22 15:55:49
   * @return 采购发票交易类型ID
   */
  public String getPk_invctrantype() {
    return (String) this.getAttributeValue(InvcTranTypeVO.PK_INVCTRANTYPE);
  }

  /**
   * 属性时间戳的Getter方法.
   * 
   * @time 2009-12-22 15:55:49
   * @return 时间戳
   */
  public UFDateTime getTs() {
    return (UFDateTime) this.getAttributeValue(InvcTranTypeVO.TS);
  }

  /**
   * 属性交易类型编码的Getter方法.
   * 
   * @time 2009-12-22 15:55:49
   * @return 交易类型编码
   */
  public String getVtrantypecode() {
    return (String) this.getAttributeValue(InvcTranTypeVO.VTRANTYPECODE);
  }

  /**
   * 属性是否调整发票的Setter方法.
   * 
   * @time 2013-7-8 15:55:49
   * @param bajust 是否调整发票
   */
  public void setBajust(UFBoolean bajust) {
    this.setAttributeValue(InvcTranTypeVO.BAJUST, bajust);
  }

  /**
   * 属性是否质量合格检查的Setter方法.
   * 
   * @time 2009-12-22 15:55:49
   * @param bcheckquality 是否质量合格检查
   */
  public void setBcheckquality(UFBoolean bcheckquality) {
    this.setAttributeValue(InvcTranTypeVO.BCHECKQUALITY, bcheckquality);
  }

  /**
   * 属性是否消耗性采购的Setter方法.
   * 
   * @time 2009-12-22 15:55:49
   * @param bconsumepur 是否消耗性采购
   */
  public void setBconsumepur(UFBoolean bconsumepur) {
    this.setAttributeValue(InvcTranTypeVO.BCONSUMEPUR, bconsumepur);
  }

  /**
   * 属性结算完毕自动传应付的Setter方法.
   * 
   * @time 2009-12-22 15:55:49
   * @param bsendpay 结算完毕自动传应付
   */
  public void setBsendpay(UFBoolean bsendpay) {
    this.setAttributeValue(InvcTranTypeVO.BSENDPAY, bsendpay);
  }

  /** 交易类型编码 setter 方法 */
  public void setCtrantypeid(String ctrantypeid) {
    this.setAttributeValue(InvcTranTypeVO.CTRANTYPEID, ctrantypeid);
  }

  /**
   * 属性传应付控制的Setter方法.
   * 
   * @time 2009-12-22 15:55:49
   * @param itoarapmode 传应付控制
   */
  public void setItoarapmode(Integer itoarapmode) {
    this.setAttributeValue(InvcTranTypeVO.ITOARAPMODE, itoarapmode);
  }

  /**
   * 属性所属集团的Setter方法.
   * 
   * @time 2009-12-22 15:55:49
   * @param pk_group 所属集团
   */
  public void setPk_group(String pk_group) {
    this.setAttributeValue(InvcTranTypeVO.PK_GROUP, pk_group);
  }

  /**
   * 属性采购发票交易类型ID的Setter方法.
   * 
   * @time 2009-12-22 15:55:49
   * @param pk_invctrantype 采购发票交易类型ID
   */
  public void setPk_invctrantype(String pk_invctrantype) {
    this.setAttributeValue(InvcTranTypeVO.PK_INVCTRANTYPE, pk_invctrantype);
  }

  /**
   * 属性时间戳的Setter方法.
   * 
   * @time 2009-12-22 15:55:49
   * @param ts 时间戳
   */
  public void setTs(UFDateTime ts) {
    this.setAttributeValue(InvcTranTypeVO.TS, ts);
  }

  /**
   * 属性交易类型编码的Setter方法.
   * 
   * @time 2009-12-22 15:55:49
   * @param vtrantypecode 交易类型编码
   */
  public void setVtrantypecode(String vtrantypecode) {
    this.setAttributeValue(InvcTranTypeVO.VTRANTYPECODE, vtrantypecode);
  }

}
