insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001JK9',1,-1,null,null,0,1,null,-1,'N',null,-1,'fpositiontype',0,'N',1,'N','N',null,0,'fpositiontype','pu.po_position.fpositiontype',null,'N',0,null,'1002Z810000000000EOH','@@@@',0,null,null,null,'N',0,9,'PositioninvHeaderVO','PositioninvHeaderVO',0,'2012-06-18 13:41:20','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001JKA',1,-1,'计划员编码',null,0,1,null,-1,'N',null,-1,'cemployeeid',0,'N',1,'N','Y',null,0,'cemployeeid','pu.po_position.cemployeeid',null,'N',1,null,'1002Z810000000000EOH','@@@@',0,'人员,code=Y','UC000-0003483',null,'N',1,6,'PositioninvHeaderVO','PositioninvHeaderVO',0,'2012-06-18 13:41:20','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001JKB',1,-1,null,null,0,1,null,-1,'N',null,-1,'vmemo',0,'N',1,'N','Y',null,0,'vmemo','pu.po_position.vmemo',null,'N',0,null,'1002Z810000000000EOH','@@@@',0,null,null,null,'N',1,8,'PositioninvHeaderVO','PositioninvHeaderVO',0,'2012-06-18 13:41:20','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001JKC',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',null,0,'pk_group','pu.po_position.pk_group',null,'N',0,null,'1002Z810000000000EOH','@@@@',0,null,null,null,'N',0,2,'PositioninvHeaderVO','PositioninvHeaderVO',0,'2012-06-18 13:41:20','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001JKD',1,-1,'物料编码',null,0,0,null,-1,'N',null,-1,'pk_material',0,'N',1,'N','N',null,0,'pk_material','pu.po_position_b.pk_material','material_code=code','N',0,null,'1002Z810000000000EOH','@@@@',1,'物料（多版本）','UC000-0002911',null,'N',0,7,'pk_position_b','岗位设置子表',0,'2012-06-18 13:41:20','N',null,null,null,0,1,'N',0,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001JKE',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_position_b',0,'N',1,'N','N',null,0,'pk_position_b','pu.po_position_b.pk_position_b',null,'N',0,null,'1002Z810000000000EOH','@@@@',1,null,null,null,'N',0,1,'pk_position_b','岗位设置子表',0,'2012-06-18 13:41:20','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001JKF',1,-1,null,null,0,1,null,-1,'N',null,30,'code',0,'N',1,'N','Y',null,0,'code','pu.po_position.code',null,'N',1,null,'1002Z810000000000EOH','@@@@',0,null,null,null,'N',1,4,'PositioninvHeaderVO','PositioninvHeaderVO',0,'2012-06-18 13:41:20','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001JKG',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',null,0,'ts','pu.po_position_b.ts',null,'N',0,null,'1002Z810000000000EOH','@@@@',1,null,null,null,'N',0,11,'pk_position_b','岗位设置子表',0,'2012-06-18 13:41:20','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001JKH',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_position',0,'N',1,'N','N',null,0,'pk_position','pu.po_position.pk_position',null,'N',0,null,'1002Z810000000000EOH','@@@@',0,null,null,null,'N',0,1,'PositioninvHeaderVO','PositioninvHeaderVO',0,'2012-06-18 13:41:20','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001JKI',1,-1,'物料基本分类编码',null,0,1,null,-1,'N',null,-1,'pk_marbasclass',0,'N',1,'N','Y',null,0,'pk_marbasclass','pu.po_position_b.pk_marbasclass','marbasclass_code=code','N',0,null,'1002Z810000000000EOH','@@@@',1,'物料基本分类','1400105150002',null,'N',1,3,'pk_position_b','岗位设置子表',0,'2012-06-18 13:41:20','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001JKJ',1,-1,null,null,0,1,null,-1,'N',null,-1,'fflag',0,'N',1,'N','Y',null,0,'fflag','pu.po_position_b.fflag',null,'N',1,null,'1002Z810000000000EOH','@@@@',1,null,null,null,'N',1,10,'pk_position_b','岗位设置子表',0,'2012-06-18 13:41:20','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001JKK',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','N',null,0,'pk_org','pu.po_position.pk_org',null,'N',0,null,'1002Z810000000000EOH','@@@@',0,null,null,null,'N',0,3,'PositioninvHeaderVO','PositioninvHeaderVO',0,'2012-06-18 13:41:20','N',null,null,null,1,1,'N',0,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001JKL',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',null,0,'ts','pu.po_position.ts',null,'N',0,null,'1002Z810000000000EOH','@@@@',0,null,null,null,'N',0,10,'PositioninvHeaderVO','PositioninvHeaderVO',0,'2012-06-18 13:41:20','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001JKM',1,-1,'物料采购分类编码',null,0,1,null,-1,'N',null,-1,'pk_marpuclass',0,'N',1,'N','Y',null,0,'pk_marpuclass','pu.po_position_b.pk_marpuclass','marpuclass_code=code','N',0,null,'1002Z810000000000EOH','@@@@',1,'物料采购分类','1400105150003',null,'N',1,5,'pk_position_b','岗位设置子表',0,'2012-06-18 13:41:20','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001JKN',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','N',null,0,'pk_org','pu.po_position_b.pk_org',null,'N',0,null,'1002Z810000000000EOH','@@@@',1,null,null,null,'N',0,2,'pk_position_b','岗位设置子表',0,'2012-06-18 13:41:20','N',null,null,null,1,1,'N',0,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000001JKO',1,-1,null,null,0,1,null,-1,'N',null,50,'name',0,'N',1,'N','Y',null,0,'name','pu.po_position.name',null,'N',1,null,'1002Z810000000000EOH','@@@@',0,null,null,null,'N',1,5,'PositioninvHeaderVO','PositioninvHeaderVO',0,'2012-06-18 13:41:20','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z8100000000064OK',1,-1,'物料采购分类名称',null,0,0,null,-1,'N','pk_marpuclass',-1,'pk_marpuclass.name',0,'N',1,'N','Y',null,0,'name','uap.marpuclass.name',null,'N',0,null,'1002Z810000000000EOH','@@@@',1,null,'1400105150001',null,'N',1,6,'pk_position_b','pk_position_b',0,'2012-06-18 13:41:20','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z8100000000064OL',1,-1,'物料基本分类名称',null,0,0,null,-1,'N','pk_marbasclass',-1,'pk_marbasclass.name',0,'N',1,'N','Y',null,0,'name','uap.marbasclass.name',null,'N',0,null,'1002Z810000000000EOH','@@@@',1,null,'1400105150004',null,'N',1,4,'pk_position_b','pk_position_b',0,'2012-06-18 13:41:20','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z8100000000064ON',1,-1,'计划员名称',null,0,0,null,-1,'N','cemployeeid',-1,'cemployeeid.name',0,'N',1,'N','Y',null,0,'name','uap.psndoc.name',null,'N',0,null,'1002Z810000000000EOH','@@@@',0,null,'UC000-0003482',null,'N',1,7,'PositioninvHeaderVO','PositioninvHeaderVO',0,'2012-06-18 13:41:20','N',null,null,null,1,1,'N',1,null,1,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000EQV7',1,-1,null,null,0,0,null,-1,'N',null,-1,'material_code',0,'N',1,'N','N',null,0,'material_code','pu.po_position_b.material_code',null,'N',0,null,'1002Z810000000000EOH','@@@@',1,null,null,null,'N',0,13,'pk_position_b','pk_position_b',0,'2012-06-18 13:41:20','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000EQV8',1,-1,null,null,0,0,null,-1,'N',null,-1,'marbasclass_code',0,'N',1,'N','N',null,0,'marbasclass_code','pu.po_position_b.marbasclass_code',null,'N',0,null,'1002Z810000000000EOH','@@@@',1,null,null,null,'N',0,12,'pk_position_b','pk_position_b',0,'2012-06-18 13:41:20','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000EQV9',1,-1,null,null,0,1,null,-1,'N',null,-1,'marpuclass_code',0,'N',1,'N','N',null,0,'marpuclass_code','pu.po_position_b.marpuclass_code',null,'N',0,null,'1002Z810000000000EOH','@@@@',1,null,null,null,'N',0,14,'pk_position_b','pk_position_b',0,'2012-06-18 13:41:20','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000O4TU',1,-1,null,null,0,0,null,-1,'N','pk_srcmaterial',-1,'pk_srcmaterial.name',0,'N',1,'N','Y',null,0,'name','uap.material_v.name',null,'N',0,null,'1002Z810000000000EOH','@@@@',1,null,null,null,'N',1,9,'pk_position_b','pk_position_b',0,'2012-06-18 13:41:20','N',null,null,null,1,1,'N',1,null,100,null)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000O4TV',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_srcmaterial',0,'N',1,'N','Y',null,0,'pk_srcmaterial','pu.po_position_b.pk_srcmaterial','pk_material=pk_material,material_code=code','N',0,null,'1002Z810000000000EOH','@@@@',1,null,null,null,'N',1,8,'pk_position_b','pk_position_b',0,'2012-06-18 13:41:20','N',null,null,null,1,1,'N',1,null,100,null)
go

