insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000000QCT',1,-1,'库存单据类型',null,0,0,null,-1,'N','vstockbilltype',-1,'vstockbilltype.billtypename',0,'N',1,'N','Y',null,0,'billtypename','uap.BilltypeVO.billtypename',null,'N',0,null,'1002Z810000000005OH6','@@@@',1,null,'1400414040002',null,'N',1,4,'body','body',0,'2015-03-19 20:50:52','N',null,null,null,1,1,'N',1,null,100,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000003TCH',1,-1,null,null,0,1,null,-1,'N',null,-1,'ncostfactor3',0,'N',1,'N','Y',null,0,'ncostfactor3','pu.po_settlebill_b.ncostfactor3',null,'N',0,null,'1002Z810000000005OH6','@@@@',1,null,null,null,'N',1,32,'body','body',1,'2015-03-19 20:50:52','N',null,null,null,1,1,'N',1,null,100,32)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000003TCI',1,-1,null,null,0,1,null,-1,'N',null,-1,'ncostfactor1',0,'N',1,'N','Y',null,0,'ncostfactor1','pu.po_settlebill_b.ncostfactor1',null,'N',0,null,'1002Z810000000005OH6','@@@@',1,null,null,null,'N',1,30,'body','body',1,'2015-03-19 20:50:52','N',null,null,null,1,1,'N',1,null,100,30)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000003TCJ',1,-1,null,null,0,1,null,-1,'N',null,-1,'ncostfactor7',0,'N',1,'N','Y',null,0,'ncostfactor7','pu.po_settlebill_b.ncostfactor7',null,'N',0,null,'1002Z810000000005OH6','@@@@',1,null,null,null,'N',1,36,'body','body',1,'2015-03-19 20:50:52','N',null,null,null,1,1,'N',1,null,100,36)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000003TCK',1,-1,null,null,0,1,null,-1,'N',null,-1,'ncostfactor6',0,'N',1,'N','Y',null,0,'ncostfactor6','pu.po_settlebill_b.ncostfactor6',null,'N',0,null,'1002Z810000000005OH6','@@@@',1,null,null,null,'N',1,35,'body','body',1,'2015-03-19 20:50:52','N',null,null,null,1,1,'N',1,null,100,35)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000003TCL',1,-1,null,null,0,1,null,-1,'N',null,-1,'ncostfactor5',0,'N',1,'N','Y',null,0,'ncostfactor5','pu.po_settlebill_b.ncostfactor5',null,'N',0,null,'1002Z810000000005OH6','@@@@',1,null,null,null,'N',1,34,'body','body',1,'2015-03-19 20:50:52','N',null,null,null,1,1,'N',1,null,100,34)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000003TCM',1,-1,null,null,0,1,null,-1,'N',null,-1,'ncostfactor2',0,'N',1,'N','Y',null,0,'ncostfactor2','pu.po_settlebill_b.ncostfactor2',null,'N',0,null,'1002Z810000000005OH6','@@@@',1,null,null,null,'N',1,31,'body','body',1,'2015-03-19 20:50:52','N',null,null,null,1,1,'N',1,null,100,31)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000003TCN',1,-1,null,null,0,1,null,-1,'N',null,-1,'ncostfactor8',0,'N',1,'N','Y',null,0,'ncostfactor8','pu.po_settlebill_b.ncostfactor8',null,'N',0,null,'1002Z810000000005OH6','@@@@',1,null,null,null,'N',1,37,'body','body',1,'2015-03-19 20:50:52','N',null,null,null,1,1,'N',1,null,100,37)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000003TCO',1,-1,null,null,0,1,null,-1,'N',null,-1,'ncostfactor4',0,'N',1,'N','Y',null,0,'ncostfactor4','pu.po_settlebill_b.ncostfactor4',null,'N',0,null,'1002Z810000000005OH6','@@@@',1,null,null,null,'N',1,33,'body','body',1,'2015-03-19 20:50:52','N',null,null,null,1,1,'N',1,null,100,33)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000007S4R',1,-1,null,'false',0,0,null,-1,'N',null,-1,'bvirtualsettle',0,'N',1,'N','N',null,0,'bvirtualsettle','pu.po_settlebill.bvirtualsettle',null,'N',0,null,'1002Z810000000005OH6','@@@@',0,null,null,null,'N',0,11,'main','结算单头',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,1,11)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000007S4S',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org_v',0,'N',1,'N','Y',null,0,'pk_org_v','pu.po_settlebill.pk_org_v',null,'N',0,null,'1002Z810000000005OH6','@@@@',0,'财务组织版本',null,null,'N',0,3,'main','结算单头',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,1,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z810000000007S4T',1,-1,null,'@SYSOPER',0,0,null,-1,'N',null,-1,'creator',0,'N',1,'N','Y',null,0,'creator','pu.po_settlebill.creator',null,'N',0,null,'1002Z810000000005OH6','@@@@',2,'用户',null,null,'N',1,1,'tail','tail',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,1,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1001Z8WLPOTEM0002017',1,-1,null,null,0,0,null,-1,'N',null,-1,'dmakedate',0,'N',1,'N','Y',null,0,'dmakedate','pu.po_settlebill.dmakedate',null,'N',0,null,'1002Z810000000005OH6','@@@@',2,null,null,null,'N',1,2,'tailinfo','tailinfo',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,1,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z8100000000026WD',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_arrstockorg',null,'N',1,'N','N',null,0,'pk_arrstockorg','pu.po_settlebill_b.pk_arrstockorg',null,'N',0,null,'1002Z810000000005OH6',null,1,'库存组织,code=N',null,null,'N',0,1,'body','body',0,'2015-03-19 20:50:52','N',null,null,null,1,1,'N',1,null,100,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005OH7',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_stock_b',null,'N',1,'N','N',null,0,'pk_stock_b','pu.po_settlebill_b.pk_stock_b',null,'N',0,null,'1002Z810000000005OH6',null,1,null,null,null,'N',0,19,'body','结算单体',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,100,19)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005OH8',1,-1,null,null,0,0,null,-1,'N',null,-1,'vstocktrantype',null,'N',1,'N','N',null,0,'vstocktrantype','pu.po_settlebill_b.vstocktrantype',null,'N',0,null,'1002Z810000000005OH6',null,1,'影响因素交 易类型,code=N',null,null,'N',0,11,'body','结算单体',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,100,11)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005OH9',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_dtransaleid',null,'N',1,'N','N',null,0,'pk_dtransaleid','pu.po_settlebill_b.pk_dtransaleid',null,'N',0,null,'1002Z810000000005OH6',null,1,null,null,null,'N',0,24,'body','结算单体',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,100,24)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005OHC',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_srcmaterial',null,'N',1,'N','N',null,0,'pk_srcmaterial','pu.po_settlebill_b.pk_srcmaterial',null,'N',0,null,'1002Z810000000005OH6',null,1,'物料,code=N',null,null,'N',0,14,'body','结算单体',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,100,14)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005OHD',1,-1,null,null,0,0,null,-1,'N',null,-1,'vinvoicetrantype',null,'N',1,'N','N',null,0,'vinvoicetrantype','pu.po_settlebill_b.vinvoicetrantype',null,'N',0,null,'1002Z810000000005OH6',null,1,'影响因素交 易类型,code=N',null,null,'N',0,7,'body','结算单体',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,100,7)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005OHG',1,-1,null,null,0,0,null,-1,'Y',null,-1,'pk_supplier',null,'N',1,'Y','N',null,0,'pk_supplier','pu.po_settlebill_b.pk_supplier',null,'N',0,null,'1002Z810000000005OH6',null,1,'供应商档案,code=N',null,null,'N',0,40,'body','结算单体',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,100,40)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005OHK',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',null,'N',1,'N','N',null,0,'pk_group','pu.po_settlebill.pk_group',null,'N',0,null,'1002Z810000000005OH6',null,0,'集团',null,null,'N',0,2,'main','结算单头',0,'2015-03-19 20:50:52','N',null,null,null,0,0,'N',1,null,1,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005OHL',1,-1,null,null,0,0,null,-1,'N',null,-1,'nmoney',null,'N',1,'N','Y',null,0,'nmoney','pu.po_settlebill_b.nmoney',null,'N',0,null,'1002Z810000000005OH6',null,1,null,null,null,'N',1,28,'body','结算单体',1,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,100,28)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005OHN',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_invoice',null,'N',1,'N','N',null,0,'pk_invoice','pu.po_settlebill_b.pk_invoice',null,'N',0,null,'1002Z810000000005OH6',null,1,null,null,null,'N',0,16,'body','结算单体',0,'2015-03-19 20:50:52','N',null,null,null,0,0,'N',1,null,100,16)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005OHO',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_settlebill',null,'N',1,'N','N',null,0,'pk_settlebill','pu.po_settlebill.pk_settlebill',null,'N',0,null,'1002Z810000000005OH6',null,0,null,null,null,'N',0,1,'main','结算单头',0,'2015-03-19 20:50:52','N',null,null,null,0,0,'N',1,null,1,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005OHR',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_invoice_b',null,'N',1,'N','N',null,0,'pk_invoice_b','pu.po_settlebill_b.pk_invoice_b',null,'N',0,null,'1002Z810000000005OH6',null,1,null,null,null,'N',0,17,'body','结算单体',0,'2015-03-19 20:50:52','N',null,null,null,0,0,'N',1,null,100,17)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005OHS',1,-1,null,null,0,0,null,-1,'N',null,-1,'ts',null,'N',1,'N','N',null,0,'ts','pu.po_settlebill.ts',null,'N',0,null,'1002Z810000000005OH6',null,0,null,null,null,'N',0,7,'main','结算单头',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,1,7)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005OHU',1,-1,null,null,0,0,null,-1,'Y',null,-1,'pk_material',null,'N',1,'Y','N',null,0,'pk_material','pu.po_settlebill_b.pk_material',null,'N',0,null,'1002Z810000000005OH6',null,1,'物料（多版本）,code=N',null,null,'N',0,12,'body','结算单体',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,100,12)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005OHV',1,-1,null,null,0,0,null,-1,'Y',null,-1,'vstockcode',null,'N',1,'Y','Y',null,0,'vstockcode','pu.po_settlebill_b.vstockcode',null,'N',0,null,'1002Z810000000005OH6',null,1,null,null,null,'N',1,5,'body','结算单体',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,100,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005OHW',1,-1,null,'0',0,0,null,-1,'N',null,-1,'iprintcount',null,'N',1,'N','N',null,0,'iprintcount','pu.po_settlebill.iprintcount',null,'N',0,null,'1002Z810000000005OH6',null,0,null,null,null,'N',0,6,'main','结算单头',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,1,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005OHX',1,-1,null,null,0,0,null,-1,'N',null,-1,'vbillcode',null,'N',1,'Y','Y',null,0,'vbillcode','pu.po_settlebill.vbillcode',null,'N',0,null,'1002Z810000000005OH6',null,0,null,null,null,'N',1,4,'main','结算单头',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,1,4)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005OHZ',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_settlebill_b',null,'N',1,'N','N',null,0,'pk_settlebill_b','pu.po_settlebill_b.pk_settlebill_b',null,'N',0,null,'1002Z810000000005OH6',null,1,null,null,null,'N',0,10,'body','结算单体',0,'2015-03-19 20:50:52','N',null,null,null,0,0,'N',1,null,100,10)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005OI0',1,-1,null,null,0,0,null,-1,'N',null,-1,'ts',null,'N',1,'N','N',null,0,'ts','pu.po_settlebill_b.ts',null,'N',0,null,'1002Z810000000005OH6',null,1,null,null,null,'N',0,45,'body','结算单体',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,100,45)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005OI1',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_dept',null,'N',1,'N','N',null,0,'pk_dept','pu.po_settlebill_b.pk_dept',null,'N',0,null,'1002Z810000000005OH6',null,1,'部门,code=N',null,null,'N',0,42,'body','结算单体',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,100,42)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005OI2',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_invoiceorder_b',null,'N',1,'N','N',null,0,'pk_invoiceorder_b','pu.po_settlebill_b.pk_invoiceorder_b',null,'N',0,null,'1002Z810000000005OH6',null,1,null,null,null,'N',0,23,'body','结算单体',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,100,23)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005OI3',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_costregion',null,'N',1,'N','N',null,0,'pk_costregion','pu.po_settlebill_b.pk_costregion',null,'N',0,null,'1002Z810000000005OH6',null,1,'成本域,code=N',null,null,'N',0,39,'body','结算单体',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,100,39)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005OI5',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_stockorder_b',null,'N',1,'N','N',null,0,'pk_stockorder_b','pu.po_settlebill_b.pk_stockorder_b',null,'N',0,null,'1002Z810000000005OH6',null,1,null,null,null,'N',0,21,'body','结算单体',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,100,21)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005OI8',1,-1,null,null,0,0,null,-1,'Y',null,-1,'vinvoicecode',null,'N',1,'Y','Y',null,0,'vinvoicecode','pu.po_settlebill_b.vinvoicecode',null,'N',0,null,'1002Z810000000005OH6',null,1,null,null,null,'N',1,6,'body','结算单体',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,100,6)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005OI9',1,-1,null,null,0,0,null,-1,'N',null,-1,'nprice',null,'N',1,'N','Y',null,0,'nprice','pu.po_settlebill_b.nprice',null,'N',0,null,'1002Z810000000005OH6',null,1,null,null,null,'N',1,27,'body','结算单体',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,100,27)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005OIA',1,-1,null,null,0,0,null,-1,'N',null,-1,'nreasonalwastmny',null,'N',1,'N','Y',null,0,'nreasonalwastmny','pu.po_settlebill_b.nreasonalwastmny',null,'N',0,null,'1002Z810000000005OH6',null,1,null,null,null,'N',1,48,'body','结算单体',1,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,100,48)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005OIB',1,-1,null,null,0,0,null,-1,'N',null,-1,'nsettlenum',null,'N',1,'N','Y',null,0,'nsettlenum','pu.po_settlebill_b.nsettlenum',null,'N',0,null,'1002Z810000000005OH6',null,1,null,null,null,'N',1,26,'body','结算单体',1,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,100,26)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005OIC',1,-1,null,null,0,0,null,-1,'N',null,-1,'nreasonalwastprice',null,'N',1,'N','Y',null,0,'nreasonalwastprice','pu.po_settlebill_b.nreasonalwastprice',null,'N',0,null,'1002Z810000000005OH6',null,1,null,null,null,'N',1,47,'body','结算单体',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,100,47)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005OID',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_stockorder',null,'N',1,'N','N',null,0,'pk_stockorder','pu.po_settlebill_b.pk_stockorder',null,'N',0,null,'1002Z810000000005OH6',null,1,null,null,null,'N',0,20,'body','结算单体',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,100,20)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005OIE',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_invoiceorder',null,'N',1,'N','N',null,0,'pk_invoiceorder','pu.po_settlebill_b.pk_invoiceorder',null,'N',0,null,'1002Z810000000005OH6',null,1,null,null,null,'N',0,22,'body','结算单体',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,100,22)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005OIF',1,-1,'库存单据类型code',null,0,0,null,-1,'N',null,-1,'vstockbilltype',null,'N',1,'N','N',null,0,'vstockbilltype','pu.po_settlebill_b.vstockbilltype',null,'N',0,null,'1002Z810000000005OH6',null,1,'影响因素单据类型,code=N','1400414040001',null,'N',0,3,'body','结算单体',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,100,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005OIG',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_dtransalebid',null,'N',1,'N','N',null,0,'pk_dtransalebid','pu.po_settlebill_b.pk_dtransalebid',null,'N',0,null,'1002Z810000000005OH6',null,1,null,null,null,'N',0,25,'body','结算单体',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,100,25)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005OIJ',1,-1,null,null,0,0,null,-1,'N',null,-1,'nreasonalwastnum',null,'N',1,'N','Y',null,0,'nreasonalwastnum','pu.po_settlebill_b.nreasonalwastnum',null,'N',0,null,'1002Z810000000005OH6',null,1,null,null,null,'N',1,38,'body','结算单体',1,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,100,38)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005OIK',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_stock',null,'N',1,'N','N',null,0,'pk_stock','pu.po_settlebill_b.pk_stock',null,'N',0,null,'1002Z810000000005OH6',null,1,null,null,null,'N',0,18,'body','结算单体',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,100,18)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005OIN',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',null,'N',1,'N','N',null,0,'pk_group','pu.po_settlebill_b.pk_group',null,'N',0,null,'1002Z810000000005OH6',null,1,'集团,code=N',null,null,'N',0,15,'body','结算单体',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,100,15)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005YIL',1,-1,null,null,0,0,null,-1,'N','pk_material',-1,'pk_material.name',0,'N',1,'N','Y',null,0,'name','uap.material.name',null,'N',0,null,'1002Z810000000005OH6','@@@@',1,null,null,null,'N',1,9,'body','body',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,100,9)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z810000000005YIM',1,-1,null,null,0,0,null,-1,'Y','pk_material',-1,'pk_material.code',0,'N',1,'Y','Y',null,0,'code','uap.material.code',null,'N',0,null,'1002Z810000000005OH6','@@@@',1,null,null,null,'N',1,8,'body','body',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,100,8)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z8100000000063WP',1,-1,null,'false',0,0,null,-1,'N',null,-1,'btoia',0,'N',1,'N','N',null,0,'btoia','pu.po_settlebill.btoia',null,'N',0,null,'1002Z810000000005OH6','@@@@',0,null,null,null,'N',0,8,'main','main',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,1,8)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000ASW3',1,-1,null,null,0,0,null,-1,'N',null,-1,'stockbilldate',0,'N',1,'N','N',null,0,'stockbilldate','pu.po_settlebill_b.stockbilldate',null,'N',0,null,'1002Z810000000005OH6','@@@@',1,null,null,null,'N',0,50,'body','body',0,'2015-03-19 20:50:52','N',null,null,null,1,1,'N',1,null,100,50)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000ASW4',1,-1,null,null,0,0,null,-1,'N',null,-1,'vitctcode',0,'N',1,'N','N',null,0,'vitctcode','pu.po_settlebill_b.vitctcode',null,'N',0,null,'1002Z810000000005OH6','@@@@',1,null,null,null,'N',0,51,'body','body',0,'2015-03-19 20:50:52','N',null,null,null,1,1,'N',1,null,100,51)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000ASW5',1,-1,null,null,0,0,null,-1,'N',null,-1,'invoicebilldate',0,'N',1,'N','N',null,0,'invoicebilldate','pu.po_settlebill_b.invoicebilldate',null,'N',0,null,'1002Z810000000005OH6','@@@@',1,null,null,null,'N',0,49,'body','body',0,'2015-03-19 20:50:52','N',null,null,null,1,1,'N',1,null,100,49)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000GS6D',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_psndoc',null,'N',1,'N','Y',null,0,'pk_psndoc','pu.po_settlebill_b.pk_psndoc',null,'N',0,null,'1002Z810000000005OH6',null,1,'人员,code=N',null,null,'N',1,44,'body','body',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,100,44)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000NOMK',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_dept_v',0,'N',1,'N','Y',null,0,'pk_dept_v','pu.po_settlebill_b.pk_dept_v',null,'N',0,null,'1002Z810000000005OH6','@@@@',1,'部门版本,code=N',null,null,'N',1,43,'body','body',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,100,43)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000QDUL',1,-1,null,null,0,0,null,-1,'N',null,-1,'cunitid',0,'N',1,'N','Y',null,0,'cunitid','pu.po_settlebill_b.cunitid',null,'N',0,null,'1002Z810000000005OH6','@@@@',1,'计量单位,code=N',null,null,'N',1,13,'body','body',0,'2015-03-19 20:50:52','N',null,null,null,1,1,'N',0,null,100,13)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1002Z81000000000QDUN',1,-1,null,null,0,0,null,-1,'N',null,-1,'ccurrencyid',0,'N',1,'N','N',null,0,'ccurrencyid','pu.po_settlebill.ccurrencyid',null,'N',0,null,'1002Z810000000005OH6','@@@@',0,'币种档案',null,null,'N',0,9,'main','main',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,1,9)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1003Z810000000009GA4',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_arrstockorg_v',0,'N',1,'N','Y',null,0,'pk_arrstockorg_v','pu.po_settlebill_b.pk_arrstockorg_v','pk_arrstockorg=pk_stockorg','N',0,null,'1002Z810000000005OH6','@@@@',1,'库存组织版本,code=N',null,null,'N',1,2,'body','body',0,'2015-07-18 13:38:16','N',null,null,null,1,1,'N',1,null,100,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z8100000000018R5',1,-1,null,null,0,0,null,-1,'N',null,-1,'frowtype',0,'N',1,'N','N',null,0,'frowtype','pu.po_settlebill_b.frowtype',null,'N',0,null,'1002Z810000000005OH6','@@@@',1,null,null,null,'N',0,46,'body','body',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,100,46)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z8100000000018R7',1,-1,null,'@SYSOPER',0,0,null,-1,'N',null,-1,'billmaker',0,'N',1,'N','Y',null,0,'billmaker','pu.po_settlebill.billmaker',null,'N',0,null,'1002Z810000000005OH6','@@@@',2,'用户',null,null,'N',1,1,'tailinfo',null,0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,1,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z8100000000018R8',1,-1,null,null,0,0,null,-1,'N',null,-1,'creationtime',0,'N',1,'N','Y',null,0,'creationtime','pu.po_settlebill.creationtime',null,'N',0,null,'1002Z810000000005OH6','@@@@',2,null,null,null,'N',1,2,'tail',null,0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,1,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z8100000000018R9',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','N',null,0,'pk_org','pu.po_settlebill.pk_org',null,'N',0,null,'1002Z810000000005OH6','@@@@',0,'财务组织',null,null,'N',0,12,'main','main',0,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,1,12)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z8100000000018RA',1,-1,null,null,0,0,null,-1,'N',null,-1,'dbilldate',0,'N',1,'N','Y',null,0,'dbilldate','pu.po_settlebill.dbilldate',null,'N',0,null,'1002Z810000000005OH6','@@@@',0,null,null,null,'N',1,5,'main','main',0,'2015-03-19 20:50:52','N',null,null,null,1,1,'N',1,null,1,5)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000002VF8',1,-1,null,null,0,0,null,-1,'N',null,-1,'ndiscount',null,'N',1,'N','Y',null,0,'ndiscount','pu.po_settlebill_b.ndiscount',null,'N',0,null,'1002Z810000000005OH6',null,1,null,null,null,'N',1,29,'body','body',1,'2015-03-19 20:50:52','N',null,null,null,0,1,'N',1,null,100,29)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width,listshoworder) values('1005Z810000000002VF9',1,-1,'供应商名称',null,0,0,null,-1,'N','pk_supplier',-1,'pk_supplier.name',null,'N',1,'N','Y',null,0,'name','uap.supplier.name',null,'N',0,null,'1002Z810000000005OH6',null,1,null,'UC000-0000279',null,'N',1,41,'body','body',0,'2015-03-19 20:50:52','N',null,null,null,1,1,'N',1,null,100,41)
go

